"use client";
import Link from "next/link";
import type { OccurrenceStatus, PlannedActivityOccurrence } from "@/lib/planner/types";

function formatTime(value: string | null) { if (!value) return "Anytime"; const [hours, minutes] = value.split(":"); const hour = Number(hours); return `${hour % 12 || 12}:${minutes} ${hour >= 12 ? "PM" : "AM"}`; }
export function OccurrenceCard({ occurrence, busy, showManagement = false, onStatus, onEdit, onDelete, onProgress }: { occurrence: PlannedActivityOccurrence; busy: boolean; showManagement?: boolean; onStatus: (status: OccurrenceStatus) => void; onEdit?: () => void; onDelete?: () => void; onProgress?: () => void }) {
  const activity = occurrence.planned_activity; const completed = occurrence.status === "completed";
  return <article className="py-3">
    <div className="flex items-start gap-3"><span aria-hidden="true" className={`mt-1.5 h-2.5 w-2.5 shrink-0 rounded-full ${completed ? "bg-emerald-500" : occurrence.status === "skipped" ? "bg-amber-500" : "bg-slate-300"}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div>{activity?.user_protocol ? <p className="mb-0.5 text-xs font-medium text-violet-700">{activity.user_protocol.name} · {activity.protocol_links?.[0]?.is_required ? "Required" : "Optional"}</p> : null}<h3 className={`text-sm font-semibold ${completed ? "text-slate-500 line-through" : "text-slate-900"}`}>{activity?.title ?? "Activity unavailable"}</h3><p className="mt-0.5 text-xs capitalize text-slate-500">{formatTime(occurrence.scheduled_time)} · {activity?.activity_type ?? "activity"}</p></div><span className={`rounded-full px-2 py-1 text-xs font-medium capitalize ${completed ? "bg-emerald-50 text-emerald-700" : occurrence.status === "skipped" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600"}`}>{occurrence.status}</span></div>
      {activity?.tracking_type !== "binary" && activity?.target_value ? <div className="mt-2"><div className="flex justify-between text-xs text-slate-600"><span>{occurrence.actual_value ?? 0} / {activity.target_value} {activity.target_unit}</span><span>{Math.round(occurrence.completion_percentage ?? 0)}%</span></div><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-valuenow={Math.min(100, occurrence.completion_percentage ?? 0)} aria-valuemin={0} aria-valuemax={100}><div className={`h-full rounded-full ${completed ? "bg-emerald-500" : "bg-blue-600"}`} style={{ width: `${Math.min(100, occurrence.completion_percentage ?? 0)}%` }}/></div></div> : null}
      <div className="mt-3 flex flex-wrap gap-2" aria-label={`Actions for ${activity?.title ?? "activity"}`}>{activity?.activity_type === "workout" ? <Link href="/workouts" className="min-h-11 rounded-lg bg-blue-600 px-3 py-3 text-xs font-semibold text-white">Open Workout</Link> : null}{onProgress && (activity?.activity_type === "habit" || activity?.user_protocol_id) ? <button disabled={busy} onClick={onProgress} className="min-h-11 rounded-lg border border-blue-200 bg-blue-50 px-3 text-xs font-semibold text-blue-700 disabled:opacity-50">{activity.tracking_type === "duration" ? "Add Minutes" : activity.tracking_type === "quantity" ? "Update Progress" : "Add Note"}</button> : null}{!completed ? <button disabled={busy} onClick={() => onStatus("completed")} className="min-h-11 rounded-lg bg-blue-600 px-3 text-xs font-semibold text-white disabled:opacity-50">Complete</button> : null}{occurrence.status !== "skipped" ? <button disabled={busy} onClick={() => onStatus("skipped")} className="min-h-11 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-600">Skip</button> : null}{occurrence.status !== "planned" ? <button disabled={busy} onClick={() => onStatus("planned")} className="min-h-11 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-600">Reopen</button> : null}{showManagement && activity ? <><button disabled={busy} onClick={onEdit} className="min-h-11 px-2 text-xs font-semibold text-slate-600">Edit</button><button disabled={busy} onClick={onDelete} className="min-h-11 px-2 text-xs font-semibold text-rose-600">Delete</button></> : null}</div>
    </div></div>
  </article>;
}
