import test from 'node:test';
import assert from 'node:assert/strict';
import {assessDiet,validatePlan,applicableVersion,enrollmentDates,blankPlan,type Bundle,type Plan,type Version,type Rule} from './model.ts';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const chicken=id(1),rice=id(2),bread=id(3),legume=id(4),veg=id(5),water=id(6),tea=id(7),fruit=id(8),dairy=id(9),sauce=id(10),proteinCat=id(101),grainCat=id(102),legumeCat=id(103),vegCat=id(104),fruitCat=id(105),dairyCat=id(106),beverageCat=id(107);
export function fixture():Bundle{
 const plan:Plan={...blankPlan(),name:'Synthetic slow-style rules',rules:[{kind:'category',ref:proteinCat,action:'allow'},{kind:'category',ref:legumeCat,action:'allow'},{kind:'category',ref:vegCat,action:'allow'},{kind:'category',ref:grainCat,action:'exclude'},{kind:'category',ref:fruitCat,action:'exclude'},{kind:'category',ref:dairyCat,action:'exclude'},{kind:'food',ref:water,action:'allow'},{kind:'food',ref:tea,action:'allow'}],weekly_exceptions:[6]};
 return {enrollment:{id:id(500),diet_id:id(501),start_date:'2026-01-01',end_date:null,timezone:'America/New_York',revision:1,stopped:false},version:{id:id(600),enrollment_id:id(500),effective_from:'2026-01-01',revision:1,plan},date:'2026-01-05',fingerprint:'current',coverage:{coverage_status:'complete',diet_intake_fingerprint:'current',diet_no_intake:false,confirmed_at:'now'},entries:[{id:id(700),title:'Synthetic meal',consumed_at:'2026-01-05T12:00:00Z'}],events:[],items:[{id:id(701),nutrition_entry_id:id(700),food_id:chicken,user_food_id:null,source_name:'Chicken'}],anchors:[],components:[],userFoods:[],shared:[],private:[],catalog:{foods:[{id:chicken,name:'Chicken'},{id:rice,name:'Rice'},{id:bread,name:'Breading'},{id:legume,name:'Legumes'},{id:veg,name:'Vegetables'},{id:water,name:'Water'},{id:tea,name:'Unsweetened tea'},{id:fruit,name:'Fruit'},{id:dairy,name:'Dairy'},{id:sauce,name:'Ambiguous sauce'}],categories:[{id:proteinCat,name:'Protein',slug:'protein'},{id:grainCat,name:'Grains',slug:'grains'},{id:beverageCat,name:'Beverages',slug:'beverages'}],maps:[{food_id:chicken,category_id:proteinCat},{food_id:rice,category_id:grainCat},{food_id:bread,category_id:grainCat},{food_id:legume,category_id:legumeCat},{food_id:veg,category_id:vegCat},{food_id:fruit,category_id:fruitCat},{food_id:dairy,category_id:dairyCat},{food_id:water,category_id:beverageCat},{food_id:tea,category_id:beverageCat}],library:[]}};
}
test('deterministic statuses, completeness, exception days, exhaustive policy, specific exceptions and contradictory rules',()=>{
 const b=fixture();assert.equal(assessDiet(b).calculated_status,'adherent');b.coverage=null;assert.equal(assessDiet(b).calculated_status,'incomplete');
 b.items[0].food_id=rice;assert.equal(assessDiet(b).calculated_status,'nonadherent');b.items.push({...b.items[0],id:id(999),food_id:null,source_name:'Unknown sauce'});assert.equal(assessDiet(b).calculated_status,'nonadherent');assert.equal(assessDiet({...b,items:[b.items[1]]}).calculated_status,'needs_review');
 b.date='2026-01-03';const a=assessDiet(b);assert.equal(a.calculated_status,'planned_exception');assert.equal(a.logging_complete,false);assert.ok(a.reasons.some(r=>r.kind==='violation'));
 const c=fixture();c.version.plan.rules.push({kind:'food',ref:rice,action:'allow'});c.items[0].food_id=rice;assert.equal(assessDiet(c).calculated_status,'adherent');assert.match(assessDiet(c).reasons[0].message,/overriding/);
 c.items[0].food_id=tea;c.version.plan.rules=c.version.plan.rules.filter(r=>r.ref!==tea);assert.equal(assessDiet(c).calculated_status,'adherent');c.version.plan.mode='exhaustive';assert.equal(assessDiet(c).calculated_status,'nonadherent');
 assert.throws(()=>validatePlan({...c.version.plan,rules:[{kind:'food',ref:chicken,action:'allow'},{kind:'food',ref:chicken,action:'exclude'}]},true));validatePlan({...blankPlan(),rules:[{kind:'food',action:'allow',ref:''}]});assert.throws(()=>validatePlan(blankPlan(),true));
 const d=fixture();d.coverage!.diet_intake_fingerprint='old';assert.equal(assessDiet(d).calculated_status,'incomplete');assert.equal(assessDiet(d).confirmation_invalidated,true);d.items=[];d.entries=[];d.coverage!.diet_intake_fingerprint='current';assert.equal(assessDiet(d).calculated_status,'incomplete');d.coverage!.diet_no_intake=true;assert.equal(assessDiet(d).calculated_status,'adherent');
});
test('ingredients unknown vs absent independent of macros, composites, beverages and no parent/component double counting',()=>{
 const b=fixture();b.version.plan.rules.push({kind:'ingredient',ref:'dairy',action:'exclude'});assert.equal(assessDiet(b).calculated_status,'needs_review');b.shared=[{id:id(800),food_id:chicken,classification_key:'dairy',state:'absent',provenance:'Reviewed ingredient list',reviewed_at:'now'}];assert.equal(assessDiet(b).calculated_status,'adherent');b.private=[{id:id(801),food_id:chicken,classification_key:'dairy',state:'present',provenance:'My preparation included milk'}];assert.equal(assessDiet(b).calculated_status,'nonadherent');
 const c=fixture();c.anchors=[{id:id(750),nutrition_entry_id:c.entries[0].id,health_event_id:null,food_id:chicken,label:'Breaded chicken',method:'exact',confirmed:true}];c.components=[{id:id(751),event_food_id:id(750),food_id:chicken,label:'Chicken',source:'user_confirmed',included:true,confirmed:true},{id:id(752),event_food_id:id(750),food_id:bread,label:'Breading',source:'explicit',included:true,confirmed:false}];assert.equal(assessDiet(c).items.length,2);assert.equal(assessDiet(c).calculated_status,'nonadherent');
 const voice=structuredClone(c);assert.deepEqual(assessDiet(voice).reasons,assessDiet(c).reasons);c.components[1].included=false;assert.equal(assessDiet(c).items.length,1);assert.equal(assessDiet(c).calculated_status,'adherent');
 c.events=[{id:id(760),title:'Drink',event_date:c.date,event_type:'fluid'}];assert.equal(assessDiet(c).calculated_status,'needs_review');c.anchors.push({id:id(761),nutrition_entry_id:null,health_event_id:id(760),food_id:water,label:'Water',method:'exact',confirmed:true});assert.equal(assessDiet(c).items.length,2);assert.equal(assessDiet(c).calculated_status,'adherent');
 c.catalog.library=[{parent_food_id:chicken,component_food_id:chicken,source:'library'}];assert.equal(assessDiet(c).calculated_status,'needs_review','cycles fail closed');
});
test('calendar boundaries, no future/outside-enrollment dates and effective rule versions',()=>{
 const b=fixture();const newer:Version={...b.version,id:id(601),effective_from:'2026-03-01',revision:2,plan:{...b.version.plan,name:'New rules'}};assert.equal(applicableVersion([newer,b.version],'2026-02-28')!.id,b.version.id);assert.equal(applicableVersion([newer,b.version],'2026-03-01')!.id,newer.id);
 assert.deepEqual(enrollmentDates({...b.enrollment,start_date:'2026-03-07',end_date:'2026-03-10'},'2026-03-01','2026-03-31',new Date('2026-03-09T03:30:00Z')),['2026-03-07','2026-03-08']);assert.deepEqual(enrollmentDates({...b.enrollment,start_date:'2026-11-01'},'2026-11-01','2026-11-02',new Date('2026-11-01T05:30:00Z')),['2026-11-01']);
 const p={...blankPlan(),name:'Conflict',rules:[{kind:'category',ref:grainCat,action:'allow'},{kind:'category',ref:proteinCat,action:'exclude'}] as Rule[]};const catalog=fixture().catalog;catalog.maps.push({food_id:rice,category_id:proteinCat});assert.throws(()=>validatePlan(p,true,catalog),/conflict/);
});
