import assert from"node:assert/strict";import test from"node:test";import{calculateBaselines}from"./baselines.ts";import{calculateRecentChanges}from"./changes.ts";import{calculatePatterns}from"./patterns.ts";import{percentChange}from"./statistics.ts";import{createWeeklyRecap}from"./weeklyRecap.ts";import{addLocalDays}from"../timeline/dates.ts";import type{AnalyticsSnapshot,DailyAnalytics}from"./types.ts";
const blank=(date:string):DailyAnalytics=>({date,energy:null,mood:null,sleepQuality:null,weight:null,alcohol:null,calories:null,protein:null,carbohydrates:null,fat:null,fiber:null,caffeine:null,alcoholGrams:null,workoutCount:0,workoutMinutes:0,workoutVolume:0,habitCompleted:0,habitScheduled:0,protocolCompleted:0,protocolScheduled:0});
function days(count=100):DailyAnalytics[]{return Array.from({length:count},(_,i)=>({...blank(addLocalDays("2026-05-14",i)),energy:7,mood:7,sleepQuality:i%2?4:2,weight:180,protein:150,workoutCount:i%2,workoutMinutes:i%2?60:0,habitCompleted:4,habitScheduled:5}))}
test("7 day baseline is correct",()=>assert.equal(calculateBaselines(days(),7,"2026-08-21").find(x=>x.metricKey==="energy")?.average,7));
test("30 and 90 day windows use their requested observation counts",()=>{assert.equal(calculateBaselines(days(),30,"2026-08-21").find(x=>x.metricKey==="energy")?.observationCount,30);assert.equal(calculateBaselines(days(),90,"2026-08-21").find(x=>x.metricKey==="energy")?.observationCount,90)});
test("null observations are excluded and completeness is explicit",()=>{const x=days();x.at(-1)!.energy=null;const metric=calculateBaselines(x,7,"2026-08-21").find(x=>x.metricKey==="energy")!;assert.equal(metric.observationCount,6);assert.equal(metric.completenessPercentage,85.7)});
test("insufficient 7 day data is marked insufficient",()=>{const x=days();x.slice(-7).forEach((d,i)=>d.energy=i<3?7:null);assert.equal(calculateBaselines(x,7,"2026-08-21").find(x=>x.metricKey==="energy")?.sufficientData,false)});
test("recent changes use current seven days versus a non-overlapping prior baseline",()=>{const x=days();x.slice(-7).forEach(d=>d.energy=8);const change=calculateRecentChanges(x,"2026-08-21").find(x=>x.metricKey==="energy")!;assert.equal(change.absoluteDifference,1);assert.equal(change.currentCount,7);assert.equal(change.baselineCount,30)});
test("meaningless small changes are suppressed",()=>{const x=days();x.slice(-7).forEach(d=>d.energy=7.1);assert.equal(calculateRecentChanges(x,"2026-08-21").some(x=>x.metricKey==="energy"),false)});
test("zero baseline omits percent change",()=>assert.equal(percentChange(2,0),null));
test("sleep energy pattern applies one day lag and minimum groups",()=>{const found=calculatePatterns(days()).find(x=>x.id==="sleep-energy")!;assert.equal(found.lagDays,1);assert.ok(found.groupAObservationCount>=4);assert.ok(found.groupBObservationCount>=4)});
test("workout mood pattern compares workout and non-workout days",()=>assert.ok(calculatePatterns(days()).some(x=>x.id==="workout-mood")));
test("low-data patterns are suppressed",()=>assert.equal(calculatePatterns(days(7)).length,0));
test("pattern language remains associative",()=>{for(const x of calculatePatterns(days())){assert.doesNotMatch(x.description,/causes|triggered|proves/i);assert.match(x.description,/association/i)}});
test("weekly recap limits wins changes and patterns and generates one focus",()=>{const d=days(),snapshot:AnalyticsSnapshot={generatedAt:"",window:7,baselines:calculateBaselines(d,7,"2026-08-21").filter(x=>x.average!=null),changes:calculateRecentChanges(d,"2026-08-21"),patterns:calculatePatterns(d),symptoms:[],experiments:[],failedSources:[]},recap=createWeeklyRecap(snapshot,"2026-08-21");assert.ok(recap.wins.length<=3);assert.ok(recap.changes.length<=3);assert.ok(recap.patterns.length<=3);assert.ok(recap.nextWeekFocus);assert.ok(recap.nextWeekFocus.title)});
test("missing check-ins become the weekly focus",()=>{const snapshot:AnalyticsSnapshot={generatedAt:"",window:7,baselines:[],changes:[],patterns:[],symptoms:[],experiments:[],failedSources:[]},focus=createWeeklyRecap(snapshot,"2026-08-21").nextWeekFocus;assert.ok(focus);assert.equal(focus.title,"Build a stronger baseline")});
