import type{ExperimentObservation,PatternInsight,RecapItem,StoredWeeklyRecap,SymptomObservation,WeeklyRecapV2}from"./types.ts";
const object=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value);
const text=(value:unknown)=>typeof value==="string"?value:null;
const number=(value:unknown)=>typeof value==="number"&&Number.isFinite(value)?value:null;
const array=(value:unknown)=>Array.isArray(value)?value:[];
function items(value:unknown):RecapItem[]{return array(value).flatMap(row=>object(row)&&text(row.title)&&text(row.description)?[{title:String(row.title),description:String(row.description)}]:[])}
function metrics(value:unknown):WeeklyRecapV2["summaryMetrics"]{return array(value).flatMap(row=>object(row)&&text(row.label)&&text(row.value)?[{label:String(row.label),value:String(row.value),...(text(row.basedOn)?{basedOn:String(row.basedOn)}:{})}]:[])}
function patterns(value:unknown):PatternInsight[]{return array(value).filter((row):row is PatternInsight=>object(row)&&Boolean(text(row.id))&&Boolean(text(row.title))&&Boolean(text(row.description))&&number(row.groupAObservationCount)!==null&&number(row.groupBObservationCount)!==null)}
function symptoms(value:unknown):SymptomObservation[]{return array(value).filter((row):row is SymptomObservation=>object(row)&&Boolean(text(row.id))&&Boolean(text(row.name))&&number(row.occurrences7)!==null&&number(row.occurrences30)!==null&&number(row.previous7)!==null)}
function experiments(value:unknown):ExperimentObservation[]{return array(value).filter((row):row is ExperimentObservation=>object(row)&&Boolean(text(row.id))&&Boolean(text(row.name))&&Boolean(text(row.status))&&Boolean(text(row.phase)))}
function focus(value:unknown):RecapItem|null{return items(value==null?[]:[value])[0]??null}
export function normalizeWeeklyRecap(raw:StoredWeeklyRecap|Record<string,unknown>|null|undefined):WeeklyRecapV2|null{if(!raw)return null;const row=raw as Record<string,unknown>,pick=(snake:string,camel:string)=>row[snake]??row[camel],completenessValue=pick("data_completeness","dataCompleteness"),completeness=object(completenessValue)?Object.fromEntries(Object.entries(completenessValue).filter((entry):entry is[string,number]=>number(entry[1])!==null)):{};return{weekStart:text(pick("week_start","weekStart"))??"",weekEnd:text(pick("week_end","weekEnd"))??"",generatedAt:text(pick("generated_at","generatedAt"))??"",analysisVersion:text(pick("analysis_version","analysisVersion"))??"legacy",dataCompleteness:completeness,summaryMetrics:metrics(pick("summary_metrics","summaryMetrics")),wins:items(row.wins),changes:items(row.changes),patterns:patterns(row.patterns),symptoms:symptoms(pick("symptom_summary","symptoms")),experiments:experiments(pick("experiment_summary","experiments")),nextWeekFocus:focus(pick("next_week_focus","nextWeekFocus"))}}
