'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Button,ButtonLink,PageContainer,PageHeader,Surface,InlineNotice,controlClass} from '@/components/ui/design-system';
import {dateInZone} from '@/lib/measurements/time-window';
import {intakeLeaves,type IntakeBundle,type Catalog} from '@/lib/diets/model';
import {intakeComplete} from '@/lib/experiments/linked-evidence';
import {IntakeReview} from '@/components/diets/DietsHome';
async function request<T>(q:string,payload?:unknown):Promise<T>{const r=await fetch('/api/nutrition/intake'+(q?'?'+q:''),{cache:'no-store',...(payload?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload})}:{})});const d=await r.json();if(!r.ok)throw Error(d.error??'Intake unavailable.');return d;}
export function IntakeReviewHome(){
 const [date,setDate]=useState(''),[timezone,setTimezone]=useState(''),[data,setData]=useState<{bundle:IntakeBundle;catalog:Catalog}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[ack,setAck]=useState(false),[zero,setZero]=useState(false);const generation=useRef(0);
 useEffect(()=>{const t=setTimeout(()=>{const q=new URLSearchParams(location.search),tz=q.get('timezone')??Intl.DateTimeFormat().resolvedOptions().timeZone;setTimezone(tz);setDate(q.get('date')??dateInZone(new Date(),tz));},0);return()=>clearTimeout(t);},[]);
 const refresh=useCallback(async()=>{if(!date||!timezone)return;const g=++generation.current;setData(null);setError('');setAck(false);setZero(false);try{const d=await request<{bundle:IntakeBundle;catalog:Catalog}>(new URLSearchParams({date,timezone}).toString());if(g===generation.current)setData(d);}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'Unable to load.');}},[date,timezone]);
 useEffect(()=>{const requests=generation,t=setTimeout(()=>void refresh(),0);const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{clearTimeout(t);requests.current++;window.removeEventListener('focus',focus);};},[refresh]);
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Save failed; input preserved.');}finally{setBusy(false);}}
 const leaves=data?intakeLeaves(data.bundle):[];
 return <PageContainer narrow><ButtonLink href="/health/nutrition" variant="tertiary">← Nutrition</ButtonLink><PageHeader title="Intake completeness and ingredient review" description="Review existing food and drink sources without enrolling in a diet."/><ButtonLink href="/health/nutrition" variant="secondary">Log / edit intake</ButtonLink><Surface className="mt-4 grid gap-3"><label className="grid gap-1 text-sm">Intake source date<input type="date" className={controlClass} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="grid gap-1 text-sm">Intake timezone<input className={controlClass} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><Button onClick={()=>void refresh()}>Refresh intake sources</Button>{error?<InlineNotice>{error}</InlineNotice>:null}{data?<><p>{intakeComplete(data.bundle)?'Food and beverage logging confirmed complete':'Logging incomplete or confirmation invalidated'}</p><label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>All food and beverage intake for this date has been logged.</label>{!leaves.length?<label className="flex gap-2 text-sm"><input type="checkbox" checked={zero} onChange={e=>setZero(e.target.checked)}/>This was deliberately a no-intake day.</label>:null}<Button disabled={busy||!ack||(!leaves.length&&!zero)} onClick={()=>void perform(async()=>{await request('',{date,timezone,fingerprint:data.bundle.fingerprint,no_intake:zero});await refresh();})}>Confirm complete food and drink logging</Button></>:<p role="status">{error?'Sources unavailable.':'Loading intake…'}</p>}</Surface>{data?<Surface className="mt-4 min-w-0"><h2 className="font-semibold">Existing intake and private evidence</h2><p className="text-sm">Reviewed ingredient facts apply to the selected log or, when explicitly chosen, your logs of a canonical food. Diet-specific permissions never change ingredient facts.</p>{leaves.map((item,i)=><IntakeReview key={`${date}:${i}:${item.food_id}`} item={item} catalog={data.catalog} busy={busy} perform={perform} refresh={refresh}/>)}</Surface>:null}</PageContainer>;
}
