'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {Button,ButtonLink,PageContainer,PageHeader,Surface,InlineNotice,controlClass} from '@/components/ui/design-system';
import {dateInZone} from '@/lib/measurements/time-window';
import type {SupplementDay,SupplementProduct} from '@/lib/experiments/linked-evidence';
async function request<T>(query:string,action?:string,payload?:unknown):Promise<T>{const r=await fetch('/api/nutrition/supplements'+(query?'?'+query:''),{cache:'no-store',...(action?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload})}:{})});const d=await r.json();if(!r.ok)throw Error(d.error??'Supplements unavailable.');return d;}
export function SupplementsHome(){
 const [date,setDate]=useState(''),[timezone,setTimezone]=useState(''),[data,setData]=useState<{products:SupplementProduct[];day:SupplementDay}|null>(null),[error,setError]=useState(''),[name,setName]=useState(''),[formulation,setFormulation]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[assign,setAssign]=useState<Record<string,string>>({});const generation=useRef(0);
 useEffect(()=>{const t=setTimeout(()=>{const q=new URLSearchParams(location.search),tz=q.get('timezone')??Intl.DateTimeFormat().resolvedOptions().timeZone;setTimezone(tz);setDate(q.get('date')??dateInZone(new Date(),tz));},0);return()=>clearTimeout(t);},[]);
 const refresh=useCallback(async()=>{if(!date||!timezone)return;const g=++generation.current;setData(null);setError('');setAck(false);try{const d=await request<{products:SupplementProduct[];day:SupplementDay}>(new URLSearchParams({date,timezone}).toString());if(g===generation.current)setData(d);}catch(e){if(g===generation.current)setError(e instanceof Error?e.message:'Unable to load.');}},[date,timezone]);
 useEffect(()=>{const requests=generation;const t=setTimeout(()=>void refresh(),0);const focus=()=>void refresh();window.addEventListener('focus',focus);return()=>{clearTimeout(t);requests.current++;window.removeEventListener('focus',focus);};},[refresh]);
 async function save(action:string,payload:unknown){setBusy(true);setError('');try{await request('',action,payload);setNotice('Saved. Supplement completeness and product identities apply to these source logs.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Save failed; input preserved.');}finally{setBusy(false);}}
 return <PageContainer narrow><ButtonLink href="/health/nutrition" variant="tertiary">← Nutrition</ButtonLink><PageHeader title="Supplements" description="Review identities on existing logs and confirm date-specific supplement logging."/><p className="text-sm">Products and formulations are explicitly reviewed; matching names are never automatically combined. Log or edit dose and time in Today. No dosing schedule or recommendation is created.</p><ButtonLink href="/today" variant="secondary" className="mt-3">Log / edit supplements in Today</ButtonLink><Surface className="mt-4 grid gap-3"><label className="grid gap-1 text-sm">Supplement source date<input type="date" className={controlClass} value={date} onChange={e=>setDate(e.target.value)}/></label><label className="grid gap-1 text-sm">Source timezone<input className={controlClass} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label><Button onClick={()=>void refresh()}>Refresh supplement records</Button>{error?<InlineNotice>{error}</InlineNotice>:null}{notice?<p role="status">{notice}</p>:null}
 {!data?<p role="status">{error?'Records unavailable. Retry refresh.':'Loading supplement records…'}</p>:<><p>{data.day.coverage?.complete&&data.day.coverage.fingerprint===data.day.fingerprint?'Supplement logging confirmed complete':'Supplement logging is not confirmed complete'}</p>{data.day.events.length?<ul className="grid gap-3">{data.day.events.map(e=><li className="grid min-w-0 gap-2 rounded-lg border p-3" key={e.id}><p className="break-words">{e.supplement_name??e.title} · {e.dose_amount??'Unknown dose'} {e.dose_unit??''} · {e.event_time??'Unknown time'}</p><label className="grid gap-1 text-sm">Reviewed product for {e.supplement_name??e.title}<select className={controlClass} value={assign[e.id]??e.supplement_product_id??''} onChange={x=>setAssign(a=>({...a,[e.id]:x.target.value}))}><option value="">Unreviewed identity</option>{data.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.formulation}</option>)}</select></label><Button disabled={busy||!(assign[e.id]??e.supplement_product_id)} variant="secondary" onClick={()=>void save('identity',{event_id:e.id,product_id:assign[e.id]??e.supplement_product_id})}>Confirm product identity</Button></li>)}</ul>:<p>No supplement use recorded. Empty logs alone do not establish no use.</p>}
 <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>All supplement intake for this date is logged, including deliberate no use if the list is empty. Food completeness is separate.</label><Button disabled={busy||!ack} onClick={()=>void save('confirm',{date,timezone,fingerprint:data.day.fingerprint})}>Confirm complete supplement logging</Button></>}
 </Surface><Surface className="mt-4 grid gap-3"><h2 className="font-semibold">Identify a tracked product/formulation</h2><p className="text-sm">Use a precise label from your existing supplement records. Create separate identities for different formulations. Identity definitions are immutable; create another identity when the formulation changes.</p><label className="grid gap-1 text-sm">Supplement product name<input className={controlClass} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label className="grid gap-1 text-sm">Product/formulation label<input className={controlClass} maxLength={200} value={formulation} onChange={e=>setFormulation(e.target.value)}/></label><Button disabled={busy||name.trim().length<2||!formulation.trim()} onClick={()=>void save('product',{name,formulation})}>Create private product identity</Button></Surface></PageContainer>;
}
