import type { SupabaseClient } from "@supabase/supabase-js";
import { episodeImpacts, episodeTypes, episodeUpdateStatuses, type ConditionEpisode, type CreateEpisodeInput, type EpisodeSummary, type EpisodeUpdateInput } from "./types.ts";

const select = "*,user_condition:user_conditions(id,custom_condition_name,condition:conditions(name,preferred_episode_label)),symptom_links:episode_symptom_links(user_symptom_event_id,symptom_event:user_symptom_events(id,started_at,ended_at,severity,custom_symptom_name,symptom:symptoms(name))),updates:episode_updates(id,recorded_at,overall_severity,functional_impact,status,notes)";
async function uid(c:SupabaseClient){const{data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("AUTH_REQUIRED");return data.user.id}
export function episodeLabel(condition:{preferred_episode_label?:string|null}|null|undefined){return condition?.preferred_episode_label?.trim()||"Episode"}
export function episodeTypeForLabel(label:string){const value=label.toLowerCase();return episodeTypes.find(type=>value.includes(type))??"episode"}
export function validateCreateEpisode(x:CreateEpisodeInput){if(!x.userConditionId)return "Choose a condition.";if(!episodeTypes.includes(x.episodeType))return "Choose a valid episode type.";if(!x.startedAt||Number.isNaN(new Date(x.startedAt).valueOf()))return "Choose a valid start time.";if(x.overallSeverity!=null&&(!Number.isInteger(x.overallSeverity)||x.overallSeverity<1||x.overallSeverity>10))return "Severity must be between 1 and 10.";if(x.functionalImpact&&!episodeImpacts.includes(x.functionalImpact))return "Choose a valid functional impact.";if((x.notes?.length??0)>2000)return "Notes must be 2,000 characters or fewer.";return null}
export function validateEpisodeUpdate(x:EpisodeUpdateInput){if(!episodeUpdateStatuses.includes(x.status))return "Choose a valid status.";if(x.overallSeverity!=null&&(!Number.isInteger(x.overallSeverity)||x.overallSeverity<1||x.overallSeverity>10))return "Severity must be between 1 and 10.";if(x.functionalImpact&&!episodeImpacts.includes(x.functionalImpact))return "Choose a valid functional impact.";if((x.notes?.length??0)>2000)return "Notes must be 2,000 characters or fewer.";return null}
export async function getEpisodes(c:SupabaseClient,conditionId?:string){const user=await uid(c);let q=c.from("condition_episodes").select(select).eq("user_id",user).is("archived_at",null).order("started_at",{ascending:false});if(conditionId)q=q.eq("user_condition_id",conditionId);const{data,error}=await q;if(error)throw new Error("We couldn’t load episodes.");return(data??[])as unknown as ConditionEpisode[]}
export async function getEpisode(c:SupabaseClient,id:string){const user=await uid(c);const{data,error}=await c.from("condition_episodes").select(select).eq("id",id).eq("user_id",user).single();if(error)throw new Error("Episode not found.");return data as unknown as ConditionEpisode}
export async function createEpisode(c:SupabaseClient,x:CreateEpisodeInput){const message=validateCreateEpisode(x);if(message)throw new Error(message);const{data,error}=await c.rpc("create_condition_episode",{input:{user_condition_id:x.userConditionId,episode_type:x.episodeType,title:x.title?.trim()||null,started_at:x.startedAt,overall_severity:x.overallSeverity??null,functional_impact:x.functionalImpact??null,notes:x.notes?.trim()||null,existing_symptom_event_ids:x.existingSymptomEventIds??[],new_symptoms:(x.newSymptoms??[]).map(s=>({symptom_id:s.symptomId??null,custom_name:s.customName?.trim()||null,started_at:s.startedAt??x.startedAt,severity:s.severity??null,notes:s.notes?.trim()||null}))}});if(error)throw new Error("We couldn’t save this episode.");return data as ConditionEpisode}
export async function updateEpisode(c:SupabaseClient,id:string,x:EpisodeUpdateInput){const message=validateEpisodeUpdate(x);if(message)throw new Error(message);const{data,error}=await c.rpc("update_condition_episode",{target_id:id,input:{recorded_at:x.recordedAt??new Date().toISOString(),overall_severity:x.overallSeverity??null,functional_impact:x.functionalImpact??null,status:x.status,notes:x.notes?.trim()||null,symptom_event_ids:x.symptomEventIds??[]}});if(error)throw new Error("We couldn’t save this update.");return data as ConditionEpisode}
export function episodeDay(startedAt:string,now=new Date()){return Math.max(1,Math.floor((now.getTime()-new Date(startedAt).getTime())/86400000)+1)}
export function durationHours(e:Pick<ConditionEpisode,"started_at"|"ended_at">,now=new Date()){return Math.max(0,((e.ended_at?new Date(e.ended_at):now).getTime()-new Date(e.started_at).getTime())/3600000)}
export function peakSeverity(e:Pick<ConditionEpisode,"overall_severity"|"updates">){return [e.overall_severity,...(e.updates??[]).map(x=>x.overall_severity)].filter((x):x is number=>x!=null).reduce<number|null>((max,x)=>max==null?x:Math.max(max,x),null)}
export function summarizeEpisodes(rows:ConditionEpisode[],now=new Date()):EpisodeSummary{const ago=(d:number)=>new Date(now.getTime()-d*86400000),starts=(d:number)=>rows.filter(x=>new Date(x.started_at)>=ago(d)).length,resolved=rows.filter(x=>x.status==="resolved"&&x.ended_at),mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null,names=new Map<string,number>();for(const e of rows)for(const l of e.symptom_links??[]){const s=l.symptom_event,name=s?.symptom?.name??s?.custom_symptom_name;if(name)names.set(name,(names.get(name)??0)+1)}const latest=resolved.sort((a,b)=>b.ended_at!.localeCompare(a.ended_at!))[0];return{count30:starts(30),count90:starts(90),averageResolvedDurationHours:mean(resolved.map(x=>durationHours(x))),averageStartingSeverity:mean(rows.flatMap(x=>x.overall_severity==null?[]:[x.overall_severity])),averagePeakSeverity:mean(rows.flatMap(x=>{const p=peakSeverity(x);return p==null?[]:[p]})),daysSinceLastResolved:latest?Math.floor((now.getTime()-new Date(latest.ended_at!).getTime())/86400000):null,commonSymptoms:[...names].sort((a,b)=>b[1]-a[1]).slice(0,3).map(([name,count])=>({name,count}))}}
export function getEpisodePreOnsetWindow(startedAt:string,hours:24|48|72|168){const end=new Date(startedAt),start=new Date(end.getTime()-hours*3600000);return{start:start.toISOString(),end:end.toISOString()}}
export function episodeOutcomeValues(rows:ConditionEpisode[],type:"episode_frequency"|"episode_duration"|"episode_severity"|"episode_impact",start:string,end:string){const inRange=rows.filter(x=>x.started_at>=start&&x.started_at<end);if(type==="episode_frequency")return inRange.map(()=>1);if(type==="episode_duration")return inRange.filter(x=>x.ended_at).map(x=>durationHours(x));if(type==="episode_severity")return inRange.flatMap(x=>{const p=peakSeverity(x);return p==null?[]:[p]});const rank={none:0,mild:1,moderate:2,significant:3,severe:4};return inRange.flatMap(x=>x.functional_impact?[rank[x.functional_impact]]:[])}
