import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { database } from "../security/test-database.ts";
import { foodPersistence, resolveFood, type FoodCatalog, type Category, type CatalogComponent } from "./food-resolution.ts";

const owner = "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa", other = "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb";
test("real migrations: starter library, atomic mixed ingestion, category exclusions, owner CRUD, export and deletion", async t => {
  const db = await database(); t.after(() => db.close());
  // The repository's original health_events DDL is absent; explicitly extend the synthetic baseline.
  await db.exec("alter table public.health_events add column event_date date, add column event_time time, add column event_type text, add column amount text;");
  const count = async (table: string) => (await db.query<{ n: number }>(`select count(*)::int n from public.${table}`)).rows[0].n;
  const before = await Promise.all([count("foods"), count("food_aliases"), count("food_components"), count("food_category_map")]);
  await db.exec(readFileSync(new URL("../../supabase/migrations/202609240004_starter_composite_foods.sql", import.meta.url), "utf8"));
  assert.deepEqual(await Promise.all([count("foods"), count("food_aliases"), count("food_components"), count("food_category_map")]), before);
  const foods = (await db.query<{ id: string; name: string; aliases: string[] }>("select f.id,f.name,coalesce(array_agg(a.alias) filter(where a.id is not null),'{}') aliases from public.foods f left join public.food_aliases a on a.food_id=f.id group by f.id")).rows;
  const categories = (await db.query<Category & { food_id: string }>("select c.id,c.slug,c.name,m.food_id from public.food_categories c join public.food_category_map m on c.id=m.category_id")).rows;
  const catalog: FoodCatalog = { foods: foods.map(food => ({ ...food, categories: categories.filter(c => c.food_id === food.id) })), components: (await db.query<CatalogComponent>("select * from public.food_components")).rows };
  for (const name of ["pepperoni pizza", "turkey sandwich", "cheeseburger", "peanut butter sandwich", "Greek yogurt with berries", "salad with chicken", "cereal with milk"]) assert.ok(resolveFood(name, name, catalog).components.length >= 2, name);
  const pizza = resolveFood("pepperoni pizza", "pepperoni pizza without cheese", catalog);
  const event = { user_id: owner, event_date: "2026-09-24", event_time: "12:00", event_type: "food", title: pizza.label, amount: "2 slices", input_method: "voice" };
  const rows = [{ event, food: foodPersistence(pizza) }, { event: { ...event, event_type: "exercise", title: "Walk", amount: null }, food: null }];
  const ingest = (value: unknown) => db.query("select public.ingest_health_events_with_food($1::jsonb)", [JSON.stringify(value)]);
  await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${owner}',false);`);
  assert.ok(await count("food_components") > 0);
  for (let i = 0; i < 7; i++) assert.equal((await db.query<{ allowed: boolean }>("select public.axvital_consume_api_budget('http/nutrition/resolve:POST') allowed")).rows[0].allowed, i < 6);
  for (const statement of ["insert into public.food_components default values", "update public.food_components set source='explicit'", "delete from public.food_components"]) await assert.rejects(db.exec(statement), /permission denied/);
  await ingest(rows);
  assert.equal(await count("health_events"), 2); assert.equal(await count("health_event_foods"), 1); assert.equal(await count("health_event_food_components"), 4);
  assert.deepEqual((await db.query<{ slug: string }>("select distinct c.slug from public.health_event_food_category_exposures e join public.food_categories c on c.id=e.category_id order by c.slug")).rows.map(row => row.slug), ["grains", "processed_meat", "vegetables"]);
  const parent = (await db.query<{ id: string; health_event_id: string }>("select id,health_event_id from public.health_event_foods")).rows[0];
  await db.exec(`update public.health_event_food_components set included=true,confirmed=true where event_food_id='${parent.id}' and source='explicit';`);
  assert.equal(await count("health_event_food_category_exposures"), 4);
  const bad = structuredClone(rows); bad[0].food!.components[1].food_id = other;
  await assert.rejects(ingest([rows[1], bad[0]]), /row-level security|foreign key/);
  assert.equal(await count("health_events"), 2, "component failure rolls back earlier non-food event too");
  await assert.rejects(ingest([{ ...rows[0], event: { ...event, user_id: other } }]), /INVALID_EVENT/);
  for (const value of [null, {}, [], [{ event: { ...event, event_type: null }, food: null }], [{ event, food: { label: event.title } }]]) await assert.rejects(ingest(value));
  const exported = (await db.query<{ payload: { data: Record<string, unknown[]> } }>("select public.axvital_export_account() payload")).rows[0].payload;
  assert.equal(exported.data.health_event_foods.length, 1); assert.equal(exported.data.health_event_food_components.length, 4);
  await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
  for (const table of ["health_events", "health_event_foods", "health_event_food_components", "health_event_food_category_exposures"]) assert.equal(await count(table), 0, table);
  await assert.rejects(db.exec(`insert into public.health_event_foods(user_id,health_event_id,label,method) values('${other}','${parent.health_event_id}','forged','provisional')`), /row-level security|foreign key/);
  await assert.rejects(db.exec(`insert into public.health_event_food_components(user_id,event_food_id,label,source) values('${other}','${parent.id}','forged','explicit')`), /row-level security|foreign key/);
  await db.exec(`update public.health_event_food_components set included=false; delete from public.health_event_foods; select set_config('request.jwt.claim.sub','${owner}',false);`);
  assert.equal(await count("health_event_foods"), 1); assert.equal(await count("health_event_food_category_exposures"), 4);
  await db.exec(`reset role; select public.axvital_begin_account_deletion('${owner}'); update public.account_deletions set billing_closed=true where user_id='${owner}';delete from auth.users where id='${owner}';`);
  assert.equal(await count("health_event_foods"), 0); assert.equal(await count("health_event_food_components"), 0); assert.equal(await count("food_components"), before[2]);
  await db.exec("set role anon;");
  for (const table of ["food_components", "health_event_foods", "health_event_food_components", "health_event_food_category_exposures"]) await assert.rejects(count(table), /permission denied/);
  await assert.rejects(ingest(rows), /permission denied/);
});
