import test from "node:test";
import assert from "node:assert/strict";
import { database } from "../security/test-database.ts";
import { foodPersistence, provisionalFood } from "./food-resolution.ts";
const owner = "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa", other = "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb";
test("manual/voice snapshots have exact parity; mixed transaction is atomic, idempotent, private and nutrition-only for food", async t => {
  const db = await database(); t.after(() => db.close());
  await db.exec("alter table public.health_events add column event_date date, add column event_time time, add column event_type text, add column dose text, add column dose_amount numeric, add column dose_unit text;");
  const ref = (await db.query<{ food: string; serving: string }>("select f.id food,s.id serving from foods f join food_servings s on s.food_id=f.id where f.slug='egg' and s.is_default")).rows[0];
  const food = foodPersistence({ ...provisionalFood("eggs"), food_id: ref.food, method: "alias" });
  const nutrition = { status: "recorded", serving_id: ref.serving, multiplier: 3, consumed_at: "2026-09-25T12:00:00Z", meal_type: "breakfast", notes: null, tags: [], stated_amount: "three eggs", event_type: "food" };
  const rows = [{ kind: "nutrition", food, nutrition }, { kind: "health", event: { user_id: owner, event_type: "supplement", title: "creatine", event_date: "2026-09-25", event_time: "12:00", input_method: "voice", dose_amount: 5, dose_unit: "grams" } }, { kind: "health", event: { user_id: owner, event_type: "symptom", title: "knee hurts", event_date: "2026-09-25", event_time: "12:00", input_method: "voice" } }];
  const save = (key: string, value: unknown = rows) => db.query("select ingest_voice_nutrition($1,$2::jsonb)", [key, JSON.stringify(value)]);
  const count = async (table: string) => (await db.query<{ n: number }>(`select count(*)::int n from public.${table}`)).rows[0].n;
  await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${owner}',false);`);
  const manual = (await db.query<{ id: string }>("select log_food_atomic($1,$2,null,3,'2026-09-25T12:00:00Z','breakfast',null,'manual') id", [ref.food, ref.serving])).rows[0].id;
  const key = "00000000-0000-4000-8000-000000000001";
  await save(key); await save(key);
  assert.equal(await count("nutrition_entries"), 2); assert.equal(await count("health_events"), 2); assert.equal(await count("voice_log_receipts"), 1);
  assert.equal((await db.query("select * from health_events where event_type='food'")).rows.length, 0);
  const snapshots = (await db.query<{ food_id: string; food_serving_id: string; calories: string; protein_grams: string; carbohydrate_grams: string; fat_grams: string; quantity_multiplier: string }>("select food_id,food_serving_id,calories,protein_grams,carbohydrate_grams,fat_grams,quantity_multiplier from nutrition_entry_items order by id")).rows;
  assert.deepEqual(snapshots[0], snapshots[1]); assert.equal(Number(snapshots[0].calories), 216);
  assert.equal((await db.query<{ source_type: string }>("select source_type from nutrition_entries where id=$1", [manual])).rows[0].source_type, "manual");
  const primary = (await db.query<{ id: string }>("select id from nutrition_entries where source_type='voice'")).rows[0].id;
  assert.equal((await db.query<{ nutrition_entry_id: string; health_event_id: string | null }>("select nutrition_entry_id,health_event_id from health_event_foods")).rows[0].health_event_id, null);
  const invalid = structuredClone(rows); invalid[2].event!.user_id = other;
  await assert.rejects(save("00000000-0000-4000-8000-000000000002", invalid), /INVALID_EVENT/);
  assert.equal(await count("nutrition_entries"), 2); assert.equal(await count("voice_log_receipts"), 1);
  await assert.rejects(save(key, [rows[0]]), /VOICE_RETRY_CHANGED/);
  const pending = { kind: "nutrition", food: foodPersistence(provisionalFood("Family stew")), nutrition: { ...nutrition, status: "incomplete", serving_id: null, multiplier: null, accept_incomplete: true } };
  await save("00000000-0000-4000-8000-000000000003", [pending]);
  const incomplete = (await db.query<{ id: string }>("select id from nutrition_entries where nutrition_status='incomplete'")).rows[0].id;
  assert.equal(await count("nutrition_entry_items"), 2);
  await db.query("select complete_nutrition_entry($1,$2,$3,null,2)", [incomplete, ref.food, ref.serving]);
  assert.equal(await count("nutrition_entries"), 3); assert.equal(await count("nutrition_entry_items"), 3);
  assert.equal(Number((await db.query<{ calories: string }>("select calories from nutrition_entry_items where nutrition_entry_id=$1", [incomplete])).rows[0].calories), 144);
  await assert.rejects(db.query("select complete_nutrition_entry($1,$2,$3,null,2)", [incomplete, ref.food, ref.serving]), /ENTRY_NOT_INCOMPLETE/);
  await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
  for (const table of ["nutrition_entries", "nutrition_entry_items", "health_event_foods", "voice_log_receipts", "nutrition_food_category_exposures"]) assert.equal(await count(table), 0, table);
  await assert.rejects(db.query("select complete_nutrition_entry($1,$2,$3,null,2)", [primary, ref.food, ref.serving]), /ENTRY_NOT_INCOMPLETE/);
  await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);`);
  const exported = (await db.query<{ payload: { data: Record<string, unknown[]> } }>("select axvital_export_account() payload")).rows[0].payload;
  assert.equal(exported.data.nutrition_entries.length, 3); assert.equal(exported.data.health_event_foods.length, 2);
  await db.exec(`reset role; select axvital_begin_account_deletion('${owner}');update account_deletions set billing_closed=true where user_id='${owner}';delete from auth.users where id='${owner}';`);
  for (const table of ["nutrition_entries", "nutrition_entry_items", "health_event_foods", "voice_log_receipts"]) assert.equal(await count(table), 0);
});
