"use client";
import Link from "next/link";
import {useRef,useState,type FormEvent} from "react";
import {Button,InlineNotice,controlClass} from "@/components/ui/design-system";
import {supabase} from "@/lib/supabase/client";
export function DeleteAccountForm({enabled}:{enabled:boolean}){
  const[confirmation,setConfirmation]=useState(""),[password,setPassword]=useState(""),[accepted,setAccepted]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState(""),[deleted,setDeleted]=useState(false);const busy=useRef(false);
  async function submit(event:FormEvent){event.preventDefault();if(busy.current||!enabled||confirmation!=="DELETE"||!accepted||!password)return;busy.current=true;setPending(true);setMessage("");try{
    const response=await fetch("/api/account/delete",{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirmation,password,acceptConsequences:accepted})});
    const result=await response.json();
    if(!response.ok||result.deleted!==true){setMessage(result.error==="REAUTH_REQUIRED"?"We couldn't verify your current password. Sign in again if needed, then retry.":result.error==="DELETION_UNAVAILABLE"?"Account deletion is temporarily unavailable. Please contact Support.":"We couldn't confirm account deletion. Billing may already be closed. Try signing in to check whether your account still exists, then retry or contact Support.");return;}
    setDeleted(true);
    const logout=await supabase.auth.signOut({scope:"local"});
    if(logout.error){setMessage("Your account was deleted, but this browser could not clear its session. Clear AXVital site data in your browser settings to remove the remaining local session. Closing a tab alone may not clear it.");return;}
    window.location.replace("/account-deleted");
  }catch{setMessage("We couldn't confirm the result. Deletion may have completed and billing may already be closed. Check whether you can sign in before retrying.")}finally{setPassword("");setPending(false);busy.current=false}}
  if(deleted)return <div className="space-y-3"><InlineNotice tone="success">Your account was deleted.</InlineNotice>{message&&<InlineNotice tone="info">{message}</InlineNotice>}<Link href="/account-deleted" className="text-blue-700 underline">Continue</Link></div>;
  return <form onSubmit={submit} className="space-y-4 border-t border-slate-200 pt-5">{!enabled&&<InlineNotice tone="info">Self-service deletion is not enabled on this deployment yet. <Link href="/contact" className="underline">Contact Support</Link> for help.</InlineNotice>}<fieldset disabled={pending||!enabled} className="space-y-4"><label className="block text-sm font-semibold">Current password<input className={`${controlClass} mt-2 w-full`} type="password" autoComplete="current-password" required maxLength={1024} value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="text-sm text-slate-600">Your current password is verified with the authentication provider. If you cannot use password sign-in, recover your password or contact Support.</p><label className="block text-sm font-semibold">Type DELETE to confirm<input className={`${controlClass} mt-2 w-full`} value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off" spellCheck={false} required pattern="DELETE"/></label><label className="flex min-h-11 items-start gap-3 text-sm"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0" checked={accepted} onChange={e=>setAccepted(e.target.checked)} required/><span>I understand that my account and application data will be deleted, subscriptions canceled immediately, and remaining paid access ended. This cannot be undone through the app.</span></label><Button className="bg-red-700 text-white hover:bg-red-800" disabled={!accepted||confirmation!=="DELETE"||!password||pending}>{pending?"Closing your account...":"Permanently delete my account"}</Button></fieldset>{message&&<InlineNotice>{message}</InlineNotice>}<Link className="inline-flex min-h-11 items-center text-blue-700 underline" href="/settings">Keep my account</Link></form>;
}
