'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button,ButtonLink,PageContainer,PageHeader,Surface,InlineNotice,controlClass} from '@/components/ui/design-system';
import {blankPlan,ingredientKeys,validatePlan,type Plan,type Diet,type Enrollment,type Catalog,type Rule,type Leaf} from '@/lib/diets/model';
import {dietRequest,type DietMetadata,type DailyResponse} from '@/lib/diets/client';
import {dateInZone,shiftDate} from '@/lib/measurements/time-window';
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid min-w-0 gap-1 text-sm font-medium">{label}{children}</label>;}
const weekdays=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const labels={adherent:'Adherent',nonadherent:'Nonadherent',needs_review:'Needs review',incomplete:'Incomplete',planned_exception:'Planned exception'};
function PlanEditor({plan,setPlan,catalog}:{plan:Plan;setPlan:(p:Plan)=>void;catalog:Catalog}){
 const [search,setSearch]=useState(''),[exceptionDate,setExceptionDate]=useState('');
 const changeRule=(index:number,next:Partial<Rule>)=>setPlan({...plan,rules:plan.rules.map((r,i)=>i===index?{...r,...next}:r)});
 return <div className="grid gap-4"><Field label="Diet name"><input className={controlClass} maxLength={120} value={plan.name} onChange={e=>setPlan({...plan,name:e.target.value})}/></Field><Field label="Instructions (optional, not compliance rules)"><textarea className={controlClass} maxLength={2000} value={plan.instructions} onChange={e=>setPlan({...plan,instructions:e.target.value})}/></Field><Field label="Allowed-list policy"><select className={controlClass} value={plan.mode} onChange={e=>setPlan({...plan,mode:e.target.value as Plan['mode']})}><option value="illustrative">Illustrative: evaluate unlisted foods against other rules</option><option value="exhaustive">Exhaustive: only allowed foods/categories</option></select></Field>
 <p className="text-sm">Specific food rules override category rules. Ingredient restrictions still apply. Resolve equal-specificity conflicts before following. Quantity-limited rules are deferred; this sprint checks identity and ingredients.</p>
 <Field label="Filter canonical food choices"><input className={controlClass} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search foods or aliases"/></Field>
 {plan.rules.map((r,index)=>{const options=r.kind==='food'?catalog.foods.filter(f=>f.id===r.ref||[f.name,...(f.common_aliases??[])].some(n=>n.toLowerCase().includes(search.toLowerCase()))):catalog.categories;return <fieldset className="grid min-w-0 gap-3 rounded-lg border p-3" key={index}><legend className="px-1 text-sm font-semibold">Rule {index+1}</legend><div className="grid gap-3 sm:grid-cols-2"><Field label={`Rule ${index+1} kind`}><select className={controlClass} value={r.kind} onChange={e=>changeRule(index,{kind:e.target.value as Rule['kind'],ref:'',action:e.target.value==='ingredient'?'exclude':r.action})}><option value="food">Canonical food / specific exception</option><option value="category">Food category</option><option value="ingredient">Ingredient restriction</option></select></Field><Field label={`Rule ${index+1} action`}><select className={controlClass} value={r.action} disabled={r.kind==='ingredient'} onChange={e=>changeRule(index,{action:e.target.value as Rule['action']})}><option value="allow">Allow</option><option value="exclude">Exclude</option></select></Field></div><Field label={`Rule ${index+1} subject`}><select className={controlClass} value={r.ref} onChange={e=>changeRule(index,{ref:e.target.value})}><option value="">Choose {r.kind}</option>{r.kind==='ingredient'?ingredientKeys.map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>):options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><p className="text-sm">{r.action==='allow'?'Allows':'Excludes'} {r.kind==='ingredient'?r.ref.replaceAll('_',' '):options.find(x=>x.id===r.ref)?.name??'a subject not yet selected'}</p><Button type="button" variant="tertiary" onClick={()=>setPlan({...plan,rules:plan.rules.filter((_,i)=>i!==index)})}>Remove rule {index+1}</Button></fieldset>;})}
 <div className="flex flex-wrap gap-2">{(['food','category','ingredient'] as const).map(kind=><Button key={kind} type="button" variant="secondary" onClick={()=>setPlan({...plan,rules:[...plan.rules,{kind,action:kind==='ingredient'?'exclude':'allow',ref:''}]})}>Add {kind} rule</Button>)}</div>
 <details><summary className="cursor-pointer py-2 font-semibold">Planned unrestricted exception days</summary><p className="mb-3 text-sm">Exception days retain intake and completeness, and are counted separately from adherent regular days.</p><fieldset className="grid grid-cols-2 gap-3"><legend className="sr-only">Recurring exception weekdays</legend>{weekdays.map((name,i)=><label className="flex items-center gap-2 text-sm" key={name}><input type="checkbox" checked={plan.weekly_exceptions.includes(i)} onChange={e=>setPlan({...plan,weekly_exceptions:e.target.checked?[...plan.weekly_exceptions,i]:plan.weekly_exceptions.filter(d=>d!==i)})}/>{name}</label>)}</fieldset><div className="mt-4 grid gap-2"><Field label="Individual exception date"><input type="date" className={controlClass} value={exceptionDate} onChange={e=>setExceptionDate(e.target.value)}/></Field><Button type="button" variant="secondary" disabled={!exceptionDate||plan.dated_exceptions.includes(exceptionDate)} onClick={()=>{setPlan({...plan,dated_exceptions:[...plan.dated_exceptions,exceptionDate]});setExceptionDate('');}}>Add dated exception</Button>{plan.dated_exceptions.map(d=><div className="flex flex-wrap items-center gap-2" key={d}><span>{d}</span><Button type="button" variant="tertiary" onClick={()=>setPlan({...plan,dated_exceptions:plan.dated_exceptions.filter(x=>x!==d)})}>Remove {d}</Button></div>)}</div></details></div>;
}
export function DietsHome(){
 const [meta,setMeta]=useState<DietMetadata|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<Diet|null>(null),[plan,setPlan]=useState<Plan>(blankPlan),[editor,setEditor]=useState(false),[showArchived,setShowArchived]=useState(false);
 const [start,setStart]=useState(''),[end,setEnd]=useState(''),[timezone,setTimezone]=useState(''),[enrollmentId,setEnrollmentId]=useState(''),[date,setDate]=useState(''),[daily,setDaily]=useState<DailyResponse|null>(null),[pending,setPending]=useState(false),[dailyError,setDailyError]=useState('');
 const [effective,setEffective]=useState(''),[historicalAck,setHistoricalAck]=useState(false),[stopDate,setStopDate]=useState(''),[completeAck,setCompleteAck]=useState(false),[noIntake,setNoIntake]=useState(false);
 const generation=useRef(0),draftId=useRef<string|null>(null),followId=useRef<string|null>(null);
 const enrollment=meta?.enrollments.find(e=>e.id===enrollmentId);
 const chooseEnrollment=useCallback((e:Enrollment)=>{const day=dateInZone(new Date(),e.timezone);setDaily(null);setPending(false);setDailyError('');setEnrollmentId(e.id);setDate([day,...(e.end_date?[e.end_date]:[])].sort()[0]);setEffective(day);setStopDate(e.start_date>day?e.start_date:day);setHistoricalAck(false);setCompleteAck(false);setNoIntake(false);},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const data=await dietRequest<DietMetadata>();setMeta(data);const tz=Intl.DateTimeFormat().resolvedOptions().timeZone,day=dateInZone(new Date(),tz);setTimezone(tz);setStart(day);const active=data.enrollments.find(e=>!e.stopped&&e.start_date<=dateInZone(new Date(),e.timezone)&&(!e.end_date||e.end_date>=dateInZone(new Date(),e.timezone)))??data.enrollments[0];if(active)chooseEnrollment(active);}catch(e){setError(e instanceof Error?e.message:'Unable to load Diets.');}finally{setLoading(false);}},[chooseEnrollment]);
 useEffect(()=>{const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
 const refresh=useCallback(async()=>{if(!enrollmentId||!date||!meta)return;const e=meta.enrollments.find(e=>e.id===enrollmentId);if(!e||e.cancelled||date<e.start_date||date>dateInZone(new Date(),e.timezone)||(e.end_date&&date>e.end_date)){setPending(false);setDaily(null);return;}const g=++generation.current;setPending(true);setDaily(null);setDailyError('');try{const response=await dietRequest<DailyResponse>(new URLSearchParams({id:enrollmentId,date,start:shiftDate(date,-30),end:date}).toString());if(g===generation.current){setDaily(response);setCompleteAck(false);setNoIntake(false);}}catch(cause){if(g===generation.current)setDailyError(cause instanceof Error?cause.message:'Assessment recalculation failed.');}finally{if(g===generation.current)setPending(false);}},[enrollmentId,date,meta]);
 useEffect(()=>{const requests=generation;const t=setTimeout(()=>void refresh(),0);const onFocus=()=>void refresh();window.addEventListener('focus',onFocus);return()=>{clearTimeout(t);requests.current++;window.removeEventListener('focus',onFocus);};},[refresh]);
 function edit(d?:Diet){setEditing(d??null);setPlan(d?.draft??blankPlan());draftId.current=d?.id??crypto.randomUUID();followId.current=null;setEditor(true);setError('');setNotice('');}
 async function perform(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'Unable to save. Your input has been preserved.');}finally{setBusy(false);}}
 async function saveDefinition(archived=editing?.archived??false){validatePlan(plan);draftId.current??=crypto.randomUUID();const d=await dietRequest<Diet>('', 'definition',{id:draftId.current,revision:editing?.revision??0,draft:plan,archived});setEditing(d);setMeta(m=>m?{...m,diets:[d,...m.diets.filter(x=>x.id!==d.id)]}:m);setNotice(archived?'Diet archived. Existing enrollment history is retained.':'Definition saved as a reusable draft. Enrolled rules remain unchanged.');return d;}
 async function follow(){if(!meta)return;validatePlan(plan,true,meta.catalog);const d=await saveDefinition(false);followId.current??=crypto.randomUUID();const e=await dietRequest<Enrollment>('','enroll',{id:followId.current,diet_id:d.id,definition_revision:d.revision,start_date:start,end_date:end||null,timezone});setMeta(m=>m?{...m,enrollments:[e,...m.enrollments]}:m);chooseEnrollment(e);followId.current=null;setEditor(false);setNotice('Following this diet. Rules and exceptions are saved for the enrollment.');}
 async function updateVersion(){if(!enrollment||!meta)return;validatePlan(plan,true,meta.catalog);const e=await dietRequest<Enrollment>('','version',{enrollment_id:enrollment.id,revision:enrollment.revision,effective_from:effective,plan,historical_ack:historicalAck});setMeta(m=>m?{...m,enrollments:m.enrollments.map(x=>x.id===e.id?e:x)}:m);setNotice('A dated rule and schedule version was saved. Earlier dates keep their prior rules.');}
 async function confirmComplete(){if(!daily||!enrollment)return;await dietRequest('','confirm',{enrollment_id:enrollment.id,date,fingerprint:daily.assessment.fingerprint,no_intake:noIntake});await refresh();setNotice('All relevant food and drink logging is confirmed for this date.');}
 if(loading&&!meta)return <PageContainer narrow><p role="status">Loading Diets…</p></PageContainer>;
 if(!meta)return <PageContainer narrow><InlineNotice>{error}</InlineNotice><Button onClick={()=>void load()}>Retry</Button></PageContainer>;
 const current=daily?.assessment,visibleDiets=meta.diets.filter(d=>showArchived||!d.archived);
 return <PageContainer narrow><ButtonLink href="/health/nutrition" variant="tertiary">← Nutrition</ButtonLink><PageHeader title="Diets" description="Define food rules, choose a schedule, and review explained daily adherence."/><div className="mt-4" aria-live="polite">{error?<InlineNotice>{error}</InlineNotice>:null}{notice?<p role="status" className="text-sm text-green-800">{notice}</p>:null}</div>
 <Surface className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">Reusable definitions</h2><Button onClick={()=>edit()}>Create diet</Button></div><label className="my-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Show archived diets</label>{visibleDiets.length?<ul className="grid gap-2">{visibleDiets.map(d=><li key={d.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-3"><span className="min-w-0 break-words">{d.draft.name||'Untitled draft'} · {d.archived?'Archived':'Reusable draft'}</span><Button variant="secondary" onClick={()=>edit(d)}>View / edit {d.draft.name||'draft'}</Button></li>)}</ul>:<p className="text-sm">No definitions yet. Save an incomplete draft or define rules and start following.</p>}</Surface>
 {editor?<Surface className="mt-5"><h2 className="mb-4 text-lg font-semibold">{editing?'Edit definition':'Create definition'}</h2><form onSubmit={e=>{e.preventDefault();void perform(async()=>{await saveDefinition();});}}><PlanEditor plan={plan} setPlan={setPlan} catalog={meta.catalog}/><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy} type="submit">Save draft</Button>{editing?<Button type="button" variant="secondary" disabled={busy} onClick={()=>void perform(async()=>{await saveDefinition(!editing.archived);})}>{editing.archived?'Restore diet':'Archive diet'}</Button>:null}<Button type="button" variant="tertiary" onClick={()=>setEditor(false)}>Close editor</Button></div></form>
 {!editing?.archived?<details className="mt-5"><summary className="cursor-pointer py-2 font-semibold">Start following this diet</summary><div className="grid gap-3"><Field label="Enrollment start date"><input type="date" className={controlClass} value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Enrollment end date (optional)"><input type="date" className={controlClass} min={start} value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="Enrollment timezone"><input className={controlClass} value={timezone} onChange={e=>setTimezone(e.target.value)}/></Field><Button disabled={busy||!start||!timezone} onClick={()=>void perform(follow)}>Save and follow diet</Button></div></details>:null}</Surface>:null}
 <Surface className="mt-5 grid gap-3"><h2 className="text-lg font-semibold">Following and history</h2>{meta.enrollments.length?<><Field label="Enrollment"><select className={controlClass} value={enrollmentId} onChange={e=>{const next=meta.enrollments.find(x=>x.id===e.target.value);if(next)chooseEnrollment(next);}}>{meta.enrollments.map(e=><option key={e.id} value={e.id}>{meta.diets.find(d=>d.id===e.diet_id)?.draft.name||'Diet'} · {e.start_date} · {e.stopped?'Stopped':'Following'}</option>)}</select></Field>{enrollment?<><p className="text-sm">{enrollment.start_date}–{enrollment.end_date??'open ended'} · {enrollment.timezone}</p><Field label="Assessment date"><input className={controlClass} type="date" min={enrollment.start_date} max={[dateInZone(new Date(),enrollment.timezone),...(enrollment.end_date?[enrollment.end_date]:[])].sort()[0]} value={date} onChange={e=>{setDaily(null);setDate(e.target.value);setCompleteAck(false);setNoIntake(false);}}/></Field><Button variant="secondary" disabled={pending} onClick={()=>void refresh()}>Refresh assessments</Button>{enrollment.cancelled?<p>This scheduled enrollment was cancelled. It has no assessment dates.</p>:enrollment.start_date>dateInZone(new Date(),enrollment.timezone)?<p>This enrollment starts on {enrollment.start_date}. Future dates have no adherence assessment.</p>:null}
 {!enrollment.cancelled?<details><summary className="cursor-pointer py-2">Manage effective rules, exceptions and stop date</summary><div className="grid gap-3"><Button variant="secondary" onClick={()=>edit(meta.diets.find(d=>d.id===enrollment.diet_id))}>Edit this diet’s reusable definition</Button><p className="text-sm">Saving a definition does not change an enrollment. Apply the shown rules and schedule from an effective date below; they apply until the next saved version. Earlier dates retain their rules.</p><Field label="Rules effective from"><input className={controlClass} type="date" min={enrollment.start_date} value={effective} onChange={e=>setEffective(e.target.value)}/></Field><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={historicalAck} onChange={e=>setHistoricalAck(e.target.checked)}/>I understand a historical correction changes assessments from this effective date until the next version.</label><Button disabled={busy||editing?.id!==enrollment.diet_id||!editor} onClick={()=>void perform(updateVersion)}>Apply shown rules and schedule</Button><Field label="Last following date (inclusive)"><input className={controlClass} type="date" min={enrollment.start_date} max={[enrollment.start_date,dateInZone(new Date(),enrollment.timezone)].sort().at(-1)} value={stopDate} onChange={e=>setStopDate(e.target.value)}/></Field><Button disabled={busy||enrollment.stopped} variant="secondary" onClick={()=>void perform(async()=>{const e=await dietRequest<Enrollment>('','stop',{enrollment_id:enrollment.id,revision:enrollment.revision,end_date:stopDate,historical_ack:historicalAck});setMeta(m=>m?{...m,enrollments:m.enrollments.map(x=>x.id===e.id?e:x)}:m);chooseEnrollment(e);setNotice('Following stopped. Earlier rules, source logs and history remain available.');})}>{enrollment.start_date>dateInZone(new Date(),enrollment.timezone)?'Cancel scheduled enrollment':'Stop following diet'}</Button></div></details>:null}</>:null}</>:<p className="text-sm">Start following a definition to see daily adherence.</p>}</Surface>
 {pending?<Surface className="mt-5"><p role="status">Recalculating current intake and rules…</p></Surface>:dailyError?<Surface className="mt-5"><InlineNotice>{dailyError}</InlineNotice><Button onClick={()=>void refresh()}>Retry recalculation</Button></Surface>:daily&&current?<><Surface className="mt-5 grid gap-3"><h2 className="text-lg font-semibold">{labels[current.calculated_status]} · {current.local_date}</h2><p className="text-sm">Logging completeness: {current.logging_complete?'Confirmed complete':current.confirmation_invalidated?'Confirmation invalidated; reconfirm after changes':'Not confirmed complete'}</p><p className="text-sm">Applicable diet: {daily.bundle.version.plan.name} · Rules effective {daily.bundle.version.effective_from} · version {daily.bundle.version.revision}</p><details><summary className="cursor-pointer py-2">Applicable rules and instructions</summary><p className="text-sm">{daily.bundle.version.plan.instructions}</p><p className="text-sm capitalize">{daily.bundle.version.plan.mode} allowed list</p><ul className="mt-2 list-disc pl-5 text-sm">{daily.bundle.version.plan.rules.map((r,i)=><li key={i}>{r.action==='allow'?'Allow':'Exclude'} {r.kind==='ingredient'?r.ref.replaceAll('_',' '):(r.kind==='food'?meta.catalog.foods:meta.catalog.categories).find(x=>x.id===r.ref)?.name??'Saved reference'}</li>)}</ul></details>
 {current.exception?<p className="text-sm">Planned unrestricted exception: actual intake is retained. This is not an adherent regular day and does not imply complete logging.</p>:null}{current.calculated_status==='incomplete'?<p>Confirm whether all food and drinks have been logged.</p>:null}{current.no_intake_confirmed?<p>Deliberately confirmed no-intake day.</p>:null}
 {current.reasons.length?<ul className="grid gap-2 text-sm">{current.reasons.map((r,i)=><li key={i} className="rounded-lg border p-3"><span className="font-semibold capitalize">{r.kind}: </span>{r.message}{r.provenance?<span className="mt-1 block text-xs">Evidence: {r.provenance}</span>:null}<span className="mt-1 block text-xs">Source: {r.source.domain} log {r.source.id.slice(0,8)}{r.source.component_id?' · meal component':''}</span></li>)}</ul>:!current.items.length?<p className="text-sm">No intake logged. Zero entries alone do not establish adherence.</p>:<p className="text-sm">All logged items are resolved and comply with the applicable rules.</p>}
 {!current.logging_complete?<fieldset className="grid gap-3 rounded-lg border p-3"><legend className="px-1 font-semibold">Confirm intake logging</legend><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={completeAck} onChange={e=>setCompleteAck(e.target.checked)}/>All food and beverage intake for {date} has been logged.</label>{!current.items.length?<label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={noIntake} onChange={e=>setNoIntake(e.target.checked)}/>This was deliberately a no-intake day.</label>:null}<Button disabled={busy||!completeAck||(!current.items.length&&!noIntake)} onClick={()=>void perform(confirmComplete)}>Confirm complete logging</Button></fieldset>:null}
 <ButtonLink href="/health/nutrition" variant="secondary">Log or edit intake in Nutrition</ButtonLink><ButtonLink href="/today" variant="tertiary">Manual / voice logging and saved meals</ButtonLink>
 </Surface>
 {current.items.length?<Surface className="mt-5"><h2 className="text-lg font-semibold">Inspect and review intake</h2><p className="mt-2 text-sm">Corrections update your records and preserve catalog information. Reusable classification corrections apply to your logs of that food, including past dates. Diet-rule changes are made separately above.</p>{current.items.map((item,i)=><IntakeReview key={`${date}:${i}:${item.food_id}`} item={item} catalog={meta.catalog} busy={busy} perform={perform} refresh={refresh}/>)}</Surface>:null}
 <Surface className="mt-5"><h2 className="text-lg font-semibold">Daily history · up to 31 elapsed dates</h2><p className="mt-2 text-sm">{Object.entries(labels).map(([k,label])=>`${label}: ${daily.history.filter(a=>a.calculated_status===k).length}`).join(' · ')}</p><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="py-2 text-left">Dates within enrollment only. Exception days are separate from regular adherence.</caption><thead><tr><th className="p-2">Date</th><th className="p-2">Assessment</th><th className="p-2">Logging</th><th className="p-2">Rule version</th></tr></thead><tbody>{daily.history.map(a=><tr className="border-t" key={a.local_date}><th scope="row" className="p-2"><button className="underline focus-visible:ring-2" onClick={()=>setDate(a.local_date)}>{a.local_date}</button></th><td className="p-2">{labels[a.calculated_status]}</td><td className="p-2">{a.logging_complete?'Complete':'Unconfirmed'}</td><td className="p-2">{a.rule_version_id.slice(0,8)}</td></tr>)}</tbody></table></div></Surface></>:null}
 </PageContainer>;
}
export function IntakeReview({item,catalog,busy,perform,refresh}:{item:Leaf;catalog:Catalog;busy:boolean;perform:(f:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>}){
 const [food,setFood]=useState(item.food_id??''),[key,setKey]=useState<typeof ingredientKeys[number]>('dairy'),[state,setState]=useState('unknown'),[provenance,setProvenance]=useState(''),[ack,setAck]=useState(false),[reusable,setReusable]=useState(false);
 const s=item.source;const subject=s.component_id?'component_id':s.event_food_id?'event_food_id':s.user_food_id?'user_food_id':s.domain==='health'?'health_event_id':s.item_id?'nutrition_entry_item_id':null;
 const id=s.component_id??s.event_food_id??s.user_food_id??(s.domain==='health'?s.id:s.item_id);
 return <details className="mt-3 rounded-lg border p-3"><summary className="cursor-pointer py-1 font-medium">{item.label} · {item.trusted?'Resolved identity':'Needs identity review'}</summary><div className="mt-3 grid gap-3"><p className="text-xs">This is a {s.component_id?'meal component':'logged food or beverage'}. Original logs, nutrition values and shared catalog records are retained. Ingredient evidence is not an allergy-safety certification.</p><Field label={`Review ${item.label}: provenance or explanation`}><input className={controlClass} maxLength={500} value={provenance} onChange={e=>setProvenance(e.target.value)}/></Field><label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I understand this correction recalculates affected past dates and invalidates logging confirmation.</label>
 {subject&&subject!=='nutrition_entry_item_id'?<><Field label={`Review ${item.label}: canonical identity`}><select className={controlClass} value={food} onChange={e=>setFood(e.target.value)}><option value="">Choose a canonical food</option>{catalog.foods.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Button disabled={busy||!ack||!food||!provenance.trim()} variant="secondary" onClick={()=>void perform(async()=>{await dietRequest('','identity',{subject,id,food_id:food,provenance,historical_ack:ack});await refresh();})}>Save identity correction</Button></>:null}
 <Field label={`Review ${item.label}: ingredient`}><select className={controlClass} value={key} onChange={e=>setKey(e.target.value as typeof key)}>{ingredientKeys.map(k=><option key={k} value={k}>{k.replaceAll('_',' ')}</option>)}</select></Field><Field label={`Review ${item.label}: evidence state`}><select className={controlClass} value={state} onChange={e=>setState(e.target.value)}><option value="unknown">Unknown</option><option value="present">Known present</option><option value="absent">Known absent</option></select></Field>{item.food_id?<label className="flex items-start gap-2 text-sm"><input className="mt-1" type="checkbox" checked={reusable} onChange={e=>setReusable(e.target.checked)}/>Reuse this ingredient classification for all my logs of this canonical food, including historical dates.</label>:null}
 <Button disabled={busy||!ack||!provenance.trim()||(!subject&&!item.food_id)} onClick={()=>void perform(async()=>{await dietRequest('','classification',{subject:reusable&&item.food_id?'food_id':subject??'food_id',id:reusable&&item.food_id?item.food_id:id??item.food_id,key,state,provenance,historical_ack:ack});await refresh();})}>Save private classification</Button></div></details>;
}

