import { exposureDefinitions } from "./exposures.ts";
import { createEpisodeWindow, selectBaselineDays } from "./windows.ts";
import { TRIGGER_ANALYSIS_VERSION, type ExposureDay, type TriggerAnalysisResult, type TriggerPattern, type TriggerWindowHours } from "./types.ts";
type Episode={id:string;started_at:string;user_condition_id:string;episode_type:string};
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null;
const round=(x:number|null,d=1)=>x==null?null:Number(x.toFixed(d));
export function evidenceStrength(episodes:number,comparisons:number,completeness:number,consistency:number){if(episodes>=10&&comparisons>=15&&completeness>=75&&consistency>=.7)return"consistent"as const;if(episodes>=5&&comparisons>=10&&completeness>=60&&consistency>=.6)return"emerging"as const;return"limited"as const}
export function analyzeTriggerPatterns({episodes,days,userConditionId,conditionLabel,episodeLabel,windowHours}:{episodes:Episode[];days:ExposureDay[];userConditionId:string;conditionLabel:string;episodeLabel:string;windowHours:TriggerWindowHours}):TriggerAnalysisResult{
 const relevant=episodes.filter(x=>x.user_condition_id===userConditionId).sort((a,b)=>a.started_at.localeCompare(b.started_at)),windows=relevant.map(e=>createEpisodeWindow(e.id,e.started_at,windowHours)),patterns:TriggerPattern[]=[],otherVariables:string[]=[];
 for(const def of exposureDefinitions){const episodeValues:number[]=[],baselineValues:number[]=[],lowerByEpisode:boolean[]=[];let comparisonCount=0;
  for(const i of relevant.keys()){const window=windows[i],windowDays=days.filter(d=>d.at>=window.startAt&&d.at<window.endAt),baseline=selectBaselineDays(days,window,windows),episodeValue=def.value(windowDays),baselineValue=def.value(baseline.days);if(baselineValue!=null){baselineValues.push(baselineValue);comparisonCount+=baseline.days.length}if(episodeValue!=null&&baselineValue!=null){episodeValues.push(episodeValue);lowerByEpisode.push(episodeValue<baselineValue)}}
  const usable=episodeValues.length,episodeValue=mean(episodeValues),baselineValue=mean(baselineValues),difference=episodeValue!=null&&baselineValue!=null?episodeValue-baselineValue:null,completeness=relevant.length?100*usable/relevant.length:0,lower=(difference??0)<0,consistency=lowerByEpisode.length?lowerByEpisode.filter(x=>x===lower).length/lowerByEpisode.length:0,sufficient=usable>=def.minimumEpisodeCount&&comparisonCount>=def.minimumComparisonCount&&Math.abs(difference??0)>=def.minimumDifference&&completeness>=50&&consistency>=.6;
  if(!sufficient){otherVariables.push(def.label);continue}
  const strength=evidenceStrength(usable,comparisonCount,completeness,consistency),matching=lowerByEpisode.filter(x=>x===lower).length,binary=def.dataType==="binary",direction=binary?(lower?"less_common"as const:"more_common"as const):(lower?"lower"as const:"higher"as const),limitations=[usable<5?`Only ${usable} episodes had usable ${def.label.toLowerCase()} data.`:null,completeness<80?`${Math.round(100-completeness)}% of episodes lacked usable data for this exposure.`:null,"Other variables may explain this difference."].filter((x):x is string=>Boolean(x)),summary=binary?`${def.label} was ${direction.replace("_"," ")} before ${matching} of ${usable} ${episodeLabel.toLowerCase()}${usable===1?"":"s"} than in personal comparison periods.`:`${def.label} was ${direction} than your personal baseline before ${matching} of ${usable} ${episodeLabel.toLowerCase()}${usable===1?"":"s"}.`;
  patterns.push({id:`${userConditionId}:${def.key}:${windowHours}`,userConditionId,conditionLabel,episodeLabel,exposureKey:def.key,exposureLabel:def.label,exposureCategory:def.category,windowHours,episodesAnalyzed:usable,episodesMatchingPattern:matching,comparisonWindows:comparisonCount,episodeValue:round(episodeValue),baselineValue:round(baselineValue),episodePrevalence:binary?round(episodeValue):null,comparisonPrevalence:binary?round(baselineValue):null,absoluteDifference:round(difference),percentDifference:!binary&&baselineValue?round(100*(difference!/baselineValue)):null,direction,evidenceStrength:strength,completenessPercentage:round(completeness)!,limitations,sufficientData:true,rankScore:usable*10+consistency*20+completeness/10+Math.min(20,Math.abs(difference??0)/def.minimumDifference*5),unit:def.unit,summary});
 }
 patterns.sort((a,b)=>b.rankScore-a.rankScore||a.exposureKey.localeCompare(b.exposureKey));
 return{generatedAt:new Date().toISOString(),analysisVersion:TRIGGER_ANALYSIS_VERSION,userConditionId,conditionLabel,episodeLabel,windowHours,episodeCount:relevant.length,patterns:patterns.slice(0,5),otherVariables,methodology:`Each episode is one observation. The ${windowHours}-hour period ending exactly at episode onset is compared with the previous 30 days, excluding all episode windows; a 90-day baseline is used when fewer than seven comparison days remain. No population norms are used.`,failedSources:[]};
}
