export const TRIGGER_ANALYSIS_VERSION="trigger-discovery-v1";
export const triggerWindows=[24,48,72,168]as const;export type TriggerWindowHours=typeof triggerWindows[number];
export type ExposureCategory="sleep"|"nutrition"|"hydration"|"workout"|"supplement"|"habit"|"protocol"|"mood"|"energy"|"symptom";
export type ExposureDay={date:string;at:string;sleepQuality:number|null;energy:number|null;mood:number|null;alcohol:boolean|null;calories:number|null;protein:number|null;caffeine:number|null;alcoholGrams:number|null;workoutCount:number;workoutMinutes:number;workoutVolume:number;habitCompleted:number;habitScheduled:number;protocolCompleted:number;protocolScheduled:number;symptomCount:number};
export type EpisodeWindow={episodeId:string;onsetAt:string;windowHours:TriggerWindowHours;startAt:string;endAt:string};
export type EpisodeAnalysisContext=EpisodeWindow&{userConditionId:string;episodeType:string;baselineStartAt:string;baselineEndAt:string;baselineDays:30|90;dataCompleteness:Record<string,number>};
export type ExposureDefinition={key:string;label:string;category:ExposureCategory;dataType:"continuous"|"binary"|"count"|"adherence";unit:string|null;supportedWindows:TriggerWindowHours[];minimumEpisodeCount:number;minimumComparisonCount:number;minimumDifference:number;value:(days:ExposureDay[])=>number|null;absenceReliable:boolean};
export type TriggerPattern={id:string;userConditionId:string;conditionLabel:string;episodeLabel:string;exposureKey:string;exposureLabel:string;exposureCategory:ExposureCategory;windowHours:TriggerWindowHours;episodesAnalyzed:number;episodesMatchingPattern:number|null;comparisonWindows:number;episodeValue:number|null;baselineValue:number|null;episodePrevalence:number|null;comparisonPrevalence:number|null;absoluteDifference:number|null;percentDifference:number|null;direction:"higher"|"lower"|"more_common"|"less_common"|"similar";evidenceStrength:"limited"|"emerging"|"consistent";completenessPercentage:number;limitations:string[];sufficientData:boolean;rankScore:number;unit:string|null;summary:string};
export type TriggerAnalysisResult={generatedAt:string;analysisVersion:string;userConditionId:string;conditionLabel:string;episodeLabel:string;windowHours:TriggerWindowHours;episodeCount:number;patterns:TriggerPattern[];otherVariables:string[];methodology:string;failedSources:string[]};
