import type{SupabaseClient}from"@supabase/supabase-js";import type{Symptom,SymptomCategory,SymptomEvent,SymptomEventInput,UserSymptom}from"./types";
const eventSelect="*,symptom:symptoms(*,category:symptom_categories(slug,name)),condition_links:symptom_event_conditions(user_condition_id,user_condition:user_conditions(id,custom_condition_name,condition:conditions(name)))";
async function uid(c:SupabaseClient){const{data,error}=await c.auth.getUser();if(error||!data.user)throw new Error("Please log in to manage symptoms.");return data.user.id}
export function symptomName(x:{symptom?:Symptom|null;custom_symptom_name?:string|null}){return x.symptom?.name??x.custom_symptom_name??"Symptom"}
export function filterSymptoms(rows:Symptom[],category:string,search:string){const q=search.trim().toLowerCase();return rows.filter(s=>(!category||s.category_id===category)&&(!q||[s.name,s.short_name,s.category?.name,...s.common_aliases].filter(Boolean).some(v=>v!.toLowerCase().includes(q))))}
export function validateSymptomEvent(x:SymptomEventInput){const custom=x.customName?.trim()||null;if((!x.symptomId&&!custom)||(x.symptomId&&custom))return"Choose one symptom.";if(custom&&(custom.length<2||custom.length>120))return"Custom symptom names must be between 2 and 120 characters.";if(!x.startedAt||Number.isNaN(new Date(x.startedAt).valueOf()))return"Enter a valid start time.";if(x.endedAt&&new Date(x.endedAt)<new Date(x.startedAt))return"End time cannot be before start time.";if(x.severity!=null&&(x.severity<1||x.severity>10||!Number.isInteger(x.severity)))return"Severity must be from 1 to 10.";if(x.occurrenceCount!=null&&(!Number.isInteger(x.occurrenceCount)||x.occurrenceCount<1))return"Count must be a positive whole number.";if((x.bodyLocation?.length??0)>120)return"Body location must be 120 characters or fewer.";if((x.notes?.length??0)>2000)return"Notes must be 2,000 characters or fewer.";return null}
export function summarizeEvents(rows:SymptomEvent[]){const values=rows.map(r=>r.severity).filter((v):v is number=>v!=null);return{count:rows.length,averageSeverity:values.length?Number((values.reduce((a,b)=>a+b,0)/values.length).toFixed(1)):null,ongoing:rows.filter(r=>r.resolved===false&&r.ended_at===null).length}}
export async function getSymptomCatalog(c:SupabaseClient){const[a,b]=await Promise.all([c.from("symptom_categories").select("id,slug,name,description,display_order").order("display_order"),c.from("symptoms").select("*,category:symptom_categories(slug,name)").order("is_featured",{ascending:false}).order("name")]);if(a.error||b.error)throw new Error("We couldn’t load the symptom catalog.");return{categories:(a.data??[])as SymptomCategory[],symptoms:(b.data??[])as unknown as Symptom[]}}
export async function getMySymptoms(c:SupabaseClient){const user=await uid(c);const{data,error}=await c.from("user_symptoms").select("*,symptom:symptoms(*,category:symptom_categories(slug,name))").eq("user_id",user).eq("is_active",true).order("is_favorite",{ascending:false}).order("last_logged_at",{ascending:false});if(error)throw new Error("We couldn’t load My Symptoms.");return(data??[])as unknown as UserSymptom[]}
export async function getRecentSymptomEvents(c:SupabaseClient,limit=50){const user=await uid(c);const{data,error}=await c.from("user_symptom_events").select(eventSelect).eq("user_id",user).is("deleted_at",null).order("started_at",{ascending:false}).limit(limit);if(error)throw new Error("We couldn’t load symptom history.");return(data??[])as unknown as SymptomEvent[]}
export async function getRecommendedSymptoms(c:SupabaseClient){const user=await uid(c);const{data:conditions,error}=await c.from("user_conditions").select("condition_id,is_primary").eq("user_id",user).is("archived_at",null).not("condition_id","is",null);if(error)throw new Error("We couldn’t load recommendations.");const ids=(conditions??[]).map(x=>x.condition_id as string);if(!ids.length)return[];const primary=new Set((conditions??[]).filter(x=>x.is_primary).map(x=>x.condition_id));const{data:mappings,error:mError}=await c.from("condition_symptoms").select("condition_id,relevance_score,is_common,is_primary,symptom:symptoms(*,category:symptom_categories(slug,name))").in("condition_id",ids);if(mError)throw new Error("We couldn’t load recommendations.");const best=new Map<string,{symptom:Symptom;score:number}>();for(const row of mappings??[]){const s=row.symptom as unknown as Symptom;const score=Number(row.relevance_score)+(primary.has(row.condition_id)?1000:0)+(row.is_primary?200:0)+(row.is_common?100:0);if(!best.has(s.id)||best.get(s.id)!.score<score)best.set(s.id,{symptom:s,score})}return[...best.values()].sort((a,b)=>b.score-a.score).map(x=>x.symptom)}
export async function addMySymptom(c:SupabaseClient,symptomId:string|null,customName:string|null,source:UserSymptom["source"]="manual"){const user=await uid(c),name=customName?.trim()||null;let query=c.from("user_symptoms").select("id").eq("user_id",user);query=symptomId?query.eq("symptom_id",symptomId):query.eq("custom_symptom_name_normalized",name!.toLowerCase());const{data:existing}=await query.maybeSingle();const mutation=existing?c.from("user_symptoms").update({is_active:true,source}).eq("id",existing.id).eq("user_id",user):c.from("user_symptoms").insert({user_id:user,symptom_id:symptomId,custom_symptom_name:name,source,is_active:true});const{data,error}=await mutation.select("*,symptom:symptoms(*,category:symptom_categories(slug,name))").single();if(error)throw new Error(error.code==="23505"?"This symptom is already in My Symptoms.":"We couldn’t add this symptom.");return data as unknown as UserSymptom}
export async function updateMySymptom(c:SupabaseClient,id:string,changes:{is_favorite?:boolean;is_active?:boolean}){const user=await uid(c);const{error}=await c.from("user_symptoms").update(changes).eq("id",id).eq("user_id",user);if(error)throw new Error("We couldn’t update My Symptoms.")}
export async function createSymptomEvent(c:SupabaseClient,input:SymptomEventInput){const errorText=validateSymptomEvent(input);if(errorText)throw new Error(errorText);const user=await uid(c);const{data,error}=await c.from("user_symptom_events").insert({user_id:user,symptom_id:input.symptomId||null,custom_symptom_name:input.customName?.trim()||null,started_at:input.startedAt,ended_at:input.endedAt||null,severity:input.severity??null,occurrence_count:input.occurrenceCount??null,resolved:input.resolved??null,body_location:input.bodyLocation?.trim()||null,notes:input.notes?.trim()||null,source:input.source??"my_health"}).select(eventSelect).single();if(error)throw new Error("We couldn’t log this symptom.");if(input.conditionIds?.length){const{error:linkError}=await c.from("symptom_event_conditions").insert(input.conditionIds.map(id=>({symptom_event_id:data.id,user_condition_id:id})));if(linkError){await c.from("user_symptom_events").delete().eq("id",data.id).eq("user_id",user);throw new Error("We couldn’t save the condition associations.")}}try{const tracked=await addMySymptom(c,input.symptomId||null,input.customName||null,input.customName?"custom":"history");await c.from("user_symptoms").update({last_logged_at:input.startedAt}).eq("id",tracked.id).eq("user_id",user)}catch{/* Event remains authoritative if optional My Symptoms update fails. */}return data as unknown as SymptomEvent}
export async function resolveSymptomEvent(c:SupabaseClient,id:string){const user=await uid(c);const now=new Date().toISOString();const{error}=await c.from("user_symptom_events").update({resolved:true,ended_at:now}).eq("id",id).eq("user_id",user);if(error)throw new Error("We couldn’t resolve this symptom event.")}
export async function deleteSymptomEvent(c:SupabaseClient,id:string){const user=await uid(c);const{error}=await c.from("user_symptom_events").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("user_id",user);if(error)throw new Error("We couldn’t remove this symptom event.")}
