"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, ButtonLink, InlineNotice, LoadingSkeleton, PageContainer, PageHeader, Surface } from "@/components/ui/design-system";
import { archiveCondition, conditionDisplayName, getUserCondition, setPrimaryCondition, updateUserCondition } from "@/lib/conditions/conditions";
import type { UserCondition } from "@/lib/conditions/types";
import { createClient } from "@/lib/supabase/browser";
import { ConditionDetailsFields, type ConditionFormValues } from "./ConditionDetailsFields";
import { ConditionStatusBadge } from "./ConditionStatusBadge";

function valuesFor(item: UserCondition): ConditionFormValues { return { status: item.status === "archived" ? "active" : item.status, diagnosedOn: item.diagnosed_on ?? "", diagnosedYear: item.diagnosed_year?.toString() ?? "", isPrimary: item.is_primary, notes: item.notes ?? "" }; }
export function ConditionManager({ id }: { id: string }) {
  const router = useRouter(); const [item, setItem] = useState<UserCondition | null>(null); const [values, setValues] = useState<ConditionFormValues | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [confirmArchive, setConfirmArchive] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const row = await getUserCondition(createClient(), id); setItem(row); setValues(valuesFor(row)); } catch { setError("We couldn’t find this condition in your health profile."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  if (loading) return <PageContainer narrow><LoadingSkeleton className="h-72"/></PageContainer>;
  if (!item || !values) return <PageContainer narrow><InlineNotice>{error}</InlineNotice><ButtonLink href="/health" variant="secondary" className="mt-4">Back to My Health</ButtonLink></PageContainer>;
  const name = conditionDisplayName(item);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await updateUserCondition(createClient(), item!.id, { conditionId: item!.condition_id, customName: item!.custom_condition_name, status: values!.status, diagnosedOn: values!.diagnosedOn || null, diagnosedYear: values!.diagnosedYear ? Number(values!.diagnosedYear) : null, isPrimary: values!.isPrimary, notes: values!.notes }); const refreshed = await getUserCondition(createClient(), item!.id); setItem(refreshed); setValues(valuesFor(refreshed)); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t update this condition."); } finally { setSaving(false); } }
  async function makePrimary() { setSaving(true); setError(""); try { await setPrimaryCondition(createClient(), item!.id); setItem({ ...item!, is_primary: true }); setValues({ ...values!, isPrimary: true }); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t update your primary condition."); } finally { setSaving(false); } }
  async function archive() { setSaving(true); setError(""); try { await archiveCondition(createClient(), item!.id); router.push("/health"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t archive this condition."); setConfirmArchive(false); setSaving(false); } }
  return <PageContainer narrow><ButtonLink href="/health" variant="tertiary" className="mb-4 -ml-4">← My Health</ButtonLink><PageHeader eyebrow={item.condition?.category?.name ?? "Custom condition"} title={name} description="Manage the details you’ve chosen to track." actions={<ConditionStatusBadge status={item.status}/>}/>
    {error ? <div className="mt-4"><InlineNotice>{error}</InlineNotice></div> : null}<Surface className="mt-6"><h2 className="text-lg font-semibold text-slate-900">Condition details</h2><form onSubmit={save} className="mt-4 grid gap-5"><ConditionDetailsFields values={values} onChange={setValues}/><div className="flex flex-wrap gap-2"><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save changes"}</Button>{!item.is_primary ? <Button type="button" variant="secondary" disabled={saving} onClick={() => void makePrimary()}>Mark as primary</Button> : null}</div></form></Surface>
    <div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Symptoms", "Coming next"], ["Protocols", "No linked protocols yet"], ["Experiments", "No linked experiments yet"], ["History", "Coming soon"]].map(([title, detail]) => <Surface compact key={title}><h2 className="font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{detail}</p></Surface>)}</div>
    <Surface className="mt-5 border-slate-300"><h2 className="font-semibold text-slate-900">Archive condition</h2><p className="mt-1 text-sm leading-6 text-slate-600">Archiving removes this condition from your active view while preserving its record.</p>{confirmArchive ? <div role="alertdialog" aria-labelledby="archive-title" aria-describedby="archive-description" className="mt-4 rounded-xl border border-slate-300 bg-slate-50 p-4"><h3 id="archive-title" className="font-semibold text-slate-900">Archive {name}?</h3><p id="archive-description" className="mt-1 text-sm text-slate-600">You can restore it later from My Health.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="destructive" disabled={saving} onClick={() => void archive()}>{saving ? "Archiving…" : `Archive ${name}`}</Button><Button variant="secondary" disabled={saving} onClick={() => setConfirmArchive(false)}>Cancel</Button></div></div> : <Button variant="secondary" className="mt-4" onClick={() => setConfirmArchive(true)}>Archive condition</Button>}</Surface>
  </PageContainer>;
}
