"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button, ButtonLink, InlineNotice, LoadingSkeleton, PageContainer, PageHeader, Surface } from "@/components/ui/design-system";
import { archiveCondition, conditionDisplayName, getUserCondition, setPrimaryCondition, updateUserCondition } from "@/lib/conditions/conditions";
import type { UserCondition } from "@/lib/conditions/types";
import { createClient } from "@/lib/supabase/browser";
import { ConditionDetailsFields, type ConditionFormValues } from "./ConditionDetailsFields";
import { ConditionStatusBadge } from "./ConditionStatusBadge";
import { EpisodeCard } from "@/components/episodes/EpisodeCard";
import { getEpisodes, summarizeEpisodes, episodeLabel } from "@/lib/episodes/episodes";
import type { ConditionEpisode } from "@/lib/episodes/types";

function valuesFor(item: UserCondition): ConditionFormValues { return { status: item.status === "archived" ? "active" : item.status, diagnosedOn: item.diagnosed_on ?? "", diagnosedYear: item.diagnosed_year?.toString() ?? "", isPrimary: item.is_primary, notes: item.notes ?? "" }; }
export function ConditionManager({ id }: { id: string }) {
  const router = useRouter(); const [item, setItem] = useState<UserCondition | null>(null); const [episodes, setEpisodes] = useState<ConditionEpisode[]>([]); const [values, setValues] = useState<ConditionFormValues | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [confirmArchive, setConfirmArchive] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const client=createClient(),[row,episodeRows] = await Promise.all([getUserCondition(client, id),getEpisodes(client,id)]); setItem(row); setValues(valuesFor(row)); setEpisodes(episodeRows); } catch { setError("We couldn’t find this condition in your health profile."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  if (loading) return <PageContainer narrow><LoadingSkeleton className="h-72"/></PageContainer>;
  if (!item || !values) return <PageContainer narrow><InlineNotice>{error}</InlineNotice><ButtonLink href="/health" variant="secondary" className="mt-4">Back to My Health</ButtonLink></PageContainer>;
  const name = conditionDisplayName(item);
  const label = episodeLabel(item.condition); const summary=summarizeEpisodes(episodes);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { await updateUserCondition(createClient(), item!.id, { conditionId: item!.condition_id, customName: item!.custom_condition_name, status: values!.status, diagnosedOn: values!.diagnosedOn || null, diagnosedYear: values!.diagnosedYear ? Number(values!.diagnosedYear) : null, isPrimary: values!.isPrimary, notes: values!.notes }); const refreshed = await getUserCondition(createClient(), item!.id); setItem(refreshed); setValues(valuesFor(refreshed)); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t update this condition."); } finally { setSaving(false); } }
  async function makePrimary() { setSaving(true); setError(""); try { await setPrimaryCondition(createClient(), item!.id); setItem({ ...item!, is_primary: true }); setValues({ ...values!, isPrimary: true }); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t update your primary condition."); } finally { setSaving(false); } }
  async function archive() { setSaving(true); setError(""); try { await archiveCondition(createClient(), item!.id); router.push("/health"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "We couldn’t archive this condition."); setConfirmArchive(false); setSaving(false); } }
  return <PageContainer narrow><ButtonLink href="/health" variant="tertiary" className="mb-4 -ml-4">← My Health</ButtonLink><PageHeader eyebrow={item.condition?.category?.name ?? "Custom condition"} title={name} description="Manage the details you’ve chosen to track." actions={<div className="flex flex-wrap gap-2"><ConditionStatusBadge status={item.status}/><ButtonLink href={`/health/episodes/new?condition=${item.id}`}>Log {label}</ButtonLink></div>}/>
    {error ? <div className="mt-4"><InlineNotice>{error}</InlineNotice></div> : null}<Surface className="mt-6"><h2 className="text-lg font-semibold text-slate-900">Condition details</h2><form onSubmit={save} className="mt-4 grid gap-5"><ConditionDetailsFields values={values} onChange={setValues}/><div className="flex flex-wrap gap-2"><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Save changes"}</Button>{!item.is_primary ? <Button type="button" variant="secondary" disabled={saving} onClick={() => void makePrimary()}>Mark as primary</Button> : null}</div></form></Surface>
    {episodes.length?<><section className="mt-6" aria-labelledby="episode-metrics"><h2 id="episode-metrics" className="text-lg font-semibold">{label} summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><Surface compact><p className="text-sm text-slate-500">Last 30 days</p><p className="text-2xl font-semibold">{summary.count30}</p></Surface><Surface compact><p className="text-sm text-slate-500">Last 90 days</p><p className="text-2xl font-semibold">{summary.count90}</p></Surface><Surface compact><p className="text-sm text-slate-500">Average resolved duration</p><p className="text-2xl font-semibold">{summary.averageResolvedDurationHours==null?"—":`${(summary.averageResolvedDurationHours/24).toFixed(1)} d`}</p></Surface></div>{summary.commonSymptoms.length?<p className="mt-3 text-sm text-slate-600"><span className="font-semibold">Most linked symptoms:</span> {summary.commonSymptoms.map(x=>x.name).join(", ")}</p>:null}</section><section className="mt-6" aria-labelledby="recent-episodes"><h2 id="recent-episodes" className="text-lg font-semibold">Recent {label}s</h2><div className="mt-3 grid gap-3">{episodes.slice(0,6).map(x=><EpisodeCard key={x.id} episode={x}/>)}</div></section></>:<Surface className="mt-5"><h2 className="font-semibold">No episodes logged yet</h2><p className="mt-1 text-sm text-slate-600">Track flares, outbreaks, attacks, or other meaningful health episodes related to this condition.</p><ButtonLink href={`/health/episodes/new?condition=${item.id}`} className="mt-4">Log {label}</ButtonLink></Surface>}
    <Surface className="mt-5"><h2 className="font-semibold">Patterns before {label.toLowerCase()}s</h2><p className="mt-1 text-sm text-slate-600">Compare the periods before episodes with your own recent baseline.</p><ButtonLink href={`/health/conditions/${item.id}/patterns`} className="mt-3">View Patterns</ButtonLink></Surface><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["Symptoms", "Managed in structured symptom history"], ["Protocols", "No linked protocols yet"], ["Experiments", "Episode outcomes are data-source compatible"], ["History", `${episodes.length} episode${episodes.length===1?"":"s"} recorded`]].map(([title, detail]) => <Surface compact key={title}><h2 className="font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">{detail}</p></Surface>)}</div>
    <Surface className="mt-5 border-slate-300"><h2 className="font-semibold text-slate-900">Archive condition</h2><p className="mt-1 text-sm leading-6 text-slate-600">Archiving removes this condition from your active view while preserving its record.</p>{confirmArchive ? <div role="alertdialog" aria-labelledby="archive-title" aria-describedby="archive-description" className="mt-4 rounded-xl border border-slate-300 bg-slate-50 p-4"><h3 id="archive-title" className="font-semibold text-slate-900">Archive {name}?</h3><p id="archive-description" className="mt-1 text-sm text-slate-600">You can restore it later from My Health.</p><div className="mt-4 flex flex-wrap gap-2"><Button variant="destructive" disabled={saving} onClick={() => void archive()}>{saving ? "Archiving…" : `Archive ${name}`}</Button><Button variant="secondary" disabled={saving} onClick={() => setConfirmArchive(false)}>Cancel</Button></div></div> : <Button variant="secondary" className="mt-4" onClick={() => setConfirmArchive(true)}>Archive condition</Button>}</Surface>
  </PageContainer>;
}
