"use client";
import { useCallback, useEffect, useState } from "react";
import { AddConditionDialog } from "./AddConditionDialog";
import { ConditionCard } from "./ConditionCard";
import { Button, ButtonLink, EmptyState, InlineNotice, LoadingSkeleton, PageContainer, PageHeader, Surface } from "@/components/ui/design-system";
import { getConditionCatalog, getUserConditions, restoreCondition } from "@/lib/conditions/conditions";
import type { CatalogCondition, ConditionCategory, UserCondition } from "@/lib/conditions/types";
import { createClient } from "@/lib/supabase/browser";

export function HealthHome() {
  const [categories, setCategories] = useState<ConditionCategory[]>([]); const [catalog, setCatalog] = useState<CatalogCondition[]>([]); const [conditions, setConditions] = useState<UserCondition[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [actionError, setActionError] = useState(""); const [dialogOpen, setDialogOpen] = useState(false); const [restoring, setRestoring] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setLoadError(""); try { const client = createClient(); const [{ categories: categoryRows, catalog: catalogRows }, userRows] = await Promise.all([getConditionCatalog(client), getUserConditions(client)]); setCategories(categoryRows); setCatalog(catalogRows); setConditions(userRows); } catch { setLoadError("We couldn’t load your health profile. Please try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const active = conditions.filter((item) => !item.archived_at); const archived = conditions.filter((item) => item.archived_at);
  async function restore(item: UserCondition) { setRestoring(item.id); setActionError(""); try { await restoreCondition(createClient(), item.id); setConditions((current) => current.map((row) => row.id === item.id ? { ...row, status: "active", archived_at: null } : row)); } catch (error) { setActionError(error instanceof Error ? error.message : "We couldn’t restore this condition."); } finally { setRestoring(null); } }
  return <PageContainer><PageHeader eyebrow="Health profile" title="My Health" description="A private overview of the health areas you are tracking." actions={<Button onClick={() => setDialogOpen(true)}>Add condition</Button>}/>
    <p className="mt-4 text-sm text-slate-600">Your health profile is private to your AXVital account.</p>
    <section className="mt-6 rounded-xl border border-blue-200 bg-blue-50 p-5" aria-labelledby="symptoms-section-title"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="symptoms-section-title" className="text-xl font-semibold text-slate-900">Health activity</h2><p className="mt-1 text-sm text-slate-600">Review your timeline or manage symptom tracking and history.</p></div><div className="flex flex-wrap gap-2"><ButtonLink href="/health/timeline">Health Timeline</ButtonLink><ButtonLink href="/health/symptoms" variant="secondary">Manage symptoms</ButtonLink><ButtonLink href="/health/symptoms/history" variant="secondary">Symptom history</ButtonLink></div></div></section>
    <section className="mt-6" aria-labelledby="health-summary-title"><h2 id="health-summary-title" className="text-lg font-semibold text-slate-900">Health summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Surface compact><p className="text-sm text-slate-500">Conditions</p><p className="mt-1 text-2xl font-semibold text-slate-900">{loading ? "—" : active.length}</p><p className="text-xs text-slate-500">currently tracked</p></Surface>{["Symptoms", "Medications", "Supplements"].map((label) => <Surface compact key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-sm font-semibold text-slate-500">Coming soon</p></Surface>)}</div></section>
    <section className="mt-8" aria-labelledby="conditions-title"><div className="flex items-center justify-between gap-4"><div><h2 id="conditions-title" className="text-xl font-semibold text-slate-900">Conditions you’re managing</h2><p className="mt-1 text-sm text-slate-600">Self-reported health areas you want to track.</p></div></div>{loadError ? <div className="mt-4 grid gap-3"><InlineNotice>{loadError}</InlineNotice><Button variant="secondary" onClick={() => void load()} className="w-fit">Try again</Button></div> : loading ? <div className="mt-4 grid gap-4 sm:grid-cols-2"><LoadingSkeleton className="h-48"/><LoadingSkeleton className="h-48"/></div> : active.length ? <div className="mt-4 grid gap-4 sm:grid-cols-2">{active.map((item) => <ConditionCard key={item.id} item={item}/>)}</div> : <div className="mt-4"><EmptyState title="Track the conditions that matter to you" description="Adding a condition helps AXVital organize symptom tracking, protocols, experiments, and future insights." action={<Button onClick={() => setDialogOpen(true)}>Add a condition</Button>}/></div>}</section>
    {!loading && archived.length ? <section className="mt-8" aria-labelledby="archived-title"><h2 id="archived-title" className="text-lg font-semibold text-slate-900">Archived conditions</h2><p className="mt-1 text-sm text-slate-600">Restore a condition when you want it back in your active health profile.</p>{actionError ? <div className="mt-3"><InlineNotice>{actionError}</InlineNotice></div> : null}<div className="mt-3 divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white">{archived.map((item) => { const name = item.condition?.name ?? item.custom_condition_name ?? "Condition"; return <div key={item.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{name}</p><p className="text-sm text-slate-500">Archived {new Date(item.archived_at!).toLocaleDateString()}</p></div><Button variant="secondary" disabled={restoring === item.id} onClick={() => void restore(item)} aria-label={`Restore ${name}`}>{restoring === item.id ? "Restoring…" : "Restore"}</Button></div>; })}</div></section> : null}
    <aside className="mt-8 rounded-xl bg-slate-100 p-4 text-sm leading-6 text-slate-600">AXVital helps you organize self-reported health information and is not a substitute for professional medical care.</aside>
    <AddConditionDialog key={dialogOpen ? "open" : "closed"} open={dialogOpen} categories={categories} catalog={catalog} onClose={() => setDialogOpen(false)} onAdded={(item) => setConditions((current) => [item, ...current.map((row) => item.is_primary ? { ...row, is_primary: false } : row)])}/>
  </PageContainer>;
}
