import Link from "next/link";
import { TrustPage } from "@/components/account/TrustPage";

// TODO(legal): Add the formal legal entity, governing law, venue, and any approved dispute terms after owner/legal review.
export default function TermsPage(){return <TrustPage title="Terms of Service">
  <p className="text-sm text-slate-500">Effective September 3, 2026</p>
  <section><h2 className="text-xl font-semibold">Acceptance and eligibility</h2><p>By creating an account or using AXVital, you agree to these Terms and the <Link className="text-blue-700 underline" href="/privacy">Privacy Policy</Link>. You must be at least 13 and legally able to enter this agreement. If you use AXVital for an organization, you represent that you have authority to bind it.</p></section>
  <section><h2 className="text-xl font-semibold">Accounts</h2><p>Provide accurate account information, safeguard your credentials, and promptly report suspected unauthorized access. You are responsible for activity under your account except where applicable law provides otherwise.</p></section>
  <section><h2 className="text-xl font-semibold">Permitted and prohibited use</h2><p>You may use AXVital for lawful personal health and wellness tracking. You may not access another person’s account; submit information without authorization; reverse engineer, disrupt, overload, scrape, or probe the service; evade access or usage controls; distribute malware; infringe rights; or use AXVital unlawfully.</p></section>
  <section><h2 className="text-xl font-semibold">Your information</h2><p>You retain rights in information you provide. You give AXVital permission to host, process, reproduce, and display it only as reasonably necessary to operate, secure, support, and improve the service. You are responsible for having the right to submit that information and for its accuracy.</p></section>
  <section><h2 className="text-xl font-semibold">AXVital intellectual property</h2><p>AXVital and its software, interface, branding, documentation, and service content are owned by AXVital or its licensors and protected by applicable intellectual-property laws. These Terms grant only a limited, revocable, non-transferable right to use the service as intended.</p></section>
  <section><h2 className="text-xl font-semibold">Subscriptions and billing</h2><p>Premium subscriptions may be offered monthly or annually at the price shown before purchase. Stripe processes payment information and recurring charges. Unless canceled, a subscription may renew at the selected interval. Manage cancellation through <Link className="text-blue-700 underline" href="/settings/billing">Billing</Link>; cancellation ordinarily prevents future renewal while access may continue through the paid period. Account deletion is separate and may end remaining access immediately. AXVital does not state a general refund policy here; contact Support for a review subject to applicable law and the purchase terms shown at checkout.</p></section>
  <section><h2 className="text-xl font-semibold">Changes to pricing or service</h2><p>AXVital may change features, plans, or prices. Changes affecting an existing subscription will be communicated or applied as required by applicable law and the checkout terms. Features may evolve, be suspended, or be discontinued.</p></section>
  <section><h2 className="text-xl font-semibold">Health and wellness disclaimer</h2><p>AXVital is a wellness information tool, not a healthcare provider. It does not provide medical advice, diagnosis, treatment, emergency monitoring, or a clinician-patient relationship. Insights, correlations, trends, experiments, recaps, and other outputs do not establish cause and effect or guarantee outcomes. You remain responsible for health decisions and should consult a qualified professional before changing medication, treatment, diet, supplements, or exercise. Review the full <Link className="text-blue-700 underline" href="/health-disclaimer">Health Disclaimer</Link>.</p></section>
  <section><h2 className="text-xl font-semibold">Third-party services</h2><p>The service relies on providers including Supabase, Vercel, Stripe, and Resend. Their services may be governed by separate terms and may occasionally be unavailable. AXVital is not responsible for third-party services beyond the extent required by law.</p></section>
  <section><h2 className="text-xl font-semibold">Termination and deletion</h2><p>You may stop using AXVital and may request account deletion through Settings. AXVital may suspend or terminate access for material violations, security risk, unlawful conduct, or service discontinuation. Provisions that by their nature should survive termination—including ownership, disclaimers, limitations, and accrued payment obligations—will survive.</p></section>
  <section><h2 className="text-xl font-semibold">Disclaimers</h2><p>To the extent permitted by law, AXVital is provided “as is” and “as available,” without warranties of uninterrupted availability, accuracy, fitness for a particular purpose, non-infringement, or particular health or experiment results. Applicable law may give you rights that cannot be waived.</p></section>
  <section><h2 className="text-xl font-semibold">Limitation of liability</h2><p>To the extent permitted by law, AXVital will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, lost profits, lost data, or health decisions based on the service. Nothing in these Terms limits liability that cannot legally be limited.</p></section>
  <section><h2 className="text-xl font-semibold">Indemnification</h2><p>To the extent permitted by law, you agree to indemnify AXVital against third-party claims arising from your unlawful use of the service, violation of these Terms, or submission of information you lacked authority to provide.</p></section>
  <section><h2 className="text-xl font-semibold">Changes and contact</h2><p>AXVital may revise these Terms and will identify updates by their effective date, with additional notice when appropriate. Continued use after an effective update constitutes acceptance where permitted by law. Questions may be submitted through <Link className="text-blue-700 underline" href="/contact">Contact AXVital</Link>.</p></section>
</TrustPage>}
