import Link from "next/link";
import type { ButtonHTMLAttributes, HTMLAttributes, ReactNode } from "react";
import { uiStyles } from "@/lib/ui-styles";

export const controlClass = uiStyles.control;
export const textareaClass = `${controlClass} py-3`;

const buttonStyles = uiStyles.button;
export type ButtonVariant = keyof typeof buttonStyles;
export function Button({ variant = "primary", className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: ButtonVariant }) { return <button {...props} className={`inline-flex min-h-11 items-center justify-center rounded-lg px-4 text-sm font-semibold outline-none transition focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 ${buttonStyles[variant]} ${className}`}/>; }
export function ButtonLink({ href, children, variant = "primary", className = "" }: { href: string; children: ReactNode; variant?: ButtonVariant; className?: string }) { return <Link href={href} className={`inline-flex min-h-11 items-center justify-center rounded-lg px-4 text-sm font-semibold outline-none transition focus-visible:ring-2 focus-visible:ring-offset-2 ${buttonStyles[variant]} ${className}`}>{children}</Link>; }

export function PageContainer({ narrow = false, className = "", ...props }: HTMLAttributes<HTMLDivElement> & { narrow?: boolean }) { return <div {...props} className={`mx-auto w-full ${narrow ? "max-w-3xl" : "max-w-6xl"} px-4 py-6 sm:px-6 lg:py-8 ${className}`}/>; }
export function PageHeader({ title, description, eyebrow, actions }: { title: string; description?: string; eyebrow?: string; actions?: ReactNode }) { return <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow ? <p className="text-sm font-semibold text-blue-700">{eyebrow}</p> : null}<h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">{title}</h1>{description ? <p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">{description}</p> : null}</div>{actions ? <div className="flex flex-wrap gap-2">{actions}</div> : null}</header>; }
export function Surface({ compact = false, className = "", ...props }: HTMLAttributes<HTMLElement> & { compact?: boolean }) { return <section {...props} className={`rounded-xl border border-slate-200 bg-white ${compact ? "p-4" : "p-4 sm:p-5"} ${className}`}/>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-6 text-center"><h3 className="font-semibold text-slate-900">{title}</h3><p className="mt-1 text-sm text-slate-600">{description}</p>{action ? <div className="mt-4">{action}</div> : null}</div>; }
export function InlineNotice({ tone = "error", children }: { tone?: "error" | "success" | "info"; children: ReactNode }) { const style = tone === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : tone === "info" ? "border-blue-200 bg-blue-50 text-blue-800" : "border-red-200 bg-red-50 text-red-800"; return <p role={tone === "error" ? "alert" : "status"} className={`rounded-lg border p-3 text-sm font-medium ${style}`}>{children}</p>; }
export function StatusBadge({ status }: { status: string }) { const normalized = status.toLowerCase(); const style = normalized === "completed" || normalized === "success" ? "bg-emerald-50 text-emerald-700" : normalized === "in_progress" || normalized === "active" ? "bg-blue-50 text-blue-700" : normalized === "paused" || normalized === "skipped" ? "bg-amber-50 text-amber-700" : normalized === "cancelled" || normalized === "failed" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600"; return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${style}`}>{status.replaceAll("_", " ")}</span>; }
export function LoadingSkeleton({ className = "h-20" }: { className?: string }) { return <div aria-busy="true" className={`animate-pulse rounded-xl bg-slate-200 motion-reduce:animate-none ${className}`}><span className="sr-only">Loading</span></div>; }
