export type Plan="free"|"premium";export type SubscriptionStatus="active"|"trialing"|"past_due"|"canceled"|"incomplete"|"incomplete_expired"|"unpaid"|"paused"|"inactive";
export type Entitlement="trigger_discovery"|"predictive_outlook"|"advanced_insights"|"advanced_weekly_recap"|"full_experiments"|"voice_logging"|"advanced_wearable_intelligence";
export type SubscriptionState={plan:Plan;status:SubscriptionStatus;currentPeriodEnd:string|null;cancelAtPeriodEnd:boolean};
export type EntitlementState="active"|"grace_period"|"inactive";
export const FEATURE_MATRIX:Record<Plan,ReadonlySet<Entitlement>>={free:new Set(),premium:new Set(["trigger_discovery","predictive_outlook","advanced_insights","advanced_weekly_recap","full_experiments","voice_logging","advanced_wearable_intelligence"])};
export function entitlementState(subscription:SubscriptionState|null,now=new Date()):EntitlementState{if(!subscription||subscription.plan!=="premium")return"inactive";if(subscription.status==="active"||subscription.status==="trialing")return subscription.currentPeriodEnd&&new Date(subscription.currentPeriodEnd)<=now?"inactive":"active";if((subscription.status==="past_due"||subscription.status==="canceled")&&subscription.currentPeriodEnd&&new Date(subscription.currentPeriodEnd)>now)return"grace_period";return"inactive"}
export function developmentBypass(env:Partial<Pick<NodeJS.ProcessEnv,"NODE_ENV"|"AXVITAL_BILLING_BYPASS">>=process.env){return env.NODE_ENV!=="production"&&env.AXVITAL_BILLING_BYPASS==="true"}
export function hasEntitlement(subscription:SubscriptionState|null,entitlement:Entitlement,env:Partial<Pick<NodeJS.ProcessEnv,"NODE_ENV"|"AXVITAL_BILLING_BYPASS">>=process.env,now=new Date()){return developmentBypass(env)||(entitlementState(subscription,now)!=="inactive"&&FEATURE_MATRIX.premium.has(entitlement))}
export function subscriptionFromRow(row:{plan?:string;status?:string;current_period_end?:string|null;cancel_at_period_end?:boolean}|null):SubscriptionState|null{if(!row)return null;const statuses:SubscriptionStatus[]=["active","trialing","past_due","canceled","incomplete","incomplete_expired","unpaid","paused","inactive"];return{plan:row.plan==="premium"?"premium":"free",status:statuses.includes(row.status as SubscriptionStatus)?row.status as SubscriptionStatus:"inactive",currentPeriodEnd:row.current_period_end??null,cancelAtPeriodEnd:Boolean(row.cancel_at_period_end)}}
