import type { SupabaseClient } from "@supabase/supabase-js";
import { exerciseDisplayLabel, groupLabel } from "./grouping";
import type { WorkoutTemplate, WorkoutTemplateDependencies, WorkoutTemplateInput } from "./types";

async function uid(client: SupabaseClient) { const { data, error } = await client.auth.getUser(); if (error || !data.user) throw new Error("AUTH_REQUIRED"); return data.user.id; }
export async function getWorkoutTemplates(client: SupabaseClient, archived = false) { const user = await uid(client); const { data, error } = await client.from("workout_templates").select("*,groups:workout_template_groups(id,exercises:workout_template_exercises(id,sets:workout_template_sets(id)))").eq("user_id", user).eq("is_archived", archived).order("name"); if (error) throw error; return (data ?? []) as WorkoutTemplate[]; }
export async function getWorkoutTemplateById(client: SupabaseClient, id: string) { const user = await uid(client); const { data, error } = await client.from("workout_templates").select("*,groups:workout_template_groups(*,exercises:workout_template_exercises(*,exercise:exercises(*),sets:workout_template_sets(*)))").eq("id", id).eq("user_id", user).order("group_order", { referencedTable: "workout_template_groups" }).single(); if (error) throw error; const template=data as WorkoutTemplate; template.groups?.sort((a,b)=>a.group_order-b.group_order).forEach(g=>{g.exercises?.sort((a,b)=>a.exercise_order-b.exercise_order).forEach(e=>e.sets?.sort((a,b)=>a.set_number-b.set_number));}); return template; }
export async function createWorkoutTemplate(client: SupabaseClient, input: WorkoutTemplateInput) { const user=await uid(client); const {groups,...head}=input; const {data,error}=await client.from("workout_templates").insert({...head,user_id:user}).select("*").single(); if(error)throw error; try { for(let gi=0;gi<groups.length;gi++){const g=groups[gi],label=groupLabel(gi);const{data:group,error:ge}=await client.from("workout_template_groups").insert({user_id:user,workout_template_id:data.id,group_order:gi,group_label:label,group_type:g.group_type,rounds:g.rounds,rest_between_exercises_seconds:g.rest_between_exercises_seconds,rest_after_group_seconds:g.rest_after_group_seconds,notes:g.notes}).select("*").single();if(ge)throw ge;for(let ei=0;ei<g.exercises.length;ei++){const e=g.exercises[ei],{sets,exercise,...values}=e;const{data:te,error:ee}=await client.from("workout_template_exercises").insert({...values,user_id:user,workout_template_id:data.id,workout_template_group_id:group.id,exercise_id:exercise.id,exercise_order:ei,display_label:exerciseDisplayLabel(label,ei),target_sets:sets.length}).select("*").single();if(ee)throw ee;if(sets.length){const{error:se}=await client.from("workout_template_sets").insert(sets.map((s,si)=>({...s,user_id:user,workout_template_exercise_id:te.id,set_number:si+1})));if(se)throw se;}}}return getWorkoutTemplateById(client,data.id);}catch(reason){await client.from("workout_templates").delete().eq("id",data.id).eq("user_id",user);throw reason;} }
export async function updateWorkoutTemplate(client:SupabaseClient,id:string,input:WorkoutTemplateInput){await uid(client);const{error}=await client.rpc("replace_workout_template",{target_id:id,payload:input});if(error)throw error;return getWorkoutTemplateById(client,id);}
export async function archiveWorkoutTemplate(client:SupabaseClient,id:string,archived=true){const user=await uid(client);const{data,error}=await client.from("workout_templates").update({is_archived:archived}).eq("id",id).eq("user_id",user).select("id").maybeSingle();if(error||!data)throw error??new Error("TEMPLATE_NOT_FOUND");}
export async function getWorkoutTemplateDependencies(client:SupabaseClient,id:string){await uid(client);const{data,error}=await client.rpc("workout_template_dependencies",{target_id:id});if(error)throw error;if(!data)throw new Error("TEMPLATE_NOT_FOUND");return data as WorkoutTemplateDependencies;}
export async function deleteWorkoutTemplate(client:SupabaseClient,id:string){await uid(client);const{data,error}=await client.rpc("delete_workout_template_if_unused",{target_id:id});if(error)throw error;return Boolean(data);}
export async function duplicateWorkoutTemplate(client:SupabaseClient,id:string){const t=await getWorkoutTemplateById(client,id);return createWorkoutTemplate(client,{name:`${t.name} Copy`,description:t.description,category:t.category,estimated_duration_minutes:t.estimated_duration_minutes,notes:t.notes,groups:(t.groups??[]).map(g=>({group_type:g.group_type,rounds:g.rounds,rest_between_exercises_seconds:g.rest_between_exercises_seconds,rest_after_group_seconds:g.rest_after_group_seconds,notes:g.notes,exercises:(g.exercises??[]).map(e=>({exercise:e.exercise!,tracking_type:e.tracking_type,tempo:e.tempo,rest_after_exercise_seconds:e.rest_after_exercise_seconds,notes:e.notes,sets:(e.sets??[]).map(s=>({set_number:s.set_number,set_type:s.set_type,target_reps:s.target_reps,target_reps_min:s.target_reps_min,target_reps_max:s.target_reps_max,target_weight:s.target_weight,target_duration_seconds:s.target_duration_seconds,target_distance:s.target_distance,distance_unit:s.distance_unit,is_optional:s.is_optional,notes:s.notes}))}))}))});}
