import type { ConditionCampaign } from "@/lib/campaigns/conditions";

const linkStyle = "inline-flex min-h-11 items-center underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-blue-500";
function Signup() {
  return <a href="/signup" rel="noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-blue-600 px-7 font-semibold text-white transition hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-400">Get Started</a>;
}
function PrivacyNote() {
  return <p className="mt-3 text-sm leading-6">Choose what you record. Read how personal information is handled in our <a href="/privacy" rel="noreferrer" className={linkStyle}>Privacy Policy</a>.</p>;
}

export function ConditionLandingPage({ content }: { content: ConditionCampaign }) {
  return <div className="[overflow-wrap:anywhere]">
    <section className="bg-slate-950 px-4 py-10 text-white sm:px-6 sm:py-16 lg:py-20">
      <div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1.2fr_0.8fr] lg:items-center">
        <div><p className="text-sm font-semibold uppercase tracking-widest text-blue-300">{content.name} · Personal tracking</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-[1.1] tracking-tight sm:text-5xl lg:text-6xl">{content.headline}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">{content.intro}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Signup/><a href="#how-it-works" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-600 px-6 font-semibold hover:bg-slate-800 focus-visible:outline-2 focus-visible:outline-blue-400">See how it works</a></div><div className="text-slate-300"><PrivacyNote/></div></div>
        <aside className="rounded-3xl border border-slate-700 bg-slate-900 p-6 sm:p-8" aria-label="Example tracking question"><p className="text-sm font-semibold text-blue-300">A question, not a conclusion</p><blockquote className="mt-4 text-2xl font-medium leading-snug">“{content.questions[0]}”</blockquote><div className="mt-6 space-y-3 border-t border-slate-700 pt-6">{["Record the days that matter", "Keep everyday context together", "Review your own history"].map((text, i) => <p key={text} className="flex gap-3 text-slate-300"><span className="font-semibold text-blue-300">0{i + 1}</span>{text}</p>)}</div><p className="mt-6 text-sm leading-6 text-slate-400">Illustrative question—not a finding or a promise of results.</p></aside>
      </div>
    </section>

    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="max-w-3xl"><h2 className="text-3xl font-semibold tracking-tight">There’s more to remember than a symptom score.</h2><p className="mt-4 text-lg leading-8 text-slate-600">When symptoms change, it can be hard to remember the days around them. Sleep, stress, routines, and other circumstances are context you may want to record—not proof of a cause or a trigger.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2">{[["What you may want to record", content.symptoms], ["Everyday context you may choose to track", content.context]].map(([heading, items]) => <article key={heading as string} className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="text-xl font-semibold">{heading}</h3><ul className="mt-4 space-y-2 text-slate-600">{(items as string[]).map(item => <li key={item} className="flex gap-3 leading-7"><span aria-hidden="true" className="text-blue-600">•</span>{item}</li>)}</ul></article>)}</div><p className="mt-4 text-sm leading-6 text-slate-500">Use available logs and notes for the information relevant to you. You do not need to track everything.</p></section>

    <section id="how-it-works" className="scroll-mt-24 bg-white px-4 py-12 sm:px-6 sm:py-16"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-blue-700">Track what matters → Learn what affects you → Test what works</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">From a daily record to a personal question.</h2><ol className="mt-8 grid gap-5 md:grid-cols-3">{[
      ["Track", "Record symptoms and episodes alongside sleep, activities, nutrition, supplements, treatments, workouts, or other events. Build habits for recurring actions and protocols for structured routines."],
      ["Learn", "Review trends, changes over time, possible correlations, and weekly summaries. AXVital Insights helps surface patterns worth paying attention to when enough relevant data is available."],
      ["Test", "Use Experiments to structure a personal question and compare tracked outcomes around one deliberate change. Review adherence and results without treating an association as medical causation."],
    ].map(([title, body], i) => <li key={title} className="rounded-2xl border border-slate-200 p-6"><span className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 font-semibold text-blue-700">{i + 1}</span><h3 className="mt-5 text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-600">{body}</p></li>)}</ol></div></section>

    <section className="bg-slate-950 px-4 py-12 text-white sm:px-6 sm:py-16"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2"><div><p className="text-sm font-semibold text-blue-300">AXVital Experiments</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Don’t just track. Test.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Form a question. Choose an outcome. Intentionally change one thing, track adherence, and review what happened.</p><p className="mt-4 leading-7 text-slate-300">Experiments organize your observations; they do not establish medical causes. Results may be limited or inconclusive. Available outcomes and readiness depend on what you track.</p><div className="mt-6"><Signup/><PrivacyNote/></div></div><div className="rounded-2xl border border-slate-700 bg-slate-900 p-6 sm:p-8"><p className="text-sm font-semibold text-blue-300">Hypothetical personal tracking question</p><blockquote className="mt-4 text-2xl leading-snug">“{content.experiment}”</blockquote><p className="mt-6 leading-7 text-slate-300">This is an example, not medical advice or a recommended intervention. Do not stop or change medication or treatment for an experiment without guidance from your healthcare professional.</p><p className="mt-4 text-sm leading-6 text-slate-400">Exploration is available before starting. Saving and starting Experiments requires Premium.</p></div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-12 sm:px-6 sm:py-16"><div className="grid gap-10 lg:grid-cols-2"><div><h2 className="text-3xl font-semibold tracking-tight">Patterns worth exploring. Not automatic answers.</h2><p className="mt-4 text-lg leading-8 text-slate-600">Use trends, summaries, and experiment results to explore your own questions. Missing observations and limited data can leave a question unanswered.</p></div><ul className="space-y-3">{content.questions.map(question => <li key={question} className="rounded-xl border border-blue-100 bg-blue-50 p-5 leading-7 text-slate-700">{question}</li>)}</ul></div></section>

    <section className="bg-white px-4 py-12 sm:px-6 sm:py-16"><div className="mx-auto max-w-6xl rounded-3xl border border-slate-200 p-6 sm:p-10"><h2 className="text-3xl font-semibold tracking-tight">Bring better context to your next appointment.</h2><p className="mt-4 max-w-3xl text-lg leading-8 text-slate-600">An organized history can help you remember when symptoms changed, what you were tracking, the routines you followed, and how recorded outcomes changed over time. Use that context for a conversation—not a diagnosis.</p><p className="mt-4 max-w-3xl leading-7 text-slate-600">{content.caution}</p></div></section>

    <section className="mx-auto max-w-4xl px-4 py-12 text-center sm:px-6 sm:py-16"><h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">Start with what matters to you.</h2><p className="mt-4 text-lg leading-8 text-slate-600">AXVital doesn’t tell you what should work. It helps you track what is happening, explore your own patterns, and test questions for yourself.</p><div className="mt-6"><Signup/><PrivacyNote/></div></section>
    <aside className="border-y border-slate-200 bg-white px-4 py-6 sm:px-6" aria-label="Health disclaimer"><p className="mx-auto max-w-6xl text-sm leading-7 text-slate-600">AXVital is a personal health tracking and wellness information platform. It does not provide medical advice, diagnosis, or treatment. It is not a medical device or a replacement for healthcare professionals. <a href="/health-disclaimer" rel="noreferrer" className={linkStyle}>Read the Health Disclaimer</a>.</p></aside>
    <footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-6 text-sm text-slate-600 sm:px-6"><span className="font-semibold text-slate-900">AXVital</span><nav aria-label="Campaign legal links" className="flex flex-wrap gap-x-6"><a href="/privacy" rel="noreferrer" className={linkStyle}>Privacy</a><a href="/terms" rel="noreferrer" className={linkStyle}>Terms</a><a href="/contact" rel="noreferrer" className={linkStyle}>Contact</a></nav></footer>
  </div>;
}
