"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createWorkoutTemplate, getWorkoutTemplateById, updateWorkoutTemplate } from "@/lib/workouts/templates";
import type { Exercise, GroupType, WorkoutTemplateInput } from "@/lib/workouts/types";
import { supabase } from "@/lib/supabase/client";
import { ExerciseSelector } from "./ExerciseSelector";

type Group=WorkoutTemplateInput["groups"][number]; type Item=Group["exercises"][number];
const blankGroup=():Group=>({group_type:"single",rounds:null,rest_between_exercises_seconds:null,rest_after_group_seconds:90,notes:null,exercises:[]});
const blankSet=()=>({set_number:1,set_type:"working",target_reps:8,target_reps_min:null,target_reps_max:null,target_weight:null,target_duration_seconds:null,target_distance:null,distance_unit:null,is_optional:false,notes:null});
const initial:WorkoutTemplateInput={name:"",description:null,category:"strength",estimated_duration_minutes:60,notes:null,groups:[]};
export function WorkoutTemplateBuilder({templateId}:{templateId?:string}){
 const router=useRouter(),[form,setForm]=useState(initial),[loading,setLoading]=useState(Boolean(templateId)),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const input="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base";
 useEffect(()=>{if(!templateId)return;void getWorkoutTemplateById(supabase,templateId).then(t=>setForm({name:t.name,description:t.description,category:t.category,estimated_duration_minutes:t.estimated_duration_minutes,notes:t.notes,groups:(t.groups??[]).map(g=>({group_type:g.group_type,rounds:g.rounds,rest_between_exercises_seconds:g.rest_between_exercises_seconds,rest_after_group_seconds:g.rest_after_group_seconds,notes:g.notes,exercises:(g.exercises??[]).map(e=>({exercise:e.exercise!,tracking_type:e.tracking_type,tempo:e.tempo,rest_after_exercise_seconds:e.rest_after_exercise_seconds,notes:e.notes,sets:(e.sets??[]).map(s=>({...s}))}))}))})).catch(()=>setError("We couldn’t load this workout template.")).finally(()=>setLoading(false));},[templateId]);
 const updateGroup=(i:number,patch:Partial<Group>)=>setForm(v=>({...v,groups:v.groups.map((g,x)=>x===i?{...g,...patch}:g)}));
 const updateItem=(gi:number,ei:number,fn:(x:Item)=>Item)=>updateGroup(gi,{exercises:form.groups[gi].exercises.map((x,i)=>i===ei?fn(x):x)});
 const move=<T,>(items:T[],from:number,to:number)=>{const out=[...items];const[x]=out.splice(from,1);out.splice(to,0,x);return out};
 function addExercise(gi:number,exercise:Exercise){updateGroup(gi,{exercises:[...form.groups[gi].exercises,{exercise,tracking_type:exercise.default_tracking_type,tempo:null,rest_after_exercise_seconds:null,notes:null,sets:[blankSet()]}]});}
 async function submit(e:FormEvent){e.preventDefault();if(saving)return;if(!form.name.trim()||!form.groups.some(g=>g.exercises.length)){setError("Add a name and at least one exercise.");return}setSaving(true);setError("");try{const t=templateId?await updateWorkoutTemplate(supabase,templateId,form):await createWorkoutTemplate(supabase,form);router.push(`/workouts/templates/${t.id}`);}catch{setError("We couldn’t save your template changes. Your edits are still here.");setSaving(false);}}
 if(loading)return <p className="p-8" role="status">Loading template…</p>;
 return <form onSubmit={submit} className="mx-auto max-w-4xl px-4 py-6 sm:px-6">
  <header className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-sm font-bold uppercase tracking-widest text-emerald-300">Workout template</p><h1 className="mt-1 text-3xl font-black">{templateId?"Edit Workout":"Build a Workout"}</h1><p className="mt-2 text-sm text-slate-300">Changes apply to workouts scheduled in the future. Existing plans and history stay unchanged.</p></header>
  {error?<p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 font-semibold text-rose-700">{error}</p>:null}
  <section className="mt-5 grid gap-4 rounded-2xl bg-white p-4 sm:grid-cols-2">
   <label className="font-semibold sm:col-span-2">Name<input required maxLength={120} autoFocus className={input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>
   <label className="font-semibold sm:col-span-2">Description<textarea rows={3} className={`${input} py-3`} value={form.description??""} onChange={e=>setForm({...form,description:e.target.value||null})}/></label>
   <label className="font-semibold">Estimated minutes<input type="number" min="1" className={input} value={form.estimated_duration_minutes??""} onChange={e=>setForm({...form,estimated_duration_minutes:e.target.value?Number(e.target.value):null})}/></label>
   <label className="font-semibold">Category<input className={input} value={form.category??""} onChange={e=>setForm({...form,category:e.target.value||null})}/></label>
   <label className="font-semibold sm:col-span-2">Template notes<textarea rows={2} className={`${input} py-3`} value={form.notes??""} onChange={e=>setForm({...form,notes:e.target.value||null})}/></label>
  </section>
  <div className="mt-5 flex items-center justify-between gap-3"><h2 className="text-2xl font-black">Exercise groups</h2><button type="button" onClick={()=>setForm({...form,groups:[...form.groups,blankGroup()]})} className="min-h-11 rounded-full bg-emerald-600 px-4 font-bold text-white">Add group</button></div>
  <div className="mt-4 space-y-4">{form.groups.map((g,gi)=><fieldset key={gi} className="min-w-0 rounded-2xl bg-white p-4 shadow-sm"><legend className="px-2 text-xl font-black">Group {String.fromCharCode(65+gi)}</legend>
   <div className="grid gap-3 sm:grid-cols-3"><label className="font-semibold">Group type<select className={input} value={g.group_type} onChange={e=>updateGroup(gi,{group_type:e.target.value as GroupType})}>{["single","superset","triset","circuit"].map(v=><option key={v}>{v}</option>)}</select></label><label className="font-semibold">Rest between exercises<input type="number" min="0" className={input} value={g.rest_between_exercises_seconds??""} onChange={e=>updateGroup(gi,{rest_between_exercises_seconds:e.target.value?Number(e.target.value):null})}/></label><label className="font-semibold">Rest after group<input type="number" min="0" className={input} value={g.rest_after_group_seconds??""} onChange={e=>updateGroup(gi,{rest_after_group_seconds:e.target.value?Number(e.target.value):null})}/></label></div>
   <div className="mt-3 flex flex-wrap gap-2"><button type="button" aria-label={`Move group ${gi+1} up`} disabled={!gi} onClick={()=>setForm({...form,groups:move(form.groups,gi,gi-1)})} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">↑ Group</button><button type="button" aria-label={`Move group ${gi+1} down`} disabled={gi===form.groups.length-1} onClick={()=>setForm({...form,groups:move(form.groups,gi,gi+1)})} className="min-h-11 rounded-lg border px-3 disabled:opacity-40">↓ Group</button><button type="button" onClick={()=>setForm({...form,groups:form.groups.filter((_,i)=>i!==gi)})} className="min-h-11 rounded-lg px-3 font-semibold text-amber-800">Remove group</button></div>
   <div className="mt-4"><p className="font-semibold">Add or replace exercise</p><ExerciseSelector onSelect={x=>addExercise(gi,x)}/></div>
   <div className="mt-4 space-y-3">{g.exercises.map((item,ei)=><article key={`${item.exercise.id}-${ei}`} className="min-w-0 rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-black">{String.fromCharCode(65+gi)}{ei+1} {item.exercise.name}</h3><div className="flex gap-1"><button type="button" aria-label={`Move ${item.exercise.name} up`} disabled={!ei} onClick={()=>updateGroup(gi,{exercises:move(g.exercises,ei,ei-1)})} className="min-h-11 min-w-11 rounded-lg border">↑</button><button type="button" aria-label={`Move ${item.exercise.name} down`} disabled={ei===g.exercises.length-1} onClick={()=>updateGroup(gi,{exercises:move(g.exercises,ei,ei+1)})} className="min-h-11 min-w-11 rounded-lg border">↓</button><button type="button" aria-label={`Remove ${item.exercise.name}`} onClick={()=>updateGroup(gi,{exercises:g.exercises.filter((_,i)=>i!==ei)})} className="min-h-11 rounded-lg px-2 font-semibold text-amber-800">Remove</button></div></div>
    <div className="mt-2 flex flex-wrap gap-2">{gi>0?<button type="button" onClick={()=>setForm({...form,groups:form.groups.map((group,index)=>index===gi?{...group,exercises:group.exercises.filter((_,i)=>i!==ei)}:index===gi-1?{...group,exercises:[...group.exercises,item]}:group)})} className="min-h-11 rounded-lg border px-3">Move to previous group</button>:null}{gi<form.groups.length-1?<button type="button" onClick={()=>setForm({...form,groups:form.groups.map((group,index)=>index===gi?{...group,exercises:group.exercises.filter((_,i)=>i!==ei)}:index===gi+1?{...group,exercises:[...group.exercises,item]}:group)})} className="min-h-11 rounded-lg border px-3">Move to next group</button>:null}</div>
    <div className="mt-3 grid gap-2 sm:grid-cols-3"><label className="text-sm font-semibold">Rest seconds<input type="number" min="0" className={input} value={item.rest_after_exercise_seconds??""} onChange={e=>updateItem(gi,ei,x=>({...x,rest_after_exercise_seconds:e.target.value?Number(e.target.value):null}))}/></label><label className="text-sm font-semibold sm:col-span-2">Exercise notes<input className={input} value={item.notes??""} onChange={e=>updateItem(gi,ei,x=>({...x,notes:e.target.value||null}))}/></label></div>
    <div className="mt-3 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr><th>Set</th><th>Reps</th><th>Weight</th><th>Duration</th><th>Distance</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{item.sets.map((set,si)=><tr key={si}><td>{si+1}</td>{(["target_reps","target_weight","target_duration_seconds","target_distance"] as const).map(k=><td key={k}><input aria-label={`${item.exercise.name} set ${si+1} ${k.replaceAll("_"," ")}`} type="number" min="0" step={k.includes("weight")||k.includes("distance")?"any":1} className="my-1 min-h-11 w-24 rounded-lg border px-2" value={set[k]??""} onChange={e=>updateItem(gi,ei,x=>({...x,sets:x.sets.map((s,i)=>i===si?{...s,[k]:e.target.value?Number(e.target.value):null}:s)}))}/></td>)}<td><button type="button" aria-label={`Remove set ${si+1} from ${item.exercise.name}`} onClick={()=>updateItem(gi,ei,x=>({...x,sets:x.sets.filter((_,i)=>i!==si)}))} className="min-h-11 text-amber-800">Remove</button></td></tr>)}</tbody></table></div>
    <button type="button" onClick={()=>updateItem(gi,ei,x=>({...x,sets:[...x.sets,{...blankSet(),set_number:x.sets.length+1}]}))} className="mt-2 min-h-11 rounded-lg border px-3 font-semibold">Add set</button>
   </article>)}</div>
  </fieldset>)}</div>
  <button disabled={saving} className="mt-6 min-h-14 w-full rounded-full bg-slate-950 text-lg font-black text-white disabled:opacity-60">{saving?"Saving…":templateId?"Save Template Changes":"Save Workout Template"}</button>
 </form>;
}
