"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createWorkoutTemplate } from "@/lib/workouts/templates";
import type { Exercise, GroupType, WorkoutTemplateInput } from "@/lib/workouts/types";
import { supabase } from "@/lib/supabase/client";
import { ExerciseSelector } from "./ExerciseSelector";

const blankGroup = (): WorkoutTemplateInput["groups"][number] => ({ group_type: "single", rounds: null, rest_between_exercises_seconds: null, rest_after_group_seconds: 90, notes: null, exercises: [] });
export function WorkoutTemplateBuilder() {
  const router = useRouter();
  const [form, setForm] = useState<WorkoutTemplateInput>({ name: "", description: null, category: "strength", estimated_duration_minutes: 60, notes: null, groups: [] });
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const input = "mt-2 min-h-12 w-full rounded-2xl border border-slate-200 px-4 font-bold";
  const updateGroup = (index: number, patch: Partial<WorkoutTemplateInput["groups"][number]>) => setForm((value) => ({ ...value, groups: value.groups.map((group, current) => current === index ? { ...group, ...patch } : group) }));
  function addExercise(groupIndex: number, exercise: Exercise) { const group = form.groups[groupIndex]; updateGroup(groupIndex, { exercises: [...group.exercises, { exercise, tracking_type: exercise.default_tracking_type, tempo: null, rest_after_exercise_seconds: null, notes: null, sets: [{ set_number: 1, set_type: "working", target_reps: 8, target_reps_min: null, target_reps_max: null, target_weight: null, target_duration_seconds: null, target_distance: null, distance_unit: null, is_optional: false, notes: null }] }] }); }
  async function submit(event: FormEvent) { event.preventDefault(); if (!form.name.trim() || !form.groups.some((group) => group.exercises.length)) return setError("Add a name and at least one exercise."); setSaving(true); try { const template = await createWorkoutTemplate(supabase, form); router.push(`/workouts/templates/${template.id}`); } catch { setError("We couldn’t save this workout template."); setSaving(false); } }
  return <form onSubmit={submit} className="mx-auto max-w-4xl px-4 py-6 md:px-6 md:py-10">
    <section className="rounded-3xl bg-slate-950 p-6 text-white"><p className="text-sm font-black uppercase tracking-widest text-emerald-300">Workout template</p><h1 className="mt-2 text-4xl font-black">Build a Workout</h1></section>
    {error ? <p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</p> : null}
    <section className="mt-5 grid gap-4 rounded-3xl bg-white p-5 sm:grid-cols-2"><label className="font-bold sm:col-span-2">Name<input autoFocus className={input} value={form.name} onChange={(event) => setForm((value) => ({ ...value, name: event.target.value }))}/></label><label className="font-bold">Estimated minutes<input type="number" min="1" className={input} value={form.estimated_duration_minutes ?? ""} onChange={(event) => setForm((value) => ({ ...value, estimated_duration_minutes: Number(event.target.value) }))}/></label><label className="font-bold">Category<input className={input} value={form.category ?? ""} onChange={(event) => setForm((value) => ({ ...value, category: event.target.value }))}/></label></section>
    <div className="mt-5 flex justify-between"><h2 className="text-2xl font-black">Exercise groups</h2><button type="button" onClick={() => setForm((value) => ({ ...value, groups: [...value.groups, blankGroup()] }))} className="rounded-full bg-emerald-500 px-5 py-3 font-black text-white">Add Group</button></div>
    <div className="mt-4 space-y-4">{form.groups.map((group, groupIndex) => <fieldset key={groupIndex} className="rounded-3xl bg-white p-5 shadow-sm"><legend className="px-2 text-xl font-black">Group {String.fromCharCode(65 + groupIndex)}</legend><label className="font-bold">Group type<select className={input} value={group.group_type} onChange={(event) => updateGroup(groupIndex, { group_type: event.target.value as GroupType })}>{["single", "superset", "triset", "circuit"].map((value) => <option key={value}>{value}</option>)}</select></label><div className="mt-4"><p className="font-bold">Add exercise</p><ExerciseSelector onSelect={(exercise) => addExercise(groupIndex, exercise)}/></div><div className="mt-4 space-y-3">{group.exercises.map((item, exerciseIndex) => <article key={`${item.exercise.id}-${exerciseIndex}`} className="rounded-2xl bg-slate-50 p-4"><p className="font-black">{String.fromCharCode(65 + groupIndex)}{exerciseIndex + 1} {item.exercise.name}</p><div className="mt-3 grid grid-cols-3 gap-2"><label className="text-xs font-bold">Sets<input type="number" min="1" className={input} value={item.sets.length} onChange={(event) => { const count = Number(event.target.value); const sets = Array.from({ length: count }, (_, index) => item.sets[index] ?? { set_number: index + 1, set_type: "working", target_reps: 8, target_reps_min: null, target_reps_max: null, target_weight: null, target_duration_seconds: null, target_distance: null, distance_unit: null, is_optional: false, notes: null }); updateGroup(groupIndex, { exercises: group.exercises.map((exercise, index) => index === exerciseIndex ? { ...exercise, sets } : exercise) }); }}/></label><label className="text-xs font-bold">Reps<input type="number" className={input} value={item.sets[0]?.target_reps ?? ""} onChange={(event) => { const reps = Number(event.target.value); updateGroup(groupIndex, { exercises: group.exercises.map((exercise, index) => index === exerciseIndex ? { ...exercise, sets: exercise.sets.map((set) => ({ ...set, target_reps: reps })) } : exercise) }); }}/></label><label className="text-xs font-bold">Weight<input type="number" step="any" className={input} value={item.sets[0]?.target_weight ?? ""} onChange={(event) => { const weight = event.target.value ? Number(event.target.value) : null; updateGroup(groupIndex, { exercises: group.exercises.map((exercise, index) => index === exerciseIndex ? { ...exercise, sets: exercise.sets.map((set) => ({ ...set, target_weight: weight })) } : exercise) }); }}/></label></div></article>)}</div></fieldset>)}</div>
    <button disabled={saving} className="mt-6 min-h-14 w-full rounded-full bg-slate-950 text-lg font-black text-white">{saving ? "Saving…" : "Save Workout Template"}</button>
  </form>;
}
