"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { archiveExercise, searchExercises } from "@/lib/workouts/exercises";
import { archiveWorkoutTemplate, deleteWorkoutTemplate, duplicateWorkoutTemplate, getWorkoutTemplateDependencies, getWorkoutTemplates } from "@/lib/workouts/templates";
import { getPlannedWorkouts, scheduleWorkout } from "@/lib/workouts/planning";
import { getWorkoutSessions, startWorkoutSession } from "@/lib/workouts/sessions";
import { calculateWorkoutSessionMetrics } from "@/lib/workouts/analytics";
import { metadataLabel } from "@/lib/workouts/exercise-metadata";
import type { Exercise, PlannedWorkout, WorkoutSession, WorkoutTemplate } from "@/lib/workouts/types";
import { supabase } from "@/lib/supabase/client";
import { CustomExerciseForm } from "./CustomExerciseForm";
import { ExerciseSelector } from "./ExerciseSelector";

function today() { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
export function WorkoutsHome() {
  const router = useRouter(); const [tab, setTab] = useState<"planned" | "templates" | "exercises" | "history">("planned");
  const [exercises, setExercises] = useState<Exercise[]>([]); const [templates, setTemplates] = useState<WorkoutTemplate[]>([]); const [archivedTemplates, setArchivedTemplates] = useState<WorkoutTemplate[]>([]); const [showArchived,setShowArchived]=useState(false); const [planned, setPlanned] = useState<PlannedWorkout[]>([]); const [sessions, setSessions] = useState<WorkoutSession[]>([]);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showExercise, setShowExercise] = useState(false); const [showSchedule, setShowSchedule] = useState<WorkoutTemplate | null>(null); const [confirm,setConfirm]=useState<{template:WorkoutTemplate;action:"archive"|"delete"}|null>(null);
  const load = useCallback(async () => { try { const date = today(); const [exerciseRows, templateRows, archivedRows, plannedRows, sessionRows] = await Promise.all([searchExercises(supabase), getWorkoutTemplates(supabase), getWorkoutTemplates(supabase,true), getPlannedWorkouts(supabase, date, `${date.slice(0, 8)}31`), getWorkoutSessions(supabase, "2025-01-01", date)]); setExercises(exerciseRows); setTemplates(templateRows); setArchivedTemplates(archivedRows); setPlanned(plannedRows); setSessions(sessionRows); } catch { setError("We couldn’t load your workouts."); } }, []);
  useEffect(() => { const timer = setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  useEffect(() => { const showLibrary = () => { if (window.location.hash === "#exercise-library") setTab("exercises"); }; showLibrary(); window.addEventListener("hashchange", showLibrary); return () => window.removeEventListener("hashchange", showLibrary); }, []);
  async function schedule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!showSchedule) return; setBusy(true); const data = new FormData(event.currentTarget); try { await scheduleWorkout(supabase, showSchedule.id, String(data.get("date")), String(data.get("time")) || null); setShowSchedule(null); setTab("planned"); await load(); } catch { setError("We couldn’t schedule this workout."); } finally { setBusy(false); } }
  async function start(workout: PlannedWorkout) { setBusy(true); try { const session = await startWorkoutSession(supabase, workout.id, today()); router.push(`/workouts/sessions/${session.id}`); } catch { setError("We couldn’t start the workout."); setBusy(false); } }
  async function manage(template:WorkoutTemplate,action:"archive"|"restore"|"delete"|"duplicate"){setBusy(true);setError("");try{if(action==="archive")await archiveWorkoutTemplate(supabase,template.id);if(action==="restore")await archiveWorkoutTemplate(supabase,template.id,false);if(action==="duplicate")await duplicateWorkoutTemplate(supabase,template.id);if(action==="delete"){const deps=await getWorkoutTemplateDependencies(supabase,template.id);if(deps.planned_workouts+deps.protocols+deps.experiments>0){setError("This template is used by existing workouts, protocols, or experiments and cannot be permanently deleted. You can keep it archived instead.");return}await deleteWorkoutTemplate(supabase,template.id)}setConfirm(null);await load();}catch{setError(`We couldn’t ${action} this template.`)}finally{setBusy(false)}}
  return <div className="mx-auto max-w-6xl px-4 py-6 md:px-6 md:py-10">
    <section className="rounded-3xl bg-slate-950 p-6 text-white md:p-8"><p className="text-sm font-black uppercase tracking-widest text-emerald-300">Training</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-black">Workouts</h1><p className="mt-2 text-slate-300">Plan sessions, execute sets, and preserve actual performance.</p></div><div className="flex gap-2"><Link href="/workouts/templates/new" className="rounded-full bg-emerald-500 px-4 py-3 font-black">Build Workout</Link><Link href="/workouts/progress" className="rounded-full bg-white/10 px-4 py-3 font-black">Progress</Link></div></div></section>
    <div className="mt-5 flex gap-2 overflow-x-auto">{(["planned", "templates", "exercises", "history"] as const).map((value) => <button key={value} onClick={() => setTab(value)} className={`min-h-11 rounded-full px-5 font-black capitalize ${tab === value ? "bg-slate-950 text-white" : "bg-white"}`}>{value}</button>)}</div>
    {error ? <p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</p> : null}
    {tab === "planned" ? <div className="mt-5 grid gap-4 md:grid-cols-2">{planned.map((workout) => <article key={workout.id} className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase text-emerald-600">{workout.scheduled_date} · {workout.status}</p><h2 className="mt-2 text-2xl font-black">{workout.name}</h2><div className="mt-4 flex gap-2"><Link href={`/workouts/planned/${workout.id}`} className="rounded-full bg-slate-100 px-4 py-3 font-black">View Plan</Link>{workout.status === "in_progress" ? <Link href={`/workouts/sessions/${sessions.find((session) => session.planned_workout_id === workout.id && session.status === "in_progress")?.id}`} className="rounded-full bg-amber-400 px-4 py-3 font-black">Resume</Link> : workout.status === "planned" ? <button disabled={busy} onClick={() => void start(workout)} className="rounded-full bg-emerald-500 px-4 py-3 font-black text-white">Start Workout</button> : null}</div></article>)}{!planned.length ? <p className="rounded-3xl border border-dashed bg-white p-8 text-center text-slate-500 md:col-span-2">No workouts planned this month. Schedule one from a template.</p> : null}</div> : null}
    {tab === "templates" ? <section className="mt-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{showArchived?"Archived templates":"Active templates"}</h2><button onClick={()=>setShowArchived(v=>!v)} className="min-h-11 rounded-full border bg-white px-4 font-bold">{showArchived?"Show active":`Archived (${archivedTemplates.length})`}</button></div><div className="mt-3 grid gap-4 md:grid-cols-2">{(showArchived?archivedTemplates:templates).map((template) => {const exerciseCount=template.groups?.reduce((n,g)=>n+(g.exercises?.length??0),0)??0;const setCount=template.groups?.reduce((n,g)=>n+(g.exercises?.reduce((m,e)=>m+(e.sets?.length??0),0)??0),0)??0;return <article key={template.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-2"><h3 className="text-2xl font-black">{template.name}</h3><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{template.is_archived?"Archived":"Active"}</span></div><p className="mt-2 text-sm text-slate-500">{exerciseCount} exercises · {setCount} sets · {template.estimated_duration_minutes??"—"} minutes</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/workouts/templates/${template.id}`} className="min-h-11 rounded-full bg-slate-950 px-4 py-3 font-black text-white">View</Link>{template.is_archived?<><button onClick={()=>void manage(template,"restore")} className="min-h-11 rounded-full bg-emerald-100 px-4 font-black text-emerald-800">Restore</button><button onClick={()=>setConfirm({template,action:"delete"})} className="min-h-11 rounded-full px-4 font-black text-red-700">Delete permanently</button></>:<><button onClick={()=>setShowSchedule(template)} className="min-h-11 rounded-full bg-emerald-100 px-4 font-black text-emerald-800">Schedule</button><details className="relative"><summary aria-label={`More actions for ${template.name}`} className="flex min-h-11 cursor-pointer list-none items-center rounded-full border px-4 font-black">More</summary><div className="absolute right-0 z-10 mt-1 grid min-w-48 rounded-xl border bg-white p-2 shadow-lg"><Link href={`/workouts/templates/${template.id}/edit`} className="min-h-11 rounded-lg px-3 py-3 font-semibold">Edit template</Link><button onClick={()=>void manage(template,"duplicate")} className="min-h-11 rounded-lg px-3 text-left font-semibold">Duplicate</button><button onClick={()=>setConfirm({template,action:"archive"})} className="min-h-11 rounded-lg px-3 text-left font-semibold text-amber-800">Archive</button></div></details></>}</div></article>})}</div></section> : null}
    {tab === "exercises" ? <><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={() => setShowExercise(true)} className="min-h-12 rounded-full bg-emerald-500 px-5 font-black text-white">Create Custom Exercise</button><ExerciseSelector onSelect={() => undefined}/></div><div className="mt-4 grid gap-3 md:grid-cols-2">{exercises.map((exercise) => <article key={exercise.id} className="rounded-2xl bg-white p-4"><h2 className="font-black">{exercise.name}</h2><p className="mt-1 text-sm font-semibold text-slate-500">{[metadataLabel(exercise.category), exercise.primary_muscle_group && metadataLabel(exercise.primary_muscle_group), exercise.equipment && metadataLabel(exercise.equipment), metadataLabel(exercise.default_tracking_type)].filter(Boolean).join(" · ")}</p>{exercise.user_id ? <button onClick={() => void archiveExercise(supabase, exercise.id).then(load)} className="mt-3 text-sm font-black text-amber-700">Archive</button> : <p className="mt-2 text-xs font-bold text-slate-400">Shared library</p>}</article>)}</div></> : null}
    {tab === "history" ? <div className="mt-5 space-y-3">{sessions.filter((session) => session.status !== "in_progress").map((session) => { const metrics = calculateWorkoutSessionMetrics(session); return <Link key={session.id} href={`/workouts/sessions/${session.id}/summary`} className="block rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{session.name}</h2><p className="mt-2 font-semibold text-slate-500">{session.session_date} · {session.status} · {metrics.completedSetCount} sets · {metrics.totalRepetitions} reps · {metrics.totalExternalLoadVolume.toLocaleString()} volume</p></Link>; })}</div> : null}
    {showExercise ? <div className="fixed inset-0 z-[70] flex items-end bg-slate-950/50 sm:items-center sm:justify-center"><div className="w-full rounded-t-3xl bg-white sm:max-w-2xl sm:rounded-3xl"><CustomExerciseForm onCancel={() => setShowExercise(false)} onCreated={(exercise) => { setExercises((items) => [...items, exercise].sort((a, b) => a.name.localeCompare(b.name))); setShowExercise(false); setError(""); }}/></div></div> : null}
    {showSchedule ? <div className="fixed inset-0 z-[70] flex items-end bg-slate-950/50 sm:items-center sm:justify-center"><form onSubmit={schedule} className="w-full rounded-t-3xl bg-white p-5 sm:max-w-md sm:rounded-3xl"><h2 className="text-2xl font-black">Schedule {showSchedule.name}</h2><label className="mt-5 block font-bold">Date<input name="date" type="date" required defaultValue={today()} className="mt-2 min-h-12 w-full rounded-2xl border px-4"/></label><label className="mt-4 block font-bold">Time<input name="time" type="time" className="mt-2 min-h-12 w-full rounded-2xl border px-4"/></label><button disabled={busy} className="mt-5 min-h-12 w-full rounded-full bg-emerald-500 font-black text-white">{busy ? "Scheduling…" : "Schedule Workout"}</button></form></div> : null}
    {confirm?<div role="presentation" className="fixed inset-0 z-[80] grid place-items-end bg-slate-950/50 p-0 sm:place-items-center sm:p-4"><div role="dialog" aria-modal="true" aria-labelledby="template-confirm-title" className="w-full rounded-t-3xl bg-white p-5 sm:max-w-md sm:rounded-3xl"><h2 id="template-confirm-title" className="text-2xl font-black">{confirm.action==="archive"?`Archive ${confirm.template.name}?`:`Delete ${confirm.template.name} permanently?`}</h2><p className="mt-3 text-slate-600">{confirm.action==="archive"?"You won’t see this template when planning new workouts, but existing workout history will remain available.":"This action cannot be undone. Deletion will be blocked if the template has workout, protocol, or experiment history."}</p><div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button autoFocus onClick={()=>setConfirm(null)} className="min-h-11 rounded-full border px-4 font-bold">Cancel</button><button disabled={busy} onClick={()=>void manage(confirm.template,confirm.action)} className={`min-h-11 rounded-full px-4 font-bold ${confirm.action==="delete"?"bg-red-700 text-white":"bg-amber-100 text-amber-900"}`}>{busy?"Working…":confirm.action==="delete"?"Delete permanently":"Archive template"}</button></div></div></div>:null}
  </div>;
}
