import { featureRegistry, generateFeatureVector } from "./features.ts";
import { CONTROL_SPACING_HOURS, EPISODE_SIMILARITY_VERSION, MAX_CONTROLS_PER_POSITIVE, MIN_SHARED_COVERAGE, MIN_VECTOR_COMPLETENESS, OUTLOOK_HOURS, PERFORMANCE_MIN_POSITIVES, PERFORMANCE_MIN_WINDOWS, type BacktestMetrics, type ConditionOutlook, type FeatureKey, type FeatureVector, type HistoricalVector, type OutlookClassification, type OutlookFactor, type OutlookInput, type Readiness } from "./types.ts";

const HOUR=3600000,mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:null,round=(x:number,d=3)=>Number(x.toFixed(d));
const percentile=(xs:number[],p:number)=>{if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y),i=(a.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return a[l]+(a[h]-a[l])*(i-l)};
const overlap=(a:{windowStartAt:string;windowEndAt:string},b:{windowStartAt:string;windowEndAt:string})=>a.windowStartAt<b.windowEndAt&&b.windowStartAt<a.windowEndAt;
export function historicalVectors(input:OutlookInput,predictionAt=input.predictionAt){
 const cutoff=new Date(predictionAt).getTime(),episodes=input.episodes.filter(e=>new Date(e.started_at).getTime()<=cutoff).sort((a,b)=>a.started_at.localeCompare(b.started_at));
 const positives:HistoricalVector[]=episodes.map(e=>({kind:"positive" as const,episodeId:e.id,vector:generateFeatureVector(input.days,e.started_at)})).filter(x=>x.vector.featureCompleteness>=MIN_VECTOR_COMPLETENESS);
 if(!episodes.length)return{positives,negatives:[] as HistoricalVector[]};
 const positiveWindows=episodes.map(e=>generateFeatureVector([],e.started_at)),active=episodes.map(e=>({start:new Date(e.started_at).getTime(),end:e.ended_at?new Date(e.ended_at).getTime():new Date(e.started_at).getTime()+OUTLOOK_HOURS*HOUR}));
 const first=Math.min(...input.days.map(d=>new Date(d.at).getTime()),cutoff),limit=positives.length*MAX_CONTROLS_PER_POSITIVE,negatives:HistoricalVector[]=[];
 for(let end=first+OUTLOOK_HOURS*HOUR;end<=cutoff&&negatives.length<limit;end+=CONTROL_SPACING_HOURS*HOUR){const vector=generateFeatureVector(input.days,new Date(end).toISOString()),follow=end+OUTLOOK_HOURS*HOUR;if(episodes.some(e=>{const onset=new Date(e.started_at).getTime();return onset>=end&&onset<follow})||positiveWindows.some(w=>overlap(vector,w))||active.some(a=>end>a.start&&new Date(vector.windowStartAt).getTime()<a.end)||vector.featureCompleteness<MIN_VECTOR_COMPLETENESS)continue;negatives.push({kind:"negative",episodeId:null,vector})}
 return{positives,negatives};
}
type Stats=Record<FeatureKey,{mean:number;sd:number}>;
export function normalizationStats(vectors:HistoricalVector[]):Stats{const out={} as Stats;for(const f of featureRegistry){const xs=vectors.map(v=>v.vector.values[f.key]).filter((x):x is number=>typeof x==="number");const m=mean(xs)??0,variance=mean(xs.map(x=>(x-m)**2))??0;out[f.key]={mean:m,sd:Math.sqrt(variance)}}return out}
const normalized=(v:number,key:FeatureKey,stats:Stats)=>{const f=featureRegistry.find(x=>x.key===key)!;return f.normalization==="binary"?v:(stats[key].sd?((v-stats[key].mean)/stats[key].sd):0)};
export function vectorSimilarity(a:FeatureVector,b:FeatureVector,stats:Stats){const shared=featureRegistry.filter(f=>a.values[f.key]!=null&&b.values[f.key]!=null),coverage=shared.length/featureRegistry.length;if(coverage<MIN_SHARED_COVERAGE)return null;const categories=[...new Set(shared.map(x=>x.category))],dist=categories.reduce((sum,category)=>{const fs=shared.filter(x=>x.category===category),categoryDistance=fs.reduce((n,f)=>n+(normalized(a.values[f.key]!,f.key,stats)-normalized(b.values[f.key]!,f.key,stats))**2,0)/fs.length;return sum+categoryDistance/categories.length},0);return{similarity:1/(1+Math.sqrt(dist)),coverage}}
export function readiness(totalEpisodes:number,positives:HistoricalVector[],negatives:HistoricalVector[]):Readiness{const completeness=mean(positives.map(x=>x.vector.featureCompleteness))??0,features=new Set(positives.flatMap(x=>featureRegistry.filter(f=>x.vector.values[f.key]!=null).map(f=>f.key))).size;let level:Readiness["level"]=positives.length<3?"not_ready":positives.length<5?"experimental":positives.length<10?"exploratory":"established_history";if(completeness<.6&&level!=="not_ready")level=positives.length<5?"not_ready":level==="established_history"?"exploratory":"experimental";return{level,totalEpisodes,usablePositiveWindows:positives.length,negativeWindows:negatives.length,featureCompleteness:round(completeness),usableFeatures:features,historyDays:0}}
export function classify(pos:number,neg:number,negativeScores:number[],positiveScores:number[],coverage:number):OutlookClassification{if(coverage<MIN_SHARED_COVERAGE)return"unavailable";const delta=pos-neg,n75=percentile(negativeScores,.75)??.55,p75=percentile(positiveScores,.75)??.7;if(delta<=0&&pos<(percentile(negativeScores,.5)??.5))return"low_similarity";if(delta<=0||pos<n75)return"typical";if(pos>=p75&&delta>=.08)return"high_similarity";return"elevated_similarity"}
function factors(current:FeatureVector,positives:HistoricalVector[],negatives:HistoricalVector[]):OutlookFactor[]{const result:OutlookFactor[]=[];for(const f of featureRegistry){const c=current.values[f.key],p=mean(positives.map(x=>x.vector.values[f.key]).filter((x):x is number=>typeof x==="number")),n=mean(negatives.map(x=>x.vector.values[f.key]).filter((x):x is number=>typeof x==="number"));if(c==null||p==null||n==null)continue;const range=Math.max(Math.abs(p-n),1),alignment=Math.abs(c-n)/range;if((c-p)*(p-n)<=0&&alignment>=.5)result.push({key:f.key,label:f.label,category:f.category,currentValue:round(c,1),baselineValue:round(n,1),positiveMean:round(p,1),negativeMean:round(n,1),summary:`Currently ${c<n?"below":"above"} your usual historical periods and resembles previous pre-episode patterns.`})}return result.sort((a,b)=>Math.abs(b.currentValue-b.negativeMean)-Math.abs(a.currentValue-a.negativeMean)).slice(0,4)}
export function buildOutlook(input:OutlookInput):ConditionOutlook{const history=historicalVectors(input),ready=readiness(input.episodes.length,history.positives,history.negatives),current=generateFeatureVector(input.days,input.predictionAt),base={userConditionId:input.userConditionId,conditionLabel:input.conditionLabel,episodeLabel:input.episodeLabel,generatedAt:input.predictionAt,predictionHorizonHours:OUTLOOK_HOURS,analysisVersion:EPISODE_SIMILARITY_VERSION,readiness:ready,featureCoverage:current.featureCompleteness,positiveWindowsUsed:history.positives.length,negativeWindowsUsed:history.negatives.length,performance:null};if(ready.level==="not_ready"||!history.negatives.length)return{...base,classification:"unavailable",positiveSimilarity:null,negativeSimilarity:null,similarityDelta:null,contributingFactors:[],nearestEpisodes:[],limitations:["At least 3 usable episode windows and comparison history are required.","This is based only on your recorded history."]};const stats=normalizationStats([...history.positives,...history.negatives]),score=(v:HistoricalVector)=>vectorSimilarity(current,v.vector,stats),pm=history.positives.map(v=>({v,s:score(v),onset:input.episodes.find(e=>e.id===v.episodeId)?.started_at??""})).filter(x=>x.s),nm=history.negatives.map(v=>score(v)).filter((x):x is NonNullable<typeof x>=>Boolean(x));if(!pm.length||!nm.length)return{...base,classification:"unavailable",positiveSimilarity:null,negativeSimilarity:null,similarityDelta:null,contributingFactors:[],nearestEpisodes:[],limitations:["Not enough shared recent features to compare this period reliably."]};const nearest=[...pm].sort((a,b)=>b.s!.similarity-a.s!.similarity),pos=mean(nearest.slice(0,3).map(x=>x.s!.similarity))!,neg=mean(nm.map(x=>x.similarity))!,positiveScores=pm.map(x=>x.s!.similarity),negativeScores=nm.map(x=>x.similarity),coverage=mean([...pm.map(x=>x.s!.coverage),...nm.map(x=>x.coverage)])!,classification=classify(pos,neg,negativeScores,positiveScores,coverage);return{...base,classification,positiveSimilarity:round(pos),negativeSimilarity:round(neg),similarityDelta:round(pos-neg),featureCoverage:round(coverage),contributingFactors:factors(current,history.positives,history.negatives),nearestEpisodes:nearest.slice(0,3).map(x=>({episodeId:x.v.episodeId!,onsetAt:x.onset,similarity:round(x.s!.similarity),label:x.s!.similarity>=.75?"High similarity":x.s!.similarity>=.55?"Moderate similarity":"Some similarity"})),limitations:["This does not mean an episode will occur.","Similarity is not a probability or medical assessment.","This is based only on your recorded history."]}}
export function backtestMetrics(outcomes:Array<{classification:OutlookClassification;episodeFollowed:boolean}>):BacktestMetrics{const positive=(x:OutlookClassification)=>x==="elevated_similarity"||x==="high_similarity",tp=outcomes.filter(x=>positive(x.classification)&&x.episodeFollowed).length,fp=outcomes.filter(x=>positive(x.classification)&&!x.episodeFollowed).length,tn=outcomes.filter(x=>!positive(x.classification)&&!x.episodeFollowed).length,fn=outcomes.filter(x=>!positive(x.classification)&&x.episodeFollowed).length,ratio=(a:number,b:number)=>b?round(a/b):null,pos=tp+fn;return{evaluatedWindows:outcomes.length,positiveOutcomes:pos,truePositives:tp,falsePositives:fp,trueNegatives:tn,falseNegatives:fn,sensitivity:ratio(tp,tp+fn),specificity:ratio(tn,tn+fp),precision:ratio(tp,tp+fp),recall:ratio(tp,tp+fn),falsePositiveRate:ratio(fp,fp+tn),falseNegativeRate:ratio(fn,fn+tp),displayable:pos>=PERFORMANCE_MIN_POSITIVES&&outcomes.length>=PERFORMANCE_MIN_WINDOWS}}
export function rollingBacktest(input:OutlookInput){const times=input.days.map(x=>new Date(x.at).getTime());if(!times.length)return{outcomes:[],metrics:backtestMetrics([])};const earliest=Math.min(...times),end=new Date(input.predictionAt).getTime(),outcomes:Array<{predictionAt:string;classification:OutlookClassification;episodeFollowed:boolean}>=[];for(let at=earliest+OUTLOOK_HOURS*HOUR;at+OUTLOOK_HOURS*HOUR<=end;at+=CONTROL_SPACING_HOURS*HOUR){const predictionAt=new Date(at).toISOString(),result=buildOutlook({...input,predictionAt,episodes:input.episodes.filter(e=>new Date(e.started_at).getTime()<=at),days:input.days.filter(d=>new Date(d.at).getTime()<=at)});if(result.classification==="unavailable")continue;outcomes.push({predictionAt,classification:result.classification,episodeFollowed:input.episodes.some(e=>{const onset=new Date(e.started_at).getTime();return onset>at&&onset<=at+OUTLOOK_HOURS*HOUR})})}return{outcomes,metrics:backtestMetrics(outcomes)}}
