/* eslint-disable @typescript-eslint/no-explicit-any */
import type { SupabaseClient } from "@supabase/supabase-js";
import type { ExposureDay } from "../trigger-analysis/types.ts";
import { buildOutlook } from "./engine.ts";
const blank=(at:string):ExposureDay=>({date:at.slice(0,10),at,sleepQuality:null,energy:null,mood:null,alcohol:null,calories:null,protein:null,caffeine:null,alcoholGrams:null,workoutCount:0,workoutMinutes:0,workoutVolume:0,habitCompleted:0,habitScheduled:0,protocolCompleted:0,protocolScheduled:0,symptomCount:0});
export async function buildConditionOutlook(client:SupabaseClient,{userConditionId,now=new Date()}:{userConditionId:string;timeZone:string;now?:Date}){
 const{data:auth,error:authError}=await client.auth.getUser();if(authError||!auth.user)throw new Error("AUTH_REQUIRED");const user=auth.user.id;
 const{data:condition,error:conditionError}=await client.from("user_conditions").select("id,custom_condition_name,condition:conditions(name,preferred_episode_label)").eq("id",userConditionId).eq("user_id",user).single();if(conditionError)throw new Error("CONDITION_NOT_FOUND");
 const cutoff=new Date(now.getTime()-730*86400000).toISOString(),{data:episodes,error:episodeError}=await client.from("condition_episodes").select("id,started_at,ended_at").eq("user_id",user).eq("user_condition_id",userConditionId).is("archived_at",null).gte("started_at",cutoff).lte("started_at",now.toISOString()).order("started_at");if(episodeError)throw episodeError;
 const first=(episodes??[])[0]?.started_at??now.toISOString(),start=new Date(new Date(first).getTime()-90*86400000).toISOString(),end=now.toISOString();
 const queries=[client.from("daily_checkins").select("checkin_date,energy_score,mood_score,sleep_quality,alcohol,updated_at").eq("user_id",user).gte("checkin_date",start.slice(0,10)).lte("updated_at",end),client.from("nutrition_entries").select("consumed_at,items:nutrition_entry_items(calories,protein_grams,caffeine_mg,alcohol_grams)").eq("user_id",user).is("deleted_at",null).gte("consumed_at",start).lt("consumed_at",end),client.from("workout_sessions").select("started_at,duration_seconds,sets:workout_session_sets(status,actual_reps,actual_weight)").eq("user_id",user).eq("status","completed").gte("started_at",start).lt("started_at",end),client.from("planned_activity_occurrences").select("scheduled_date,status,updated_at,planned_activity:planned_activities(activity_type,user_protocol_id)").eq("user_id",user).gte("updated_at",start).lt("updated_at",end),client.from("user_symptom_events").select("started_at").eq("user_id",user).is("deleted_at",null).gte("started_at",start).lt("started_at",end)];
 const settled=await Promise.allSettled(queries),failed:string[]=[],rows=settled.map((r,i)=>{if(r.status==="rejected"||r.value.error){failed.push(["check-ins","nutrition","workouts","routines","symptoms"][i]);return[]}return r.value.data??[]}),map=new Map<string,ExposureDay>(),day=(at:string)=>{const key=at.slice(0,10),found=map.get(key);if(found)return found;const d=blank(at);map.set(key,d);return d};
 for(const x of rows[0]as any[]){const d=day(x.updated_at??`${x.checkin_date}T12:00:00Z`),quality:{[key:string]:number}={Poor:1,Average:2,Fair:2,Good:3,Great:4,Excellent:4};d.energy=x.energy_score;d.mood=x.mood_score;d.sleepQuality=typeof x.sleep_quality==="number"?x.sleep_quality:quality[x.sleep_quality]??null;d.alcohol=x.alcohol}
 for(const x of rows[1]as any[]){const d=day(x.consumed_at),total=(k:string)=>(x.items??[]).reduce((n:number,v:any)=>n+Number(v[k]??0),0);d.calories=(d.calories??0)+total("calories");d.protein=(d.protein??0)+total("protein_grams");d.caffeine=(d.caffeine??0)+total("caffeine_mg")}
 for(const x of rows[2]as any[]){const d=day(x.started_at);d.workoutCount++;d.workoutMinutes+=Number(x.duration_seconds??0)/60;d.workoutVolume+=(x.sets??[]).filter((s:any)=>s.status==="completed").reduce((n:number,s:any)=>n+Number(s.actual_reps??0)*Number(s.actual_weight??0),0)}
 for(const x of rows[3]as any[]){const d=day(x.updated_at),a=x.planned_activity;if(a?.user_protocol_id){d.protocolScheduled++;if(x.status==="completed")d.protocolCompleted++}else if(a?.activity_type==="habit"){d.habitScheduled++;if(x.status==="completed")d.habitCompleted++}}
 for(const x of rows[4]as any[])day(x.started_at).symptomCount++;
 const c=condition as unknown as{custom_condition_name:string|null;condition?:{name:string;preferred_episode_label:string|null}|null},result=buildOutlook({userConditionId,conditionLabel:c.condition?.name??c.custom_condition_name??"Condition",episodeLabel:c.condition?.preferred_episode_label??"Episode",predictionAt:end,episodes:episodes??[],days:[...map.values()].sort((a,b)=>a.at.localeCompare(b.at))});return{...result,limitations:[...result.limitations,...(failed.length?["Some tracked data sources were unavailable."]:[])]}
}
