"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityForm } from "@/components/planner/ActivityForm";
import { addCalendarDays } from "@/lib/planner/recurrence";
import { createPlannedActivity, deletePlannedActivity, updatePlannedActivity } from "@/lib/planner/planner";
import { getHabitOccurrencesForRange, getHabits, setHabitActive } from "@/lib/habits/habits";
import { calculateAdherence } from "@/lib/habits/analytics";
import { calculateBestStreak, calculateCurrentStreak } from "@/lib/habits/streaks";
import type { CreatePlannedActivityInput, PlannedActivity, PlannedActivityOccurrence } from "@/lib/planner/types";
import { supabase } from "@/lib/supabase/client";
import { logDevError } from "@/lib/app-errors";

function todayString() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }
function weekStart(today: string) { const d = new Date(`${today}T12:00:00`); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; }

export function HabitsDashboard() {
  const today = todayString(); const historyStart = addCalendarDays(today, -364); const monthStart = today.slice(0, 8) + "01";
  const [filter, setFilter] = useState<"active" | "paused" | "all">("active"); const [sort, setSort] = useState("custom"); const [habits, setHabits] = useState<PlannedActivity[]>([]); const [rows, setRows] = useState<PlannedActivityOccurrence[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [editing, setEditing] = useState<PlannedActivity | null>(null); const [formOpen, setFormOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [items, occurrences] = await Promise.all([getHabits(supabase, filter), getHabitOccurrencesForRange(supabase, historyStart, today)]); setHabits(items); setRows(occurrences); } catch (reason) { logDevError("Failed to load habits", reason); setError("We couldn’t load your habits."); } finally { setLoading(false); } }, [filter, historyStart, today]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => clearTimeout(timer); }, [load]);
  const metrics = useMemo(() => new Map(habits.map((habit) => { const own = rows.filter((row) => row.planned_activity_id === habit.id); return [habit.id, { current: calculateCurrentStreak(own, today), best: calculateBestStreak(own, today), week: calculateAdherence(own, weekStart(today), today).percentage, month: calculateAdherence(own, monthStart, today).percentage, today: own.find((row) => row.scheduled_date === today) }]; })), [habits, monthStart, rows, today]);
  const sorted = useMemo(() => [...habits].sort((a, b) => { const am = metrics.get(a.id)!; const bm = metrics.get(b.id)!; if (sort === "time") return (a.scheduled_time ?? "99:99").localeCompare(b.scheduled_time ?? "99:99"); if (sort === "streak") return bm.current - am.current; if (sort === "adherence") return am.week - bm.week; if (sort === "alpha") return a.title.localeCompare(b.title); return (a.sort_order ?? 9999) - (b.sort_order ?? 9999) || a.title.localeCompare(b.title); }), [habits, metrics, sort]);
  async function save(input: CreatePlannedActivityInput) { setBusy("save"); try { const values = { ...input, activity_type: "habit" as const }; if (editing) await updatePlannedActivity(supabase, editing.id, values, today); else await createPlannedActivity(supabase, values); setMessage(editing ? "Habit updated." : "Habit created."); setFormOpen(false); setEditing(null); await load(); } catch (reason) { logDevError("Failed to save habit", reason); setError("We couldn’t save this habit."); } finally { setBusy(null); } }
  async function toggle(habit: PlannedActivity) { setBusy(habit.id); try { await setHabitActive(supabase, habit.id, !habit.is_active, today); setMessage(habit.is_active ? "Habit paused." : "Habit reactivated from today."); await load(); } catch (reason) { logDevError("Failed to change habit state", reason); setError("We couldn’t update this habit."); } finally { setBusy(null); } }
  async function remove(habit: PlannedActivity) { if (!confirm("Delete this habit and all of its history? This cannot be undone.")) return; setBusy(habit.id); try { await deletePlannedActivity(supabase, habit.id); setMessage("Habit deleted."); await load(); } catch (reason) { logDevError("Failed to delete habit", reason); setError("We couldn’t delete this habit."); } finally { setBusy(null); } }
  return <div className="mx-auto max-w-6xl px-4 py-6 md:px-6 md:py-10"><section className="rounded-3xl bg-slate-950 p-6 text-white md:p-8"><p className="text-sm font-black uppercase tracking-widest text-emerald-300">Consistency</p><div className="mt-3 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-black">Habits</h1><p className="mt-2 font-semibold text-slate-300">Build routines, log progress, and understand adherence.</p></div><button onClick={() => { setEditing(null); setFormOpen(true); }} className="min-h-12 rounded-full bg-emerald-500 px-6 font-black">Add Habit</button></div></section>
    <div className="mt-5 grid gap-3 sm:grid-cols-2"><fieldset className="flex rounded-2xl bg-white p-1 shadow-sm"><legend className="sr-only">Filter habits</legend>{(["active", "paused", "all"] as const).map((value) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)} className={`min-h-11 flex-1 rounded-xl text-sm font-black capitalize ${filter === value ? "bg-slate-950 text-white" : "text-slate-500"}`}>{value}</button>)}</fieldset><label className="sr-only" htmlFor="habit-sort">Sort habits</label><select id="habit-sort" value={sort} onChange={(e) => setSort(e.target.value)} className="min-h-12 rounded-2xl border border-slate-200 bg-white px-4 font-bold"><option value="custom">Custom order</option><option value="time">Scheduled time</option><option value="streak">Highest streak</option><option value="adherence">Lowest adherence</option><option value="alpha">Alphabetical</option></select></div>
    {error ? <p role="alert" className="mt-4 rounded-2xl bg-rose-50 p-4 font-bold text-rose-700">{error}</p> : null}{message ? <p role="status" className="mt-4 rounded-2xl bg-emerald-50 p-4 font-bold text-emerald-800">{message}</p> : null}
    {loading ? <div className="mt-5 grid gap-4 md:grid-cols-2">{[1,2,3,4].map((n) => <div key={n} className="h-64 animate-pulse rounded-3xl bg-slate-200" />)}</div> : null}
    {!loading && !sorted.length ? <div className="mt-5 rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center"><h2 className="text-2xl font-black">No habits here yet.</h2><p className="mt-2 font-semibold text-slate-500">Add a habit or change the filter.</p></div> : null}
    <div className="mt-5 grid gap-4 md:grid-cols-2">{sorted.map((habit) => { const data = metrics.get(habit.id)!; return <article key={habit.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-widest text-emerald-600">{habit.is_active ? "Active" : "Paused"}</p><h2 className="mt-1 text-2xl font-black">{habit.title}</h2><p className="mt-1 font-semibold text-slate-500">{habit.tracking_type === "binary" ? "Yes / No" : `${habit.target_value} ${habit.target_unit}`}</p></div><span className="text-3xl" aria-hidden="true">{habit.habit_icon || "✓"}</span></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Current", `${data.current} days`],["Best", `${data.best} days`],["Week", `${data.week}%`],["Month", `${data.month}%`]].map(([label,value]) => <div key={label} className="rounded-2xl bg-slate-50 p-3"><p className="text-xs font-black text-slate-400">{label}</p><p className="mt-1 font-black">{value}</p></div>)}</div><p className="mt-4 text-sm font-bold capitalize text-slate-600">Today: {data.today?.status ?? "Not scheduled"}</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/habits/${habit.id}`} className="min-h-11 rounded-full bg-slate-950 px-4 py-3 text-sm font-black text-white">View details</Link><button disabled={busy === habit.id} onClick={() => { setEditing(habit); setFormOpen(true); }} className="min-h-11 rounded-full px-4 text-sm font-black">Edit</button><button disabled={busy === habit.id} onClick={() => void toggle(habit)} className="min-h-11 rounded-full px-4 text-sm font-black text-amber-700">{habit.is_active ? "Pause" : "Reactivate"}</button><button disabled={busy === habit.id} onClick={() => void remove(habit)} className="min-h-11 rounded-full px-4 text-sm font-black text-rose-600">Delete</button></div></article>; })}</div>
    {formOpen ? <ActivityForm key={editing?.id ?? "new"} activity={editing} initialDate={today} saving={busy === "save"} onCancel={() => { setFormOpen(false); setEditing(null); }} onSubmit={save} /> : null}</div>;
}
