import assert from "node:assert/strict";import test from"node:test";import{addDaysToDateString,differenceInCalendarDays,getProtocolDayNumber,getWeekdayFromDateString,isDateWithinPausePeriod,isDateWithinProtocol}from"./dates.ts";import{firstWeekdayOnOrAfter,translateProtocolSchedule}from"./scheduling.ts";import{calculateProtocolAdherence,calculateProtocolSummary}from"./analytics.ts";import type{ProtocolOccurrence,ProtocolPausePeriod,ProtocolTemplateActivityInput,UserProtocolActivity}from"./types";
const base:ProtocolTemplateActivityInput={title:"Test",description:null,activity_type:"habit",tracking_type:"binary",target_value:null,target_unit:null,minimum_value:null,allow_partial_completion:false,schedule_type:"daily",days_of_week:null,interval_days:null,day_offset:null,scheduled_time:null,sort_order:0,is_required:true};
const row=(date:string,status:"planned"|"completed"|"skipped",activity="a",actual:number|null=null)=>({scheduled_date:date,status,planned_activity_id:activity,actual_value:actual} as unknown as ProtocolOccurrence);const pause=(start:string,end:string|null)=>({paused_on:start,resumed_on:end}as ProtocolPausePeriod);const link=(activity:string,required:boolean)=>({planned_activity_id:activity,is_required:required}as UserProtocolActivity);
test("daily schedule translates",()=>assert.equal(translateProtocolSchedule(base,"2026-08-03","2026-09-01").recurrence_type,"daily"));
test("weekday schedule translates",()=>assert.equal(translateProtocolSchedule({...base,schedule_type:"weekdays"},"2026-08-03",null).recurrence_type,"weekdays"));
test("specific weekdays are retained",()=>assert.deepEqual(translateProtocolSchedule({...base,schedule_type:"specific_days",days_of_week:[1,3,5]},"2026-08-03",null).days_of_week,[1,3,5]));
test("weekly schedule finds first valid weekday",()=>assert.equal(translateProtocolSchedule({...base,schedule_type:"weekly",days_of_week:[3]},"2026-08-03",null).start_date,"2026-08-05"));
test("first weekday accepts start when matched",()=>assert.equal(firstWeekdayOnOrAfter("2026-08-03",1),"2026-08-03"));
test("interval retains interval days",()=>assert.equal(translateProtocolSchedule({...base,schedule_type:"interval",interval_days:3},"2026-08-03",null).interval_days,3));
test("day offset calculates exact date",()=>assert.equal(translateProtocolSchedule({...base,schedule_type:"day_offset",day_offset:6},"2026-08-03",null).start_date,"2026-08-09"));
test("day offset becomes one time",()=>assert.equal(translateProtocolSchedule({...base,schedule_type:"day_offset",day_offset:0},"2026-08-03",null).recurrence_type,"none"));
test("date addition crosses months without UTC shift",()=>assert.equal(addDaysToDateString("2026-08-31",1),"2026-09-01"));
test("weekday uses date-only UTC components",()=>assert.equal(getWeekdayFromDateString("2026-08-03"),1));
test("calendar difference is stable",()=>assert.equal(differenceInCalendarDays("2026-08-03","2026-08-09"),6));
test("protocol day one is start",()=>assert.equal(getProtocolDayNumber("2026-08-03","2026-08-03"),1));
test("protocol bounds include endpoints",()=>assert.equal(isDateWithinProtocol("2026-08-10","2026-08-03","2026-08-10"),true));
test("pause includes paused date and excludes resume date",()=>{assert.equal(isDateWithinPausePeriod("2026-08-05",pause("2026-08-05","2026-08-07")),true);assert.equal(isDateWithinPausePeriod("2026-08-07",pause("2026-08-05","2026-08-07")),false)});
test("paused dates are excluded from adherence",()=>assert.equal(calculateProtocolAdherence([row("2026-08-03","completed"),row("2026-08-04","planned")],[pause("2026-08-04","2026-08-05")],"2026-08-05").percentage,100));
test("future occurrences are excluded",()=>assert.equal(calculateProtocolAdherence([row("2026-08-03","completed"),row("2026-08-10","planned")],[],"2026-08-03").scheduled,1));
test("skipped stays in denominator",()=>assert.equal(calculateProtocolAdherence([row("2026-08-03","completed"),row("2026-08-04","skipped")],[],"2026-08-04").percentage,50));
test("required adherence excludes optional",()=>assert.equal(calculateProtocolSummary([row("2026-08-03","completed","a"),row("2026-08-03","planned","b")],[],"2026-08-03",[link("a",true),link("b",false)]).required.percentage,100));
test("optional adherence excludes required",()=>assert.equal(calculateProtocolSummary([row("2026-08-03","completed","a"),row("2026-08-03","planned","b")],[],"2026-08-03",[link("a",true),link("b",false)]).optional.percentage,0));
test("partial progress is counted separately",()=>assert.equal(calculateProtocolAdherence([row("2026-08-03","planned","a",5)],[],"2026-08-03").partial,1));
test("empty protocol data is safe",()=>assert.deepEqual(calculateProtocolAdherence([],[],"2026-08-03"),{scheduled:0,completed:0,skipped:0,missed:0,partial:0,percentage:0}));
