import type { SupabaseClient } from "@supabase/supabase-js"; import type { ProtocolTemplate, ProtocolTemplateActivity, ProtocolTemplateInput } from "./types";
async function uid(client:SupabaseClient){ const {data,error}=await client.auth.getUser(); if(error||!data.user) throw new Error("AUTH_REQUIRED"); return data.user.id; }
export async function getProtocolTemplates(client:SupabaseClient,archived=false){ const user=await uid(client); const {data,error}=await client.from("protocol_templates").select("*,activities:protocol_template_activities(*)").eq("user_id",user).eq("is_archived",archived).order("created_at",{ascending:false}).order("sort_order",{referencedTable:"protocol_template_activities"}); if(error) throw error; return (data??[]) as ProtocolTemplate[]; }
export async function getProtocolTemplateById(client:SupabaseClient,id:string){ const user=await uid(client); const {data,error}=await client.from("protocol_templates").select("*,activities:protocol_template_activities(*)").eq("id",id).eq("user_id",user).order("sort_order",{referencedTable:"protocol_template_activities"}).single(); if(error) throw error; return data as ProtocolTemplate; }
export async function createProtocolTemplate(client:SupabaseClient,input:ProtocolTemplateInput){ const user=await uid(client); const {activities,...template}=input; const {data,error}=await client.from("protocol_templates").insert({...template,user_id:user}).select("*").single(); if(error) throw error; try { if(activities.length){ const {error:activityError}=await client.from("protocol_template_activities").insert(activities.map((a,i)=>({...a,user_id:user,protocol_template_id:data.id,sort_order:a.sort_order??i}))); if(activityError) throw activityError; } return getProtocolTemplateById(client,data.id); } catch(reason){ await client.from("protocol_templates").delete().eq("id",data.id).eq("user_id",user); throw reason; } }
export async function updateProtocolTemplate(client:SupabaseClient,id:string,input:ProtocolTemplateInput){ const user=await uid(client); const {activities,...template}=input; const {error}=await client.from("protocol_templates").update(template).eq("id",id).eq("user_id",user); if(error) throw error; const {error:removeError}=await client.from("protocol_template_activities").delete().eq("protocol_template_id",id).eq("user_id",user); if(removeError) throw removeError; if(activities.length){ const {error:insertError}=await client.from("protocol_template_activities").insert(activities.map((a,i)=>({...a,user_id:user,protocol_template_id:id,sort_order:a.sort_order??i}))); if(insertError) throw insertError; } return getProtocolTemplateById(client,id); }
export async function deleteProtocolTemplate(client:SupabaseClient,id:string){ const user=await uid(client); const {error}=await client.from("protocol_templates").delete().eq("id",id).eq("user_id",user); if(error) throw error; }
export async function archiveProtocolTemplate(client:SupabaseClient,id:string,archived:boolean){ const user=await uid(client); const {error}=await client.from("protocol_templates").update({is_archived:archived,is_active:!archived}).eq("id",id).eq("user_id",user); if(error) throw error; }
export async function duplicateProtocolTemplate(client:SupabaseClient,id:string){ const source=await getProtocolTemplateById(client,id); return createProtocolTemplate(client,{name:`${source.name} Copy`,description:source.description,goal:source.goal,duration_days:source.duration_days,category:source.category,difficulty:source.difficulty,activities:(source.activities??[]).map(({title,description,activity_type,tracking_type,target_value,target_unit,minimum_value,allow_partial_completion,schedule_type,days_of_week,interval_days,day_offset,scheduled_time,sort_order,is_required})=>({title,description,activity_type,tracking_type,target_value,target_unit,minimum_value,allow_partial_completion,schedule_type,days_of_week,interval_days,day_offset,scheduled_time,sort_order,is_required}))}); }
export function templateActivityInputs(rows:ProtocolTemplateActivity[]):ProtocolTemplateInput["activities"]{ return rows.map(({title,description,activity_type,tracking_type,target_value,target_unit,minimum_value,allow_partial_completion,schedule_type,days_of_week,interval_days,day_offset,scheduled_time,sort_order,is_required})=>({title,description,activity_type,tracking_type,target_value,target_unit,minimum_value,allow_partial_completion,schedule_type,days_of_week,interval_days,day_offset,scheduled_time,sort_order,is_required})); }
