-- Idempotent shared library. The partial unique index prevents duplicate shared names.
insert into public.exercises (user_id, name, normalized_name, aliases, category, movement_pattern, primary_muscle_group, equipment, default_tracking_type)
values
(null,'Back Squat','backsquat',array['barbell squat'],'strength','squat','quadriceps','barbell','weight_reps'),
(null,'Front Squat','frontsquat',array['front rack squat'],'strength','squat','quadriceps','barbell','weight_reps'),
(null,'Goblet Squat','gobletsquat',array['kettlebell squat','dumbbell squat'],'strength','squat','quadriceps','kettlebell','weight_reps'),
(null,'Romanian Deadlift','romaniandeadlift',array['rdl'],'strength','hinge','hamstrings','barbell','weight_reps'),
(null,'Conventional Deadlift','conventionaldeadlift',array['deadlift'],'strength','hinge','hamstrings','barbell','weight_reps'),
(null,'Hip Thrust','hipthrust',array['barbell hip thrust'],'strength','hinge','glutes','barbell','weight_reps'),
(null,'Glute Bridge','glutebridge',array['floor bridge'],'strength','hinge','glutes','bodyweight','bodyweight_reps'),
(null,'Walking Lunge','walkinglunge',array['walking lunges'],'strength','lunge','quadriceps','dumbbell','weight_reps'),
(null,'Reverse Lunge','reverselunge',array['backward lunge'],'strength','lunge','quadriceps','dumbbell','weight_reps'),
(null,'Bulgarian Split Squat','bulgariansplitsquat',array['rear foot elevated split squat','rfess'],'strength','lunge','quadriceps','bench','weight_reps'),
(null,'Bench Press','benchpress',array['barbell bench press'],'strength','horizontal_push','chest','barbell','weight_reps'),
(null,'Incline Bench Press','inclinebenchpress',array['incline barbell press'],'strength','horizontal_push','chest','barbell','weight_reps'),
(null,'Dumbbell Bench Press','dumbbellbenchpress',array['db bench press'],'strength','horizontal_push','chest','dumbbell','weight_reps'),
(null,'Push-Up','pushup',array['push up','press up'],'strength','horizontal_push','chest','bodyweight','bodyweight_reps'),
(null,'Dumbbell Fly','dumbbellfly',array['chest fly'],'strength','horizontal_push','chest','dumbbell','weight_reps'),
(null,'Overhead Press','overheadpress',array['shoulder press','military press'],'strength','vertical_push','shoulders','barbell','weight_reps'),
(null,'Dumbbell Shoulder Press','dumbbellshoulderpress',array['db shoulder press'],'strength','vertical_push','shoulders','dumbbell','weight_reps'),
(null,'Landmine Press','landminepress',array['angled barbell press'],'strength','vertical_push','shoulders','barbell','weight_reps'),
(null,'Pull-Up','pullup',array['pull up'],'strength','vertical_pull','back','pull_up_bar','bodyweight_reps'),
(null,'Chin-Up','chinup',array['chin up'],'strength','vertical_pull','back','pull_up_bar','bodyweight_reps'),
(null,'Lat Pulldown','latpulldown',array['lat pull down'],'strength','vertical_pull','back','cable','weight_reps'),
(null,'Barbell Row','barbellrow',array['bent over row'],'strength','horizontal_pull','back','barbell','weight_reps'),
(null,'Dumbbell Row','dumbbellrow',array['one arm row','db row'],'strength','horizontal_pull','back','dumbbell','weight_reps'),
(null,'Seated Cable Row','seatedcablerow',array['cable row'],'strength','horizontal_pull','back','cable','weight_reps'),
(null,'Barbell Curl','barbellcurl',array['bb curl'],'strength','isolation','biceps','barbell','weight_reps'),
(null,'Dumbbell Curl','dumbbellcurl',array['db curl'],'strength','isolation','biceps','dumbbell','weight_reps'),
(null,'Hammer Curl','hammercurl',array['neutral grip curl'],'strength','isolation','biceps','dumbbell','weight_reps'),
(null,'Triceps Pushdown','tricepspushdown',array['cable pushdown'],'strength','isolation','triceps','cable','weight_reps'),
(null,'Skull Crusher','skullcrusher',array['lying triceps extension'],'strength','isolation','triceps','barbell','weight_reps'),
(null,'Bench Dip','benchdip',array['triceps bench dip'],'strength','vertical_push','triceps','bench','bodyweight_reps'),
(null,'Plank','plank',array['front plank'],'strength','anti_extension','core','bodyweight','duration'),
(null,'Side Plank','sideplank',array['lateral plank'],'strength','anti_rotation','core','bodyweight','duration'),
(null,'Dead Bug','deadbug',array['deadbug'],'rehab','anti_extension','core','bodyweight','repetitions'),
(null,'Bird Dog','birddog',array['quadruped bird dog'],'rehab','anti_rotation','core','bodyweight','repetitions'),
(null,'Russian Twist','russiantwist',array['seated twist'],'strength','rotation','core','bodyweight','repetitions'),
(null,'Hanging Knee Raise','hangingkneeraise',array['hanging leg raise'],'strength','isolation','core','pull_up_bar','bodyweight_reps'),
(null,'Pallof Press','pallofpress',array['anti rotation press'],'strength','anti_rotation','core','cable','repetitions'),
(null,'Lateral Raise','lateralraise',array['side raise'],'strength','isolation','shoulders','dumbbell','weight_reps'),
(null,'Face Pull','facepull',array['rope face pull'],'strength','horizontal_pull','shoulders','cable','weight_reps'),
(null,'Farmer Carry','farmercarry',array['farmers walk','farmer walk'],'conditioning','carry','full_body','dumbbell','distance_duration'),
(null,'Box Jump','boxjump',array['box jumps'],'plyometric','locomotion','full_body','other','repetitions'),
(null,'Kettlebell Swing','kettlebellswing',array['kb swing'],'conditioning','hinge','full_body','kettlebell','repetitions')
on conflict (normalized_name) where user_id is null do update set
  aliases = excluded.aliases,
  category = excluded.category,
  movement_pattern = excluded.movement_pattern,
  primary_muscle_group = excluded.primary_muscle_group,
  equipment = excluded.equipment,
  default_tracking_type = excluded.default_tracking_type,
  is_archived = false;
