import { aggregateActivity, calendarDay, CONDITION_RANGE_LABEL, DAY, days, episodeWindow, PRE_EPISODE_LOOKBACK_DAYS, timelineLayout, timelineX, type Activity, type Episode } from "@/lib/condition-intelligence/model";
import { formatCalendarDay } from "@/lib/measurements/time-window";

export const dateLabel = (at: number, timeZone = "UTC") => formatCalendarDay(calendarDay(at, timeZone));
const colors = ["#2563eb", "#059669", "#9333ea", "#d97706", "#0891b2", "#db2777", "#475569"];
export function HealthEventLegend({ categories }: { categories: string[] }) {
  return <ul className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-slate-600">{categories.map((category, i) => <li key={category} className="flex items-center gap-2"><span className="h-2 w-2 rounded-full" style={{ background: colors[i % colors.length] }}/>{category}</li>)}<li>● Episode</li><li>Shaded: {PRE_EPISODE_LOOKBACK_DAYS}-day lookback</li></ul>;
}
export function PreEpisodeWindow({ left, width, top, bottom, emphasized, subdued }: { left: number; width: number; top: number; bottom: number; emphasized: boolean; subdued: boolean }) { return <rect data-lookback-band="true" data-emphasized={emphasized} x={left} y={top} width={width} height={bottom - top} fill="#dbeafe" opacity={subdued ? 0.35 : 0.7} stroke={emphasized ? "#2563eb" : "none"} strokeWidth={emphasized ? 2 : 0}/>; }
export function EpisodeInterval({ x, y, label }: { x: number; y: number; label: string }) { return <text x={x} y={y} textAnchor="middle" fontSize={11} fill="#475569">{label}</text>; }
export function EpisodeMarker({ episode, x, index, top, centerY, bottom, timeZone, selected, subdued, interactive = true, onSelect }: { episode: Episode; x: number; index: number; top: number; centerY: number; bottom: number; timeZone: string; selected: boolean; subdued: boolean; interactive?: boolean; onSelect: (id: string) => void }) {
  const label = `Episode ${index + 1}, ${dateLabel(episode.start, timeZone)}, ${episode.end === null ? "ongoing" : "completed"}`;
  return <g id={`episode-marker-${episode.id}`} role={interactive ? "button" : "img"} tabIndex={interactive ? 0 : undefined} aria-label={label} aria-pressed={interactive ? selected : undefined} aria-controls={interactive ? "selected-episode-context" : undefined} className={interactive ? "cursor-pointer outline-none [&:focus-visible_.episode-focus]:stroke-blue-600" : undefined} onClick={interactive ? () => onSelect(episode.id) : undefined} onKeyDown={interactive ? event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(episode.id); } } : undefined}>
    <title>{`${label}; ${episode.end === null ? "Ongoing" : days((episode.end - episode.start) / DAY)}; severity ${episode.severity ?? "not recorded"}`}</title>
    <rect className="episode-focus" x={x - 22} y={centerY - 22} width={44} height={44} rx={8} fill="transparent" stroke={selected ? "#2563eb" : "transparent"} strokeWidth={2}/>
    <g opacity={subdued ? 0.5 : 1}><line x1={x} x2={x} y1={top} y2={bottom} stroke="#0f172a" strokeWidth={selected ? 4 : 3}/><circle cx={x} cy={centerY} r={selected ? 12 : 9} fill="#0f172a"/><text x={x} y={35 + index % 2 * 15} textAnchor="middle" fontSize={11} fill="#0f172a">#{index + 1} · {dateLabel(episode.start, timeZone)}</text></g>
  </g>;
}
export function ConditionTimeline({ episodes, healthEvents, start, now, mode, timeZone = "UTC", interactive = true, focused = false, highlightedEpisodes = new Set<string>(), highlightedClusters = new Set<string>(), selectedEpisodeId, onSelectEpisode = () => {} }: { episodes: Episode[]; healthEvents: Activity[]; start: number; now: number; mode: "app" | "marketing"; timeZone?: string; interactive?: boolean; focused?: boolean; highlightedEpisodes?: Set<string>; highlightedClusters?: Set<string>; selectedEpisodeId?: string; onSelectEpisode?: (id: string) => void }) {
  const categories = [...new Set(healthEvents.map(e => e.category))].sort();
  const firstDay = calendarDay(start, timeZone), lastDay = calendarDay(now, timeZone) + DAY;
  const width = Math.max(1200, episodes.length * 150), x = (at: number) => timelineX(Math.max(firstDay, Math.min(lastDay, at)), firstDay, lastDay, width);
  const windows = episodes.map(e => ({ episode: e, ...episodeWindow(e, timeZone) }));
  const layout = timelineLayout(categories);
  return <section data-mode={mode} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><h2 className="text-lg font-semibold">Episode history</h2><p id="timeline-help" className="mt-1 text-sm text-slate-500">{CONDITION_RANGE_LABEL} · Scroll horizontally to explore. Calendar days: {timeZone}. {interactive ? "Select an episode for details." : "Illustrative episode history."}</p><div className="mt-4 max-w-full overflow-x-auto rounded-lg bg-slate-50 focus-visible:ring-2 focus-visible:ring-blue-600" role="region" aria-label="Condition timeline" aria-describedby="timeline-help" tabIndex={0}><svg width={width} height={layout.height} role="group" aria-label="Episodes and daily aggregated health activity" style={{ maxWidth: "none" }}>
    {windows.map(w => <PreEpisodeWindow key={w.episode.id} left={x(w.start)} width={x(w.end) - x(w.start)} top={layout.plotTop} bottom={layout.plotBottom} emphasized={highlightedEpisodes.has(w.episode.id)} subdued={focused && !highlightedEpisodes.has(w.episode.id)}/>)}
    <line data-timeline-axis="true" aria-hidden="true" x1={100} x2={width - 120} y1={layout.centerY} y2={layout.centerY} stroke="#cbd5e1"/>
    {aggregateActivity(healthEvents, timeZone).filter(t => t.at >= firstDay && t.at < lastDay).map(tick => { const key = `${tick.at}:${tick.category}`, selected = highlightedClusters.has(key); return <rect data-highlighted={selected} data-activity-category={tick.category} data-activity-day={tick.at} key={key} x={x(tick.at + DAY / 2) - (selected ? 1 : 0)} y={layout.activityY(categories.indexOf(tick.category)) - (selected ? 1 : 0)} width={selected ? 4 : 2} height={selected ? 10 : 8} opacity={focused && !selected ? 0.4 : 1} stroke={selected ? "#0f172a" : "none"} strokeWidth={selected ? 1 : 0} fill={colors[categories.indexOf(tick.category) % colors.length]}><title>{`${formatCalendarDay(tick.at)} · ${tick.category}: ${tick.count} records${selected ? " · Supporting context" : ""}`}</title></rect>; })}
    {episodes.map((episode, i) => <EpisodeMarker key={episode.id} episode={episode} index={i} x={x(calendarDay(episode.start, timeZone))} top={layout.plotTop} centerY={layout.centerY} bottom={layout.plotBottom} timeZone={timeZone} selected={episode.id === selectedEpisodeId} subdued={focused && !highlightedEpisodes.has(episode.id)} interactive={interactive} onSelect={onSelectEpisode}/>) }
    {episodes.slice(1).map((e, i) => <EpisodeInterval key={e.id} x={(x(calendarDay(e.start, timeZone)) + x(calendarDay(episodes[i].start, timeZone))) / 2} y={layout.intervalY + i % 3 * 14} label={days((e.start - episodes[i].start) / DAY)}/>)}
    <text x={100} y={layout.axisY} fontSize={12}>{dateLabel(start, timeZone)}</text><text x={width - 120} y={layout.axisY} textAnchor="end" fontSize={12}>{dateLabel(now, timeZone)}</text>
  </svg></div>{episodes.length ? <p className="mt-3 text-sm text-slate-600">{days((now - episodes.at(-1)!.start) / 86400000)} since last episode started</p> : null}<HealthEventLegend categories={categories}/></section>;
}
